@Security @Single @ignore
Feature: Securities Single

  Scenario: happy path - ntas ta single check eori pages - with no Payment method
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "securities" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"

    When I enter "01AAAAAAAAAAAAA110" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "Temporary admissions (24 months)" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    #Then I am presented with the "Securities_Enter Importer Eori Page"
    #When I enter "GB000000000000002" on "Securities_Enter Importer Eori Page"
    #And I click continue on "Securities_Enter Importer Eori Page"
    #Then I am presented with the "Securities_Enter Declarant Eori Page"
    #When I enter "GB000000000000002" on "Securities_Enter Declarant Eori Page"
    #And I click continue on "Securities_Enter Declarant Eori Page"
    #Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    #When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    #And I click continue on "Securities_Select Securities Security Id Page"
    #Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    #When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    #And I click continue on "Securities_Select Securities Security Id Page"
    #Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    #When I select radio button "no" on "Securities_Select Securities Security Id Page"
    #And I click continue on "Securities_Select Securities Security Id Page"
    #Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    #When I select radio button "no" on "Securities_Select Securities Security Id Page"
    #And I click continue on "Securities_Select Securities Security Id Page"
    #Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    #When I select radio button "no" on "Securities_Select Securities Security Id Page"
    #And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_HaveYourSupportingDocumentReadyPage"
    When I clickContinue on "Securities_HaveYourSupportingDocumentReadyPage"
    Then I am presented with the "Securities_ConfirmFullRepayment"
    When I select radio button "Yes" on "Securities_ConfirmFullRepayment"
    And I click continue on "Securities_ConfirmFullRepayment"
    Then I am presented with the "Securities_Export Method Page"
    When I select radio button "Declared to a customs warehouse" on "Securities_Export Method Page"
    And I click continue on "Securities_Export Method Page"
    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Importer" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_EnterBankAccountDetailsPage"
    And I enter "" on "Securities_EnterBankAccountDetailsPage"
    When I click continue on "Securities_EnterBankAccountDetailsPage"

    #Then I am presented with the "Securities_Confirm Full Repayment Security Id Page" "ABC0123456"
    #When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page"
    #And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    #Then I am presented with the "Securities_Select Duties Security Id Page" "ABC0123456"
    #When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page"
    #And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    #Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    #When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    #And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    #Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax (VAT)"
    #When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    #And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    #Then I am presented with the "Securities_Confirm Full Repayment Security Id Page2" "DEF6543213"
    #When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page2"
    #And I click continue on "Securities_Confirm Full Repayment Security Id Page2"
    #Then I am presented with the "Securities_Select Duties Security Id Page" "DEF6543213"
    #When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page2"
    #And I click continue on "Securities_Confirm Full Repayment Security Id Page2"
   # Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    #When I enter "10" on "Securities_Enter Claim Security Id Tax Code Page"
    #And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    #Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax (VAT)"
    #When I enter "20" on "Securities_Enter Claim Security Id Tax Code Page"
   # And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    #Then I am presented with the "Securities_Check Claim Page"
    #And I click continue on "Securities_Check Claim Page"

    #Then I am presented with the "Securities_Check Bank Details Page"
    #And I select radio button "yes" on "Securities_Check Bank Details Page"
    #When I click continue on "Securities_Check Bank Details Page"

    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Import declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import declaration"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "Yes" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Export declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "export declaration"
    When I upload a 2 "image.jpg" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    When I click continue if I'm on "UDF_Choose Files Page"

    Then I am presented with the "Securities_EnterAdditionalDetailsPage"
    When I enter "under 500 characters" on "Securities_EnterAdditionalDetailsPage"
    And I click continue on "Securities_EnterAdditionalDetailsPage  "

    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    And I should see the following details
      | Import Movement Reference Number (MRN)    | Local Reference Number (LRN)| Uploaded                                                        | Reason for security deposit           |  Payment method          | Total security deposit value   | Contact address                                         | Payee       | Any information that may support the claim | Claim full amount | What did you do with the goods? | Total     | Duties selected    | A00 - Customs Duty   | Date security deposit made | Claim for security deposit or guarantee | Contact details                              | Name on the account | Account number   | Sort code      |
      | 01AAAAAAAAAAAAA110                        | XFGLKJDSE5GDPOIJEW985T      | document.pdf,Import declaration,image.jpg,Export declaration    | Temporary admissions (24 months)      |  Bank account transfer | £6,000.00                        | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom       | Importer    | under 500 characters                       |Yes                | Declared to a customs warehouse | £6,000.00 | A00 - Customs Duty | £6,000.00            | 13 September 2019          | Yes                                     |Mr John Smith,someemail@mail.com,01234567890  | Mr John Smith       | 11001001         | 123456         |
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"



  @test @a11y @ZAP
  Scenario: happy path - nidac mdp single check eori pages - with no Payment method
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "securities" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"

    When I enter "01AAAAAAAAAAAAA110" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "Missing proof of origin" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    #Then I am presented with the "Securities_Enter Importer Eori Page"
    #When I enter "GB000000000000002" on "Securities_Enter Importer Eori Page"
    #And I click continue on "Securities_Enter Importer Eori Page"
    #Then I am presented with the "Securities_Enter Declarant Eori Page"
    #When I enter "GB000000000000002" on "Securities_Enter Declarant Eori Page"
    #And I click continue on "Securities_Enter Declarant Eori Page"
    #Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    #When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    #And I click continue on "Securities_Select Securities Security Id Page"
    #Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    #When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    #And I click continue on "Securities_Select Securities Security Id Page"
    #Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    #When I select radio button "no" on "Securities_Select Securities Security Id Page"
    #And I click continue on "Securities_Select Securities Security Id Page"
    #Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    #When I select radio button "no" on "Securities_Select Securities Security Id Page"
    #And I click continue on "Securities_Select Securities Security Id Page"
    #Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    #When I select radio button "no" on "Securities_Select Securities Security Id Page"
    #And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_HaveYourSupportingDocumentReadyPage"
    When I clickContinue on "Securities_HaveYourSupportingDocumentReadyPage"
    Then I am presented with the "Securities_ConfirmFullRepayment"
    When I select radio button "Yes" on "Securities_ConfirmFullRepayment"
    And I click continue on "Securities_ConfirmFullRepayment"
    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Importer" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_EnterBankAccountDetailsPage"
    And I enter "" on "Securities_EnterBankAccountDetailsPage"
    When I click continue on "Securities_EnterBankAccountDetailsPage"
    Then I am presented with the "Securities_AddProofOfOrigin" "Proof of origin"
    When I upload a 1 "document.pdf" file on "Securities_AddProofOfOrigin"
    And I click continue if I'm on "Securities_AddProofOfOrigin"
    Then I am presented with the "Securities_NidacAddOtherDocument"
    When I select radio button "yes" on "Securities_NidacAddOtherDocument"
    And I click continue on "Securities_NidacAddOtherDocument"

    Then I am presented with the "Securities_NidacChooseFileTypePage"
    When I select radio button "Commercial invoice" on "Securities_NidacChooseFileTypePage"
    And I click continue on "Securities_NidacChooseFileTypePage "
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    When I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_EnterAdditionalDetailsPage"
    When I enter "under 500 characters" on "Securities_EnterAdditionalDetailsPage"
    And I click continue on "Securities_EnterAdditionalDetailsPage"

    #Then I am presented with the "Securities_Confirm Full Repayment Security Id Page" "ABC0123456"
    #When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page"
    #And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    #Then I am presented with the "Securities_Select Duties Security Id Page" "ABC0123456"
    #When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page"
    #And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    #Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    #When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    #And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    #Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax (VAT)"
    #When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    #And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    #Then I am presented with the "Securities_Confirm Full Repayment Security Id Page2" "DEF6543213"
    #When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page2"
    #And I click continue on "Securities_Confirm Full Repayment Security Id Page2"
    #Then I am presented with the "Securities_Select Duties Security Id Page" "DEF6543213"
    #When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page2"
    #And I click continue on "Securities_Confirm Full Repayment Security Id Page2"
   # Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    #When I enter "10" on "Securities_Enter Claim Security Id Tax Code Page"
    #And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    #Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax (VAT)"
    #When I enter "20" on "Securities_Enter Claim Security Id Tax Code Page"
   # And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    #Then I am presented with the "Securities_Check Claim Page"
    #And I click continue on "Securities_Check Claim Page"

    #Then I am presented with the "Securities_Check Bank Details Page"
    #And I select radio button "yes" on "Securities_Check Bank Details Page"
    #When I click continue on "Securities_Check Bank Details Page"

    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    And I should see the following details
      | Import Movement Reference Number (MRN)    | Local Reference Number (LRN)| Proof of origin     | Other supporting documents                  | Reason for security deposit           |  Payment method          | Total security deposit value   | Contact address                                         | Payee       | Any information that may support the claim | Claim full amount | Total     | Duties selected    | A00 - Customs Duty   | Date security deposit made | Claim for security deposit or guarantee | Contact details                              | Name on the account | Account number   | Sort code      |
      | 01AAAAAAAAAAAAA110                        | XFGLKJDSE5GDPOIJEW985T      | document.pdf        | document.pdf,Commercial invoice             | Missing proof of origin          |  Bank account transfer   | £6,000.00                      | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom       | Importer    | under 500 characters                       |Yes                | £6,000.00 | A00 - Customs Duty | £6,000.00            | 13 September 2019          | Yes                                     |Mr John Smith,someemail@mail.com,01234567890  | Mr John Smith       | 11001001         | 123456         |
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"


  @smoke
  Scenario: Happy path with only importer bank details and displays payee type page - choose importer
    #  60AAAAAAAAAAAAAAA5 => only importer bank details (user is only importer ) - display payee indicator page and navigates to Check Bank Details Page
    When I enter "60AAAAAAAAAAAAAAA5" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "Inward Processing Relief (IPR)" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Check Total Import Discharged Page"
    When I select radio button "yes" on "Securities_Check Total Import Discharged Page"
    And I click continue on "Securities_Check Total Import Discharged Page"
    Then I am presented with the "Securities_Bod3 Mandatory Check Page"
    When I select radio button "no" on "Securities_Bod3 Mandatory Check Page"
    And I click continue on "Securities_Bod3 Mandatory Check Page"
    Then I am presented with the "Securities_Error Claim Invalid No Bod3 Page"
    When I click back button on "Securities_Error Claim Invalid No Bod3 Page"
    Then I am presented with the "Securities_Bod3 Mandatory Check Page"
    When I select radio button "yes" on "Securities_Bod3 Mandatory Check Page"
    And I click continue on "Securities_Bod3 Mandatory Check Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page" "ABC0123456"
    When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Select Duties Security Id Page" "ABC0123456"
    When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax (VAT)"
    When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page2" "DEF6543213"
    When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page2"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page2"
    Then I am presented with the "Securities_Select Duties Security Id Page" "DEF6543213"
    When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page2"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page2"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    When I enter "100" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax (VAT)"
    When I enter "200" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Check Claim Page"
    And I click continue on "Securities_Check Claim Page"
    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Importer" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_Check Bank Details Page"
    And I select radio button "yes" on "Securities_Check Bank Details Page"
    When I click continue on "Securities_Check Bank Details Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Import declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import declaration"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "Yes" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Export declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "export declaration"
    When I upload a 2 "image.jpg" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    When I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    And I should see the following details
      | Import MRN         | Importer name   | Importer email          | Importer telephone | Importer address                            | Declarant name         | Reason for security deposit    | Export declaration           | Total security deposit value | Claim for DEF6543213 | Claim for DEF6543212 | Claim for DEF6543211 | Claim for DEF6543210 | B00 - Value Added Tax (VAT) | Claim for ABC0123456 | Declarant address                                         | Claim full amount | Total   | Duties selected                          | A00 - Customs Duty | Date security deposit made | Contact details                                        | Import declaration              | Name on the account | Account number   | Sort code      | Contact address                             |
      | 60AAAAAAAAAAAAAAA5 | Swift Goods Ltd | enquiries@swftgoods.com | 0207 678 3243      | 14 Briar Lane,London,Pimlico,United Kingdom | Fred Bloggs and Co Ltd | Inward Processing Relief (IPR) | image.jpg,Export declaration | £14,385.52                   | Yes                  | No                   | No                   | No                   | £200.00               | Yes                  | 10 Rillington Place,London,Pimlico,W11 1RH,United Kingdom | Yes               | £300.00 | A00 - Customs Duty,B00 - Value Added Tax (VAT) | £100.00            | 13 September 2019          | Mr John Smith,someemail@mail.com,01234567890 | document.pdf,Import declaration | Consignee Goods Ltd | Ending with 8523 | Ending with 41 | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom |
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"


  Scenario: Data validation check at Check your answers page - with Payment method as Bank account transfer
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "securities" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"
    When I enter "01AAAAAAAAAAAAAAA1" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "UKAP Entry Price" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    When I select radio button "Yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page3" "ABC0123456"
    When I select radio button "Yes" on "Securities_Confirm Full Repayment Security Id Page3"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Check Claim Page"
    And I click continue on "Securities_Check Claim Page"
    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Importer" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_Check Bank Details Page"
    And I select radio button "yes" on "Securities_Check Bank Details Page"
    When I click continue on "Securities_Check Bank Details Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Import declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import declaration"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    And I should see the following details
      | Import MRN         | Importer name   | Importer email          | Importer telephone | Importer address                            | Declarant name         | Reason for security deposit | Import declaration              | Total security deposit value | Contact address                             | Name on the account | Claim for DEF6543213 | Claim for DEF6543212 | Claim for DEF6543211 | Claim for DEF6543210 | Account number   | B00 - Value Added Tax (VAT) | Payment method        | Claim for ABC0123456 | Declarant address                                         | Claim full amount | Total      | Duties selected                          | A00 - Customs Duty | Date security deposit made | Sort code      | Contact details                                        |
      | 01AAAAAAAAAAAAAAA1 | Swift Goods Ltd | enquiries@swftgoods.com | 0207 678 3243      | 14 Briar Lane,London,Pimlico,United Kingdom | Fred Bloggs and Co Ltd | UKAP Entry Price            | document.pdf,Import declaration | £14,085.52                   | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | Swift Goods Ltd     | No                   | No                   | No                   | No                   | Ending with 8523 | £8,085.52             | Bank account transfer | Yes                  | 10 Rillington Place,London,Pimlico,W11 1RH,United Kingdom | Yes               | £14,085.52 | A00 - Customs Duty,B00 - Value Added Tax (VAT) | £6,000.00          | 13 September 2019          | Ending with 41 | Mr John Smith,someemail@mail.com,01234567890 |
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"


  Scenario: Data validation check at Check your answers page - with Payment method as Duty deferment account
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "securities" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"
    When I enter "01AAAAAAAAAAAAAAA1" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "UKAP Entry Price" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page3" "DEF6543213"
    When I select radio button "Yes" on "Securities_Confirm Full Repayment Security Id Page3"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Check Claim Page"
    And I click continue on "Securities_Check Claim Page"
    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Importer" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_Check Bank Details Page"
    And I select radio button "yes" on "Securities_Check Bank Details Page"
    When I click continue on "Securities_Check Bank Details Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Import declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import declaration"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    And I should see the following details
      | Import MRN         | Importer name   | Importer email          | Importer telephone | Importer address                            | Declarant name         | Reason for security deposit | Import declaration              | Total security deposit value | Contact address                             | Claim for DEF6543213 | B00 - Value Added Tax (VAT) | Claim for ABC0123456 | Claim for DEF6543210 | Claim for DEF6543212 | Claim for DEF6543211 | Declarant address                                         | Claim full amount | Total   | Duties selected                          | A00 - Customs Duty | Date security deposit made | Payment method         | Contact details                                        | Name on the account | Account number   | Sort code      |
      | 01AAAAAAAAAAAAAAA1 | Swift Goods Ltd | enquiries@swftgoods.com | 0207 678 3243      | 14 Briar Lane,London,Pimlico,United Kingdom | Fred Bloggs and Co Ltd | UKAP Entry Price            | document.pdf,Import declaration | £300.00                      | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | Yes                  | £200.00               | No                   | No                   | No                   | No                   | 10 Rillington Place,London,Pimlico,W11 1RH,United Kingdom | Yes               | £300.00 | A00 - Customs Duty,B00 - Value Added Tax (VAT) | £100.00            | 13 September 2019          | Duty deferment account | Mr John Smith,someemail@mail.com,01234567890 | Swift Goods Ltd     | Ending with 8523 | Ending with 41 |
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"

  @smoke
  Scenario: Data validation check at Check your answers page - with Payment method as Cash payment
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "securities" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"
    When I enter "01AAAAAAAAAAAAAAA1" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "UKAP Entry Price" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page3" "DEF6543212"
    When I select radio button "Yes" on "Securities_Confirm Full Repayment Security Id Page3"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Check Claim Page"
    And I click continue on "Securities_Check Claim Page"
    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Importer" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_Check Bank Details Page"
    And I select radio button "yes" on "Securities_Check Bank Details Page"
    When I click continue on "Securities_Check Bank Details Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Import declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import declaration"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    And I should see the following details
      | Import MRN         | Importer name   | Importer email          | Importer telephone | Importer address                            | Declarant name         | Reason for security deposit | Import declaration              | Total security deposit value | Contact address                             | Claim for DEF6543213 | B00 - Value Added Tax (VAT) | Claim for ABC0123456 | Claim for DEF6543210 | Claim for DEF6543212 | Claim for DEF6543211 | Declarant address                                         | Claim full amount | Total   | Duties selected                          | A00 - Customs Duty | Date security deposit made | Payment method | Contact details                                        | Name on the account | Account number   | Sort code      |
      | 01AAAAAAAAAAAAAAA1 | Swift Goods Ltd | enquiries@swftgoods.com | 0207 678 3243      | 14 Briar Lane,London,Pimlico,United Kingdom | Fred Bloggs and Co Ltd | UKAP Entry Price            | document.pdf,Import declaration | £300.00                      | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | No                   | £200.00               | No                   | No                   | Yes                  | No                   | 10 Rillington Place,London,Pimlico,W11 1RH,United Kingdom | Yes               | £300.00 | A00 - Customs Duty,B00 - Value Added Tax (VAT) | £100.00            | 13 September 2019          | Cash account   | Mr John Smith,someemail@mail.com,01234567890 | Swift Goods Ltd     | Ending with 8523 | Ending with 41 |
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"

  Scenario: Data validation check at Check your answers page - with Payment method as Guarantee Account
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "securities" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"
    When I enter "01AAAAAAAAAAAAAAA1" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "UKAP Entry Price" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page3" "DEF6543210"
    When I select radio button "Yes" on "Securities_Confirm Full Repayment Security Id Page3"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Check Claim Page"
    And I click continue on "Securities_Check Claim Page"
    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Importer" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Import declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import declaration"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    And I should see the following details
      | Import MRN         | Importer name   | Importer email          | Importer telephone | Importer address                            | Declarant name         | Reason for security deposit | Import declaration              | Total security deposit value | Contact address                             | Claim for DEF6543213 | B00 - Value Added Tax (VAT) | Claim for ABC0123456 | Claim for DEF6543210 | Claim for DEF6543212 | Claim for DEF6543211 | Declarant address                                         | Claim full amount | Total   | Duties selected                          | A00 - Customs Duty | Date security deposit made | Payment method | Contact details                                        |
      | 01AAAAAAAAAAAAAAA1 | Swift Goods Ltd | enquiries@swftgoods.com | 0207 678 3243      | 14 Briar Lane,London,Pimlico,United Kingdom | Fred Bloggs and Co Ltd | UKAP Entry Price            | document.pdf,Import declaration | £300.00                      | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | No                   | £200.00               | No                   | Yes                  | No                   | No                   | 10 Rillington Place,London,Pimlico,W11 1RH,United Kingdom | Yes               | £300.00 | A00 - Customs Duty,B00 - Value Added Tax (VAT) | £100.00            | 13 September 2019          | Guarantee      | Mr John Smith,someemail@mail.com,01234567890 |
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"

  @smoke
  Scenario: Data validation check at Check your answers page - with Payment method as Individual Guarantee
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "securities" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"
    When I enter "01AAAAAAAAAAAAAAA1" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "Revenue Dispute or Inland Pre-Clearance (IPC)" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page3" "DEF6543211"
    When I select radio button "Yes" on "Securities_Confirm Full Repayment Security Id Page3"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Check Claim Page"
    And I click continue on "Securities_Check Claim Page"
    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Importer" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Import declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import declaration"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    And I should see the following details
      | Import MRN         | Importer name   | Importer email          | Importer telephone | Importer address                            | Declarant name         | Reason for security deposit                   | Import declaration              | Total security deposit value | Contact address                             | Claim for DEF6543213 | B00 - Value Added Tax (VAT) | Claim for ABC0123456 | Claim for DEF6543210 | Claim for DEF6543212 | Claim for DEF6543211 | Declarant address                                         | Claim full amount | Total   | Duties selected                          | A00 - Customs Duty | Date security deposit made | Payment method | Contact details                                        |
      | 01AAAAAAAAAAAAAAA1 | Swift Goods Ltd | enquiries@swftgoods.com | 0207 678 3243      | 14 Briar Lane,London,Pimlico,United Kingdom | Fred Bloggs and Co Ltd | Revenue Dispute or Inland Pre-Clearance (IPC) | document.pdf,Import declaration | £300.00                      | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | No                   | £200.00               | No                   | No                   | No                   | Yes                  | 10 Rillington Place,London,Pimlico,W11 1RH,United Kingdom | Yes               | £300.00 | A00 - Customs Duty,B00 - Value Added Tax (VAT) | £100.00            | 13 September 2019          | Guarantee      | Mr John Smith,someemail@mail.com,01234567890 |
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"


  Scenario: happy path - Securities without importer/declarant eori and with Bod4 check
    When I enter "01AAAAAAAAAAAAAAA1" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "End Use Relief" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Check Total Import Discharged Page"
    When I select radio button "yes" on "Securities_Check Total Import Discharged Page"
    And I click continue on "Securities_Check Total Import Discharged Page"
    Then I am presented with the "Securities_Bod4 Mandatory Check Page"
    When I select radio button "No" on "Securities_Bod4 Mandatory Check Page"
    And I click continue on "Securities_Bod4 Mandatory Check Page"
    Then I am presented with the "Securities_Error Claim Invalid No Bod4 Page"


  Scenario: happy path - check importer/declarant eori pages and export method page
    When I enter "01AAAAAAAAAAAAAAA2" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "Temporary Admissions (2 months Expiration)" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Enter Importer Eori Page"
    When I enter "GB000000000000002" on "Securities_Enter Importer Eori Page"
    And I click continue on "Securities_Enter Importer Eori Page"
    Then I am presented with the "Securities_Enter Declarant Eori Page"
    When I enter "GB000000000000002" on "Securities_Enter Declarant Eori Page"
    And I click continue on "Securities_Enter Declarant Eori Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Export Method Page"
    When I select radio button "Exported in single shipment" on "Securities_Export Method Page"
    And I click continue on "Securities_Export Method Page"
    Then I am presented with the "Securities_Enter Export Movement Reference Number Page"
    When I enter "41ABCDEFGHIJKLMNO1" on "Securities_Enter Export Movement Reference Number Page"
    And I click continue on "Securities_Enter Export Movement Reference Number Page"
    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Claimant Details Page"


  Scenario: happy path - Temporary admission and Exported in multiple shipment
    When I enter "01AAAAAAAAAAAAAAA2" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "Temporary Admissions (2 years Expiration)" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Enter Importer Eori Page"
    When I enter "GB000000000000002" on "Securities_Enter Importer Eori Page"
    And I click continue on "Securities_Enter Importer Eori Page"
    Then I am presented with the "Securities_Enter Declarant Eori Page"
    When I enter "GB000000000000002" on "Securities_Enter Declarant Eori Page"
    And I click continue on "Securities_Enter Declarant Eori Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Export Method Page"
    When I select radio button "Exported in multiple shipments" on "Securities_Export Method Page"
    And I click continue on "Securities_Export Method Page"
    Then I am presented with the "Securities_Enter Export Movement Reference Number Multiple Page"
    When I enter "41ABCDEFGHIJKLMNO1" on "Securities_Enter Export Movement Reference Number Multiple Page"
    And I click continue on "Securities_Enter Export Movement Reference Number Multiple Page"
    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Claimant Details Page"


  Scenario: Happy path with no document upload
    When I enter "01AAAAAAAAAAAAAAA1" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "Missing document: preference" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page3" "ABC0123456"
    When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page3"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page3"
    Then I am presented with the "Securities_Select Duties Security Id Page" "ABC0123456"
    When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page3"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page3"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    When I enter "100" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax (VAT)"
    When I enter "50" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Check Claim Page"
    And I click continue on "Securities_Check Claim Page"
    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Importer" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_Check Bank Details Page"
    And I select radio button "yes" on "Securities_Check Bank Details Page"
    When I click continue on "Securities_Check Bank Details Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Commercial invoice" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    And I select radio button "No" on "UDF_Choose Files Page"
    When I click continue on "UDF_Choose Files Page"
    Then I am presented with the "UDF_Choose Files Page" error page
    When I upload a 1 "image.jpg" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"


  Scenario: error message on select securities page
    When I enter "01AAAAAAAAAAAAAAA1" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "UKAP Entry Price" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    When I click continue on "Securities_Select Securities Security Id Page"
    Then The error summary title is "There is a problem" and the error message is "Select Yes if you are claiming for this Security"

  Scenario: Happy path with only importer bank details and displays payee type page - choose declarant
    #  60AAAAAAAAAAAAAAA5 => only importer bank details (user is only importer ) - display payee indicator page and navigates to /enter-bank-account-details after /bank-account-type page
    When I enter "60AAAAAAAAAAAAAAA5" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "Inward Processing Relief (IPR)" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Check Total Import Discharged Page"
    When I select radio button "yes" on "Securities_Check Total Import Discharged Page"
    And I click continue on "Securities_Check Total Import Discharged Page"
    Then I am presented with the "Securities_Bod3 Mandatory Check Page"
    When I select radio button "no" on "Securities_Bod3 Mandatory Check Page"
    And I click continue on "Securities_Bod3 Mandatory Check Page"
    Then I am presented with the "Securities_Error Claim Invalid No Bod3 Page"
    When I click back button on "Securities_Error Claim Invalid No Bod3 Page"
    Then I am presented with the "Securities_Bod3 Mandatory Check Page"
    When I select radio button "yes" on "Securities_Bod3 Mandatory Check Page"
    And I click continue on "Securities_Bod3 Mandatory Check Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page" "ABC0123456"
    When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Select Duties Security Id Page" "ABC0123456"
    When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax (VAT)"
    When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page2" "DEF6543213"
    When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page2"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page2"
    Then I am presented with the "Securities_Select Duties Security Id Page" "DEF6543213"
    When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page2"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page2"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    When I enter "10" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax (VAT)"
    When I enter "20" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Check Claim Page"
    And I click continue on "Securities_Check Claim Page"
    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Declarant" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_Bank Account Type Page"
    When I select radio button "Business bank account" on "Securities_Bank Account Type Page"
    And I click continue on "Securities_Bank Account Type Page"
    Then I am presented with the "Securities_Enter Bank Account Details Page"
    When I enter "" on "Securities_Enter Bank Account Details Page"
    And I click continue on "Securities_Enter Bank Account Details Page"
    Then I am presented with the "Securities_Check Bank Details Page"
    And I select radio button "yes" on "Securities_Check Bank Details Page"
    When I click continue on "Securities_Check Bank Details Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Import declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import declaration"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "Yes" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Export declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "export declaration"
    When I upload a 2 "image.jpg" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    When I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    And I should see the following details
      | Import MRN         | Importer name   | Importer email          | Importer telephone | Importer address                            | Declarant name         | Reason for security deposit    | Export declaration           | Total security deposit value | Claim for DEF6543213 | Claim for DEF6543212 | Claim for DEF6543211 | Claim for DEF6543210 | B00 - Value Added Tax (VAT) | Claim for ABC0123456 | Declarant address                                         | Claim full amount | Total   | Duties selected                          | A00 - Customs Duty | Date security deposit made | Contact details                                        | Import declaration              | Name on the account | Account number   | Sort code      | Contact address                             |
      | 60AAAAAAAAAAAAAAA5 | Swift Goods Ltd | enquiries@swftgoods.com | 0207 678 3243      | 14 Briar Lane,London,Pimlico,United Kingdom | Fred Bloggs and Co Ltd | Inward Processing Relief (IPR) | image.jpg,Export declaration | £14,385.52                   | Yes                  | No                   | No                   | No                   | £180.00               | Yes                  | 10 Rillington Place,London,Pimlico,W11 1RH,United Kingdom | No               | £270.00 | A00 - Customs Duty,B00 - Value Added Tax (VAT) | £90.00            | 13 September 2019          | Mr John Smith,someemail@mail.com,01234567890 | document.pdf,Import declaration | Mr John Smith       | 11001001 | 123456 | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom |
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"

  @ignore
  Scenario: with only importer bank details (user is both importer and declarant)
#  60AAAAAAAAAAAAAAA2 => only importer bank details (user is both importer and declarant) - CMA not eligible - skips payee indicator page and navigates to /check-bank-details page
    When I enter "60AAAAAAAAAAAAAAA2" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "Inward Processing Relief (IPR)" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Check Total Import Discharged Page"
    When I select radio button "yes" on "Securities_Check Total Import Discharged Page"
    And I click continue on "Securities_Check Total Import Discharged Page"
    Then I am presented with the "Securities_Bod3 Mandatory Check Page"
    When I select radio button "no" on "Securities_Bod3 Mandatory Check Page"
    And I click continue on "Securities_Bod3 Mandatory Check Page"
    Then I am presented with the "Securities_Error Claim Invalid No Bod3 Page"
    When I click back button on "Securities_Error Claim Invalid No Bod3 Page"
    Then I am presented with the "Securities_Bod3 Mandatory Check Page"
    When I select radio button "yes" on "Securities_Bod3 Mandatory Check Page"
    And I click continue on "Securities_Bod3 Mandatory Check Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page" "ABC0123456"
    When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Select Duties Security Id Page" "ABC0123456"
    When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax (VAT)"
    When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page2" "DEF6543213"
    When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page2"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page2"
    Then I am presented with the "Securities_Select Duties Security Id Page" "DEF6543213"
    When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page2"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page2"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    When I enter "10" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax (VAT)"
    When I enter "20" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Check Claim Page"
    And I click continue on "Securities_Check Claim Page"
    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Importer" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_Check Bank Details Page"
    And I select radio button "yes" on "Securities_Check Bank Details Page"
    When I click continue on "Securities_Check Bank Details Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Import declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import declaration"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "Yes" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Export declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "export declaration"
    When I upload a 2 "image.jpg" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    When I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    And I should see the following details
      | Import MRN         | Importer name                                     | Reason for security deposit    | Export declaration           | Total security deposit value | Claim for DEF6543213 | Claim for DEF6543212 | Claim for DEF6543211 | Claim for DEF6543210 | B00 - Value Added Tax (VAT) | Claim for ABC0123456                                        | Claim full amount | Total   | Duties selected                          | A00 - Customs Duty | Date security deposit made | Contact details                                        | Import declaration              | Name on the account | Account number   | Sort code      | Contact address                             |
      | 60AAAAAAAAAAAAAAA2 | Swift Goods Ltd      | Inward Processing Relief (IPR) | image.jpg,Export declaration | £14,385.52                   | Yes                  | No                   | No                   | No                   | £180.00               | Yes                 | No               | £270.00 | A00 - Customs Duty,B00 - Value Added Tax (VAT) | £90.00            | 13 September 2019          | Mr John Smith,someemail@mail.com,01234567890 | document.pdf,Import declaration | Consignee Goods Ltd | Ending with 8523 | Ending with 41 | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom |
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"