@Security @Single
Feature: Securities Single - XIEORI

  @test
  Scenario: happy path - check importer/declarant eori pages - with no Payment method
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "securities" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"
    When I enter "01XIDCAAAAAAAAAAA2" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "Temporary Admission (24 months)" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Enter Importer Eori Page"
    When I enter "XI000000000000002" on "Securities_Enter Importer Eori Page"
    And I click continue on "Securities_Enter Importer Eori Page"
    Then I am presented with the "Securities_Enter Declarant Eori Page"
    When I enter "XI000000000000002" on "Securities_Enter Declarant Eori Page"
    And I click continue on "Securities_Enter Declarant Eori Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_MulCheck Declaration Details Page"
    And I click continue on "Securities_MulCheck Declaration Details Page"
    Then I am presented with the "Securities_HaveYourSupportingDocumentReadyPage"
    When I clickContinue on "Securities_HaveYourSupportingDocumentReadyPage"

    Then I am presented with the "Securities_Export Method Page"
    When I select radio button "Declared to a customs warehouse" on "Securities_Export Method Page"
    And I click continue on "Securities_Export Method Page"

    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page"
    When I select radio button "Yes" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"

    Then I am presented with the "Securities_MulCheck Claim Page"
    And I click continue on "Securities_MulCheck Claim Page"
    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Importer" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_EnterBankAccountDetailsPage"
    And I enter "" on "Securities_EnterBankAccountDetailsPage"
    When I click continue on "Securities_EnterBankAccountDetailsPage"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Import declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import declaration"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"

    Then I am presented with the "Securities_EnterAdditionalDetailsPage"
    When I enter "under 500 characters" on "Securities_EnterAdditionalDetailsPage"
    And I click continue on "Securities_EnterAdditionalDetailsPage "

    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    And I should see the following details
      | Import Movement Reference Number (MRN)   | Reason for security deposit           |Local Reference Number (LRN) |Uploaded                        | Total security deposit value     | What did you do with the goods?|Contact address                                      | Claim for security deposit or guarantee 1 of 5 | Claim for security deposit or guarantee 2 of 5| Claim for security deposit or guarantee 3 of 5 | Claim for security deposit or guarantee 4 of 5 |Duties selected                                   |B00 - Value Added Tax (VAT) |A00 - Customs Duty |Total     |Claim for security deposit or guarantee 5 of 5 | Do you want to provide more detail?|Claim full amount  | Payee    | Sort code | Date security deposit made | Contact details                              | Name on the account | Account number   | Payment method |
      | 01XIDCAAAAAAAAAAA2                       | Temporary Admission (24 months)       | XFGLKJDSE5GDPOIJEW985T       |document.pdf,Import declaration | £14,085.52                       | Declared to a customs warehouse|12 Skybricks Road,Coventry,CV3 6EA,United Kingdom    | Yes                                            | No                                            | No                                             | No                                             | A00 - Customs Duty,B00 - Value Added Tax (VAT)   |£8,085.52                   | £6,000.00         |£14,085.52|No                                             |under 500 characters                |Yes                | Importer | 123456    | 13 September 2019          | Mr John Smith,someemail@mail.com,01234567890 | Mr John Smith       | 11001001         | Bank account transfer |
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"


