@Security @Single
Feature: Securities Single - XIEORI

  Background: Securities common steps
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "securities" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"


  Scenario: happy path - check importer/declarant eori pages - with no Payment method
    When I enter "01XIDCAAAAAAAAAAA2" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "Manual override of duty amount" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Enter Importer Eori Page"
    When I enter "XI000000000000002" on "Securities_Enter Importer Eori Page"
    And I click continue on "Securities_Enter Importer Eori Page"
    Then I am presented with the "Securities_Enter Declarant Eori Page"
    When I enter "XI000000000000002" on "Securities_Enter Declarant Eori Page"
    And I click continue on "Securities_Enter Declarant Eori Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page" "ABC0123456"
    When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Select Duties Security Id Page" "ABC0123456"
    When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax"
    When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page2" "DEF6543213"
    When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page2"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page2"
    Then I am presented with the "Securities_Select Duties Security Id Page" "DEF6543213"
    When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page2"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page2"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    When I enter "10" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax"
    When I enter "20" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Check Claim Page"
    And I click continue on "Securities_Check Claim Page"
    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Importer" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_Check Bank Details Page"
    And I select radio button "yes" on "Securities_Check Bank Details Page"
    When I click continue on "Securities_Check Bank Details Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Import declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import declaration"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "Yes" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Evidence supporting your claim" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "evidence supporting your claim"
    When I upload a 2 "image.jpg" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    When I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    And I should see the following details
      | Import MRN         | Importer name   | Importer email          | Importer telephone | Importer address                            | Declarant name         | Reason for security deposit    | Import declaration              | Total security deposit value | Contact address                                           | Claim for DEF6543213 | Claim for DEF6543212 | Claim for DEF6543211 | Claim for DEF6543210 | B00 - Value Added Tax | Claim for ABC0123456 | Declarant address                                         | Claim full amount | Total   | Duties selected                          | A00 - Customs Duty | Date security deposit made | Contact details             | Evidence supporting your claim           | Name on the account | Account number   | Sort code      |
      | 01XIDCAAAAAAAAAAA2 | Swift Goods Ltd | enquiries@swftgoods.com | 0207 678 3243      | 14 Briar Lane,London,Pimlico,United Kingdom | Fred Bloggs and Co Ltd | Manual override of duty amount | document.pdf,Import declaration | £14,385.52                   | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | Yes                  | No                   | No                   | No                   | £180.00               | Yes                  | 10 Rillington Place,London,Pimlico,W11 1RH,United Kingdom | No               | £270.00 | A00 - Customs Duty,B00 - Value Added Tax | £90.00            | 13 September 2019          | Mr John Smith,someemail@mail.com,01234567890 | image.jpg,Evidence supporting your claim | Swift Goods Ltd     | Ending with 8523 | Ending with 41 |
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"

  @smoke
  Scenario: happy path - Securities without importer/declarant eori
    When I enter "01XICAAAAAAAAAAAA1" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "Inward Processing Relief (IPR)" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Check Total Import Discharged Page"
    When I select radio button "yes" on "Securities_Check Total Import Discharged Page"
    And I click continue on "Securities_Check Total Import Discharged Page"
    Then I am presented with the "Securities_Bod3 Mandatory Check Page"
    When I select radio button "no" on "Securities_Bod3 Mandatory Check Page"
    And I click continue on "Securities_Bod3 Mandatory Check Page"
    Then I am presented with the "Securities_Error Claim Invalid No Bod3 Page"
    When I click back button on "Securities_Error Claim Invalid No Bod3 Page"
    Then I am presented with the "Securities_Bod3 Mandatory Check Page"
    When I select radio button "yes" on "Securities_Bod3 Mandatory Check Page"
    And I click continue on "Securities_Bod3 Mandatory Check Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page" "ABC0123456"
    When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Select Duties Security Id Page" "ABC0123456"
    When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax"
    When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page2" "DEF6543213"
    When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page2"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page2"
    Then I am presented with the "Securities_Select Duties Security Id Page" "DEF6543213"
    When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page2"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page2"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    When I enter "100" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax"
    When I enter "200" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Check Claim Page"
    And I click continue on "Securities_Check Claim Page"
    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Importer" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_Check Bank Details Page"
    And I select radio button "yes" on "Securities_Check Bank Details Page"
    When I click continue on "Securities_Check Bank Details Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Import declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import declaration"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "Yes" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Export declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "export declaration"
    When I upload a 2 "image.jpg" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    When I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    And I should see the following details
      | Import MRN         | Importer name   | Importer email          | Importer telephone | Importer address                            | Declarant name         | Reason for security deposit    | Export declaration           | Total security deposit value | Claim for DEF6543213 | Claim for DEF6543212 | Claim for DEF6543211 | Claim for DEF6543210 | B00 - Value Added Tax | Claim for ABC0123456 | Declarant address                                         | Claim full amount | Total   | Duties selected                          | A00 - Customs Duty | Date security deposit made | Contact details                            | Import declaration              | Name on the account | Account number   | Sort code      | Contact address                                           |
      | 01XICAAAAAAAAAAAA1 | Swift Goods Ltd | enquiries@swftgoods.com | 0207 678 3243      | 14 Briar Lane,London,Pimlico,United Kingdom | Fred Bloggs and Co Ltd | Inward Processing Relief (IPR) | image.jpg,Export declaration | £14,385.52                   | Yes                  | No                   | No                   | No                   | £200.00               | Yes                  | 10 Rillington Place,London,Pimlico,W11 1RH,United Kingdom | Yes               | £300.00 | A00 - Customs Duty,B00 - Value Added Tax | £100.00            | 13 September 2019          | Mr John Smith,someemail@mail.com,01234567890 | document.pdf,Import declaration | Swift Goods Ltd     | Ending with 8523 | Ending with 41 | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom |
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"

  @smoke
  Scenario: Data validation check at Check your answers page - with Payment method as Bank account transfer
    When I enter "10XIDAAAAAAAAAAAA1" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "UKAP Entry Price" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    When I select radio button "Yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page3" "ABC0123456"
    When I select radio button "Yes" on "Securities_Confirm Full Repayment Security Id Page3"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Check Claim Page"
    And I click continue on "Securities_Check Claim Page"
    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Importer" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_Check Bank Details Page"
    And I select radio button "yes" on "Securities_Check Bank Details Page"
    When I click continue on "Securities_Check Bank Details Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Import declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import declaration"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    And I should see the following details
      | Import MRN         | Importer name   | Importer email          | Importer telephone | Importer address                            | Declarant name         | Reason for security deposit | Import declaration              | Total security deposit value | Contact address                             | Name on the account | Claim for DEF6543213 | Claim for DEF6543212 | Claim for DEF6543211 | Claim for DEF6543210 | Account number   | B00 - Value Added Tax | Payment method        | Claim for ABC0123456 | Declarant address                                         | Claim full amount | Total      | Duties selected                          | A00 - Customs Duty | Date security deposit made | Sort code      | Contact details                                        |
      | 10XIDAAAAAAAAAAAA1 | Swift Goods Ltd | enquiries@swftgoods.com | 0207 678 3243      | 14 Briar Lane,London,Pimlico,United Kingdom | Fred Bloggs and Co Ltd | UKAP Entry Price            | document.pdf,Import declaration | £14,085.52                   | 14 Briar Lane,London,Pimlico,United Kingdom | Swift Goods Ltd     | No                   | No                   | No                   | No                   | Ending with 8523 | £8,085.52             | Bank account transfer | Yes                  | 10 Rillington Place,London,Pimlico,W11 1RH,United Kingdom | Yes               | £14,085.52 | A00 - Customs Duty,B00 - Value Added Tax | £6,000.00          | 13 September 2019          | Ending with 41 | Frank Sidebotham,enquiries@swftgoods.com,0207 678 3243 |
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"

