@Security @Single @ignore
Feature: Securities Single

  @test
  Scenario: happy path - ntas TA single check eori pages - with no Payment method
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "securities" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"
    When I enter "01AAAAAAAAAAAAA110" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "Temporary Admission (24 months)" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"

    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_HaveYourSupportingDocumentReadyPage"
    When I clickContinue on "Securities_HaveYourSupportingDocumentReadyPage"
    Then I am presented with the "Securities_ConfirmFullRepayment"
    When I select radio button "Yes" on "Securities_ConfirmFullRepayment"
    And I click continue on "Securities_ConfirmFullRepayment"
    Then I am presented with the "Securities_Export Method Page"
    When I select radio button "Declared to a customs warehouse" on "Securities_Export Method Page"
    And I click continue on "Securities_Export Method Page"
    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Importer" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_EnterBankAccountDetailsPage"
    And I enter "" on "Securities_EnterBankAccountDetailsPage"
    When I click continue on "Securities_EnterBankAccountDetailsPage"

    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Import declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import declaration"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "Yes" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Export declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "export declaration"
    When I upload a 2 "image.jpg" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    When I click continue if I'm on "UDF_Choose Files Page"

    Then I am presented with the "Securities_EnterAdditionalDetailsPage"
    When I enter "under 500 characters" on "Securities_EnterAdditionalDetailsPage"
    And I click continue on "Securities_EnterAdditionalDetailsPage "

    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    And I should see the following details
      | Movement Reference Number (MRN)       | Do you want to claim back the full amount?   | Uploaded files                                                  |Why was a security deposit needed?         | Address                                           | Payee       | Do you want to provide more detail? | What did you do with the goods? | Total     | What do you want to claim?  | A00 - Customs Duty    | Personal details                             | Bank details                       |
      | 01AAAAAAAAAAAAA110                    |  Yes                                         |Import declaration:,document.pdf,Export declaration:,image.jpg   |Temporary Admission (24 months)            | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | Importer    | under 500 characters               | Declared to a customs warehouse | £6,000.00 | A00 - Customs Duty          | £6,000.00             |Mr John Smith,someemail@mail.com,01234567890  | Mr John Smith,123456,11001001      |
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"


  @test
  Scenario: happy path - nidac mdp single check eori pages - with no Payment method
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "securities" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"

    When I enter "01AAAAAAAAAAAAA110" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "Missing proof of origin" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"

    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_HaveYourSupportingDocumentReadyPage"
    When I clickContinue on "Securities_HaveYourSupportingDocumentReadyPage"
    Then I am presented with the "Securities_ConfirmFullRepayment"
    When I select radio button "Yes" on "Securities_ConfirmFullRepayment"
    And I click continue on "Securities_ConfirmFullRepayment"
    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Importer" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_EnterBankAccountDetailsPage"
    And I enter "" on "Securities_EnterBankAccountDetailsPage"
    When I click continue on "Securities_EnterBankAccountDetailsPage"

    Then I am presented with the "Securities_AddProofOfOrigin" "Proof of origin"
    When I upload a 1 "document.pdf" file on "Securities_AddProofOfOrigin"
    And I click continue if I'm on "Securities_AddProofOfOrigin"
    Then I am presented with the "Securities_NidacAddOtherDocument"
    When I select radio button "yes" on "Securities_NidacAddOtherDocument"
    And I click continue on "Securities_NidacAddOtherDocument"

    Then I am presented with the "Securities_NidacChooseFileTypePage"
    When I select radio button "Commercial invoice" on "Securities_NidacChooseFileTypePage"
    And I click continue on "Securities_NidacChooseFileTypePage "
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    When I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_EnterAdditionalDetailsPage"
    When I enter "under 500 characters" on "Securities_EnterAdditionalDetailsPage"
    And I click continue on "Securities_EnterAdditionalDetailsPage"

    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    And I should see the following details
      | Movement Reference Number (MRN)    |Do you want to claim back the full amount?  |Proof of origin     | Other uploaded files                  | Why was a security deposit needed?   | Address                                           | Payee       | Do you want to provide more detail? | What do you want to claim? | Total   |A00 - Customs Duty     | Do you want to add other documents to your claim? | Personal details      | Bank details |
      | 01AAAAAAAAAAAAA110                 |Yes                                         | document.pdf       | Commercial invoice:,document.pdf      | Missing proof of origin              | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | Importer    | under 500 characters                       |A00 - Customs Duty             | £6,000.00   |£6,000.00         |Yes               |Mr John Smith,someemail@mail.com,01234567890    | Mr John Smith,123456,11001001 |
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"

 @test
  Scenario: happy path - Temporary admission and Exported in multiple shipment
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "securities" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"

    When I enter "01AAAAAAAAAAAAA110" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "Temporary Admission (2 months)" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"

    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_HaveYourSupportingDocumentReadyPage"
    When I clickContinue on "Securities_HaveYourSupportingDocumentReadyPage"
    Then I am presented with the "Securities_ConfirmFullRepayment"
    When I select radio button "No" on "Securities_ConfirmFullRepayment"
    And I click continue on "Securities_ConfirmFullRepayment"
    Then I am presented with the "Securities_ConfirmPartialpayment"

    When I select radio button "Yes" on "Securities_ConfirmPartialpayment"
    And I click continue on "Securities_ConfirmPartialpayment"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_CheckClaimPage"
    And I click continue on "Securities_CheckClaimPage"

    Then I am presented with the "Securities_Export Method Page"
    When I select radio button "Exported in single or multiple shipments" on "Securities_Export Method Page"
    And I click continue on "Securities_Export Method Page"
    Then I am presented with the "Securities_Enter Export Movement Reference Number Multiple Page"
    When I enter "41ABCDEFGHIJKLMNO1" on "Securities_Enter Export Movement Reference Number Multiple Page"
    And I select radio button "No" on "Securities_Enter Export Movement Reference Number Multiple Page"
    And I click continue on "Securities_Enter Export Movement Reference Number Multiple Page"

    Then I am presented with the "Securities_Choose Payee Type Page"
    And I select radio button "Importer" on "Securities_Choose Payee Type Page"
    When I click continue on "Securities_Choose Payee Type Page"
    Then I am presented with the "Securities_EnterBankAccountDetailsPage"
    And I enter "" on "Securities_EnterBankAccountDetailsPage"
    When I click continue on "Securities_EnterBankAccountDetailsPage"

    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Import declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import declaration"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "Yes" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Export declaration" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "export declaration"
    When I upload a 2 "image.jpg" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    When I click continue if I'm on "UDF_Choose Files Page"

    Then I am presented with the "Securities_EnterAdditionalDetailsPage"
    When I enter "under 500 characters" on "Securities_EnterAdditionalDetailsPage"
    And I click continue on "Securities_EnterAdditionalDetailsPage"

    Then I am presented with the "Securities_Change Contact Details Page"
    And I enter "" on "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    And I should see the following details
      | Movement Reference Number (MRN)       | Do you want to claim back the full amount?   | Uploaded files                                                  |Why was a security deposit needed?         | Address                                           | Payee       | Do you want to provide more detail? |What did you do with the goods? |1st export MRN |Total     | What do you want to claim?  | A00 - Customs Duty    | Personal details                             | Bank details                       |
      | 01AAAAAAAAAAAAA110                    |  No                                         |Import declaration:,document.pdf,Export declaration:,image.jpg   |Temporary Admission (2 months)            | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | Importer    | under 500 characters               | Exported in single shipment   | 41ABCDEFGHIJKLMNO1    |£500.00 | A00 - Customs Duty          | £500.00             |Mr John Smith,someemail@mail.com,01234567890  | Mr John Smith,123456,11001001      |
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"


