@Security @Single
Feature: Security Single

  @test
  Scenario: happy path - check importer/declarant eori pages
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "securities" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"
    When I enter "01AAAAAAAAAAAAAAA2" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "End-use Relief" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Enter Importer Eori Page"
    When I enter "GB000000000000002" on "Securities_Enter Importer Eori Page"
    And I click continue on "Securities_Enter Importer Eori Page"
    Then I am presented with the "Securities_Enter Declarant Eori Page"
    When I enter "GB000000000000002" on "Securities_Enter Declarant Eori Page"
    And I click continue on "Securities_Enter Declarant Eori Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 2,ABC0123456"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 2,DEF6543210"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Check Total Import Discharged Page"
    When I select radio button "yes" on "Securities_Check Total Import Discharged Page"
    And I click continue on "Securities_Check Total Import Discharged Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page" "ABC0123456"
    When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Select Duties Security Id Page"
    When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax"
    When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page" "DEF6543210"
    When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Select Duties Security Id Page"
    When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    When I enter "100" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax"
    When I enter "200" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"


  @test
  Scenario: happy path - Securities without importer/declarant eori
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "securities" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"
    When I enter "01AAAAAAAAAAAAAAA1" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "End-use Relief" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 2,ABC0123456"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 2,DEF6543210"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Check Total Import Discharged Page"
    When I select radio button "yes" on "Securities_Check Total Import Discharged Page"
    And I click continue on "Securities_Check Total Import Discharged Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page" "ABC0123456"
    When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Select Duties Security Id Page"
    When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax"
    When I enter "500" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page" "DEF6543210"
    When I select radio button "No" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Select Duties Security Id Page"
    When I select "A00,B00" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "A00 - Customs Duty"
    When I enter "100" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"
    Then I am presented with the "Securities_Enter Claim Security Id Tax Code Page" "B00 - Value Added Tax"
    When I enter "200" on "Securities_Enter Claim Security Id Tax Code Page"
    And I click continue on "Securities_Enter Claim Security Id Tax Code Page"