@C285 @Scheduled @BrowserStack
Feature: C285 Scheduled NI (bulk enabled, entry disabled)

  Background:
    Given the "Bulk Claim" feature is "enabled"
    Given the "Entry Number" feature is "disabled"
    Given the "Northern Ireland" feature is "enabled"
    Given the "Rejected Goods" feature is "disabled"
    Given the "Internal Upload Documents" feature is "enabled"

  @test @a11y @ZAP
  Scenario: happy path - NI enabled
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000005" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Choose How Many Mrns Page"
    When I select radio button "schedule" on "Choose How Many Mrns Page"
    And I click continue on "Choose How Many Mrns Page"
    Then I am presented with the "Scheduled_Enter Movement Reference Number Page"
    When I enter "50AAAAAAAAAAAAAAA1" on "Scheduled_Enter Movement Reference Number Page"
    And I click continue on "Scheduled_Enter Movement Reference Number Page"
    Then I am presented with the "Scheduled_Check Declaration Details Page"
    And I select radio button "yes" on "Scheduled_Check Declaration Details Page"
    And I click continue on "Scheduled_Check Declaration Details Page"
    Then I am presented with the "Scheduled_Scheduled Document Upload Upload Page"
    When I upload a "document.pdf" file on "Scheduled_Scheduled Document Upload Upload Page"
    And I click continue on "Scheduled_Scheduled Document Upload Upload Page"
    And I click continue if I'm on "Scheduled_Scheduled Document Upload Progress Page"
    Then I am presented with the "Scheduled_Scheduled Document Upload Review Page"
    And I click continue on "Scheduled_Scheduled Document Upload Review Page"
    #Then I am presented with the "Scheduled_Who Is The Declarant Page"
    #When I select radio button "I am a private individual importer" on "Scheduled_Who Is The Declarant Page"
    #And I click continue on "Scheduled_Who Is The Declarant Page"
    Then I am presented with the "Scheduled_Claimant Details Page"
    #When I select radio button "yes" on "Scheduled_Claimant Details Page"
    And I click continue on "Scheduled_Claimant Details Page"
    Then I am presented with the "Scheduled_Claim Northern Ireland Page"
    And I select radio button "yes" on "Scheduled_Claim Northern Ireland Page"
    And I click continue on "Scheduled_Claim Northern Ireland Page"
    Then I am presented with the "Scheduled_Choose Basis For Claim Page"
    When I select radio button "Outward processing relief" on "Scheduled_Choose Basis For Claim Page"
    And I click continue on "Scheduled_Choose Basis For Claim Page"
    Then I am presented with the "Scheduled_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Scheduled_Enter Commodity Details Page"
    And I click continue on "Scheduled_Enter Commodity Details Page"
    Then I am presented with the "Scheduled_Select Duties Select Duty Types Page"
    When I select "uk-duty,eu-duty,beer,wine,made-wine,miscellaneous-road-fuels,tobacco,climate-change-levy" on "Scheduled_Select Duties Select Duty Types Page"
    And I click continue on "Scheduled_Select Duties Select Duty Types Page"
    Then I am presented with the "Scheduled_Select Duties Uk Duty Page"
    When I select "A00,B00" on "Scheduled_Select Duties Uk Duty Page"
    And I click continue on "Scheduled_Select Duties Uk Duty Page"
    Then I am presented with the "Scheduled_Select Duties Eu Duty Page"
    When I select "A50,B05" on "Scheduled_Select Duties Eu Duty Page"
    And I click continue on "Scheduled_Select Duties Eu Duty Page"
    Then I am presented with the "Scheduled_Select Duties Beer Page"
    When I select "407,447" on "Scheduled_Select Duties Beer Page"
    And I click continue on "Scheduled_Select Duties Beer Page"
    Then I am presented with the "Scheduled_Select Duties Wine Page"
    When I select "411,415" on "Scheduled_Select Duties Wine Page"
    And I click continue on "Scheduled_Select Duties Wine Page"
    Then I am presented with the "Scheduled_Select Duties Made Wine Page"
    When I select "421,429" on "Scheduled_Select Duties Made Wine Page"
    And I click continue on "Scheduled_Select Duties Made Wine Page"
    Then I am presented with the "Scheduled_Select Duties Miscellaneous Road Fuels Page"
    When I select "591,592" on "Scheduled_Select Duties Miscellaneous Road Fuels Page"
    And I click continue on "Scheduled_Select Duties Miscellaneous Road Fuels Page"
    Then I am presented with the "Scheduled_Select Duties Tobacco Page"
    When I select "611,633" on "Scheduled_Select Duties Tobacco Page"
    And I click continue on "Scheduled_Select Duties Tobacco Page"
    Then I am presented with the "Scheduled_Select Duties Climate Change Levy Page"
    When I select "99A,99D" on "Scheduled_Select Duties Climate Change Levy Page"
    And I click continue on "Scheduled_Select Duties Climate Change Levy Page"
    Then I am presented with the "Scheduled_Select Duties DutyType Duty Page" "UK Duty A00"
    When I enter "10,5" on "Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "Scheduled_Select Duties DutyType Duty Page" "UK Duty B00"
    When I enter "10,5" on "Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "Scheduled_Select Duties DutyType Duty Page" "EU Duty A50"
    When I enter "10,5" on "Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "Scheduled_Select Duties DutyType Duty Page" "EU Duty B05"
    When I enter "10,5" on "Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "Scheduled_Select Duties DutyType Duty Page" "Beer 407"
    When I enter "10,5" on "Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "Scheduled_Select Duties DutyType Duty Page" "Beer 447"
    When I enter "10,5" on "Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "Scheduled_Select Duties DutyType Duty Page" "Wine 411"
    When I enter "10,5" on "Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "Scheduled_Select Duties DutyType Duty Page" "Wine 415"
    When I enter "10,5" on "Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "Scheduled_Select Duties DutyType Duty Page" "Made-wine 421"
    When I enter "10,5" on "Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "Scheduled_Select Duties DutyType Duty Page" "Made-wine 429"
    When I enter "10,5" on "Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "Scheduled_Select Duties DutyType Duty Page" "Miscellaneous road fuels 591"
    When I enter "10,5" on "Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "Scheduled_Select Duties DutyType Duty Page" "Miscellaneous road fuels 592"
    When I enter "10,5" on "Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "Scheduled_Select Duties DutyType Duty Page" "Tobacco products 611"
    When I enter "10,5" on "Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "Scheduled_Select Duties DutyType Duty Page" "Tobacco products 633"
    When I enter "10,5" on "Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "Scheduled_Select Duties DutyType Duty Page" "Climate Change Levy 99A"
    When I enter "10,5" on "Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "Scheduled_Select Duties DutyType Duty Page" "Climate Change Levy 99D"
    When I enter "10,5" on "Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "Scheduled_Check Claim Page"
    When I select radio button "Yes" on "Scheduled_Check Claim Page"
    And I click continue on "Scheduled_Check Claim Page"
    Then I am presented with the "Scheduled_Check These Bank Details Are Correct Page"
    And I click continue on "Scheduled_Check These Bank Details Are Correct Page"
    Then I am presented with the "Scheduled_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "image.jpg" file on "Scheduled_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Scheduled_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Scheduled_Supporting Evidence Scan Progress Page"
    Then I am presented with the "Scheduled_Supporting Evidence Select Supporting Evidence Type Page"
    When I select radio button "Commercial invoice" on "Scheduled_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Scheduled_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Scheduled_Supporting Evidence Check Your Answers Page"
    When I select radio button "No" on "Scheduled_Supporting Evidence Check Your Answers Page"
    And I click continue on "Scheduled_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Scheduled_Check Answers Accept Send Page"
    And I click continue on "Scheduled_Check Answers Accept Send Page"
    Then I am presented with the "Scheduled_Claim Submitted Page"
