@C285 @Scheduled
Feature: C285 Scheduled

  Background:
    Given the "Internal Upload Documents" feature is "disabled"

  @test @a11y @ZAP
  Scenario: happy path - check importer/declarant eori pages
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page"
    When I select radio button "schedule" on "C285_Choose How Many Mrns Page"
    And I click continue on "C285_Choose How Many Mrns Page"
    Then I am presented with the "C285_Scheduled_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA2" on "C285_Scheduled_Enter Movement Reference Number Page"
    And I click continue on "C285_Scheduled_Enter Movement Reference Number Page"
    Then I am presented with the "C285_Scheduled_Enter Importer Eori Page"
    When I enter "GB000000000000002" on "C285_Scheduled_Enter Importer Eori Page"
    And I click continue on "C285_Scheduled_Enter Importer Eori Page"
    Then I am presented with the "C285_Scheduled_Enter Declarant Eori Page"
    When I enter "GB000000000000002" on "C285_Scheduled_Enter Declarant Eori Page"
    And I click continue on "C285_Scheduled_Enter Declarant Eori Page"
    Then I am presented with the "C285_Scheduled_Check Declaration Details Page"
    And I select radio button "yes" on "C285_Scheduled_Check Declaration Details Page"
    And I click continue on "C285_Scheduled_Check Declaration Details Page"
    Then I am presented with the "UDF_Choose File Page"
    When I upload a 1 "image.jpg" file on "UDF_Choose File Page"
    And I click continue if I'm on "UDF_Choose File Page"
#    Then I am presented with the "UDF_Summary Page"
#    And I click continue on "UDF_Summary Page"
    Then I am presented with the "C285_Scheduled_Claimant Details Page"
    And I click continue on "C285_Scheduled_Claimant Details Page"
    Then I am presented with the "C285_Scheduled_Claim Northern Ireland Page"
    And I select radio button "yes" on "C285_Scheduled_Claim Northern Ireland Page"
    And I click continue on "C285_Scheduled_Claim Northern Ireland Page"
    Then I am presented with the "C285_Scheduled_Choose Basis For Claim Page"
    When I select radio button "Outward processing relief" on "C285_Scheduled_Choose Basis For Claim Page"
    And I click continue on "C285_Scheduled_Choose Basis For Claim Page"
    Then I am presented with the "C285_Scheduled_Enter Additional Details Page"
    When I enter "under 500 characters" on "C285_Scheduled_Enter Additional Details Page"
    And I click continue on "C285_Scheduled_Enter Additional Details Page"
    Then I am presented with the "C285_Scheduled_Select Duties Select Duty Types Page"
    When I select "uk-duty,eu-duty,beer,wine,made-wine,miscellaneous-road-fuels,tobacco,climate-change-levy" on "C285_Scheduled_Select Duties Select Duty Types Page"
    And I click continue on "C285_Scheduled_Select Duties Select Duty Types Page"
    Then I am presented with the "C285_Scheduled_Select Duties Uk Duty Page"
    When I select "A00,B00" on "C285_Scheduled_Select Duties Uk Duty Page"
    And I click continue on "C285_Scheduled_Select Duties Uk Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties Eu Duty Page"
    When I select "A50,B05" on "C285_Scheduled_Select Duties Eu Duty Page"
    And I click continue on "C285_Scheduled_Select Duties Eu Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties Beer Page"
    When I select "407,447" on "C285_Scheduled_Select Duties Beer Page"
    And I click continue on "C285_Scheduled_Select Duties Beer Page"
    Then I am presented with the "C285_Scheduled_Select Duties Wine Page"
    When I select "411,415" on "C285_Scheduled_Select Duties Wine Page"
    And I click continue on "C285_Scheduled_Select Duties Wine Page"
    Then I am presented with the "C285_Scheduled_Select Duties Made Wine Page"
    When I select "421,429" on "C285_Scheduled_Select Duties Made Wine Page"
    And I click continue on "C285_Scheduled_Select Duties Made Wine Page"
    Then I am presented with the "C285_Scheduled_Select Duties Miscellaneous Road Fuels Page"
    When I select "591,592" on "C285_Scheduled_Select Duties Miscellaneous Road Fuels Page"
    And I click continue on "C285_Scheduled_Select Duties Miscellaneous Road Fuels Page"
    Then I am presented with the "C285_Scheduled_Select Duties Tobacco Page"
    When I select "611,633" on "C285_Scheduled_Select Duties Tobacco Page"
    And I click continue on "C285_Scheduled_Select Duties Tobacco Page"
    Then I am presented with the "C285_Scheduled_Select Duties Climate Change Levy Page"
    When I select "99A,99D" on "C285_Scheduled_Select Duties Climate Change Levy Page"
    And I click continue on "C285_Scheduled_Select Duties Climate Change Levy Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "UK Duty A00"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "UK Duty B00"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "EU Duty A50"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "EU Duty B05"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Beer 407"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Beer 447"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Wine 411"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Wine 415"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Made-wine 421"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Made-wine 429"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Miscellaneous road fuels 591"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Miscellaneous road fuels 592"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Tobacco products 611"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Tobacco products 633"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Climate Change Levy 99A"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Climate Change Levy 99D"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Check Claim Page"
    When I select radio button "Yes" on "C285_Scheduled_Check Claim Page"
    And I click continue on "C285_Scheduled_Check Claim Page"
    Then I am presented with the "C285_Scheduled_Check These Bank Details Are Correct Page"
    And I click continue on "C285_Scheduled_Check These Bank Details Are Correct Page"
    Then I am presented with the "C285_Scheduled_Supporting Evidence Select Supporting Evidence Type Page"
    When I select radio button "Commercial invoice" on "C285_Scheduled_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "C285_Scheduled_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "UCDF_Choose File Other Page"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    Then I am presented with the "C285_Scheduled_Check Answers Accept Send Page"
    And I click continue on "C285_Scheduled_Check Answers Accept Send Page"
    Then I am presented with the "C285_Scheduled_Claim Submitted Page"

  @test
  Scenario: happy path - don't check importer/declarant eori pages
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page"
    When I select radio button "schedule" on "C285_Choose How Many Mrns Page"
    And I click continue on "C285_Choose How Many Mrns Page"
    Then I am presented with the "C285_Scheduled_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "C285_Scheduled_Enter Movement Reference Number Page"
    And I click continue on "C285_Scheduled_Enter Movement Reference Number Page"
    Then I am presented with the "C285_Scheduled_Check Declaration Details Page"
    And I select radio button "yes" on "C285_Scheduled_Check Declaration Details Page"
    And I click continue on "C285_Scheduled_Check Declaration Details Page"
    Then I am presented with the "UDF_Choose File Page"
    When I upload a 1 "image.jpg" file on "UDF_Choose File Page"
    And I click continue if I'm on "UDF_Choose File Page"
    Then I am presented with the "C285_Scheduled_Claimant Details Page"
    And I click continue on "C285_Scheduled_Claimant Details Page"
    Then I am presented with the "C285_Scheduled_Claim Northern Ireland Page"
    And I select radio button "yes" on "C285_Scheduled_Claim Northern Ireland Page"
    And I click continue on "C285_Scheduled_Claim Northern Ireland Page"
    Then I am presented with the "C285_Scheduled_Choose Basis For Claim Page"
    When I select radio button "Outward processing relief" on "C285_Scheduled_Choose Basis For Claim Page"
    And I click continue on "C285_Scheduled_Choose Basis For Claim Page"
    Then I am presented with the "C285_Scheduled_Enter Additional Details Page"
    When I enter "under 500 characters" on "C285_Scheduled_Enter Additional Details Page"
    And I click continue on "C285_Scheduled_Enter Additional Details Page"
    Then I am presented with the "C285_Scheduled_Select Duties Select Duty Types Page"
    When I select "uk-duty,eu-duty,beer,wine,made-wine,miscellaneous-road-fuels,tobacco,climate-change-levy" on "C285_Scheduled_Select Duties Select Duty Types Page"
    And I click continue on "C285_Scheduled_Select Duties Select Duty Types Page"
    Then I am presented with the "C285_Scheduled_Select Duties Uk Duty Page"
    When I select "A00,B00" on "C285_Scheduled_Select Duties Uk Duty Page"
    And I click continue on "C285_Scheduled_Select Duties Uk Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties Eu Duty Page"
    When I select "A50,B05" on "C285_Scheduled_Select Duties Eu Duty Page"
    And I click continue on "C285_Scheduled_Select Duties Eu Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties Beer Page"
    When I select "407,447" on "C285_Scheduled_Select Duties Beer Page"
    And I click continue on "C285_Scheduled_Select Duties Beer Page"
    Then I am presented with the "C285_Scheduled_Select Duties Wine Page"
    When I select "411,415" on "C285_Scheduled_Select Duties Wine Page"
    And I click continue on "C285_Scheduled_Select Duties Wine Page"
    Then I am presented with the "C285_Scheduled_Select Duties Made Wine Page"
    When I select "421,429" on "C285_Scheduled_Select Duties Made Wine Page"
    And I click continue on "C285_Scheduled_Select Duties Made Wine Page"
    Then I am presented with the "C285_Scheduled_Select Duties Miscellaneous Road Fuels Page"
    When I select "591,592" on "C285_Scheduled_Select Duties Miscellaneous Road Fuels Page"
    And I click continue on "C285_Scheduled_Select Duties Miscellaneous Road Fuels Page"
    Then I am presented with the "C285_Scheduled_Select Duties Tobacco Page"
    When I select "611,633" on "C285_Scheduled_Select Duties Tobacco Page"
    And I click continue on "C285_Scheduled_Select Duties Tobacco Page"
    Then I am presented with the "C285_Scheduled_Select Duties Climate Change Levy Page"
    When I select "99A,99D" on "C285_Scheduled_Select Duties Climate Change Levy Page"
    And I click continue on "C285_Scheduled_Select Duties Climate Change Levy Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "UK Duty A00"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "UK Duty B00"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "EU Duty A50"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "EU Duty B05"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Beer 407"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Beer 447"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Wine 411"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Wine 415"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Made-wine 421"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Made-wine 429"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Miscellaneous road fuels 591"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Miscellaneous road fuels 592"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Tobacco products 611"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Tobacco products 633"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Climate Change Levy 99A"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page" "Climate Change Levy 99D"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "C285_Scheduled_Check Claim Page"
    When I select radio button "Yes" on "C285_Scheduled_Check Claim Page"
    And I click continue on "C285_Scheduled_Check Claim Page"
    Then I am presented with the "C285_Scheduled_Check These Bank Details Are Correct Page"
    And I click continue on "C285_Scheduled_Check These Bank Details Are Correct Page"
    Then I am presented with the "C285_Scheduled_Supporting Evidence Select Supporting Evidence Type Page"
    When I select radio button "Commercial invoice" on "C285_Scheduled_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "C285_Scheduled_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "UCDF_Choose File Other Page"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    Then I am presented with the "C285_Scheduled_Check Answers Accept Send Page"
    And I click continue on "C285_Scheduled_Check Answers Accept Send Page"
    Then I am presented with the "C285_Scheduled_Claim Submitted Page"

  @test
  Scenario: error scenario - wrong mrn
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page"
    When I select radio button "schedule" on "C285_Choose How Many Mrns Page"
    And I click continue on "C285_Choose How Many Mrns Page"
    Then I am presented with the "C285_Scheduled_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "C285_Scheduled_Enter Movement Reference Number Page"
    And I click continue on "C285_Scheduled_Enter Movement Reference Number Page"
    Then I am presented with the "C285_Scheduled_Check Declaration Details Page"
    And I select radio button "no" on "C285_Scheduled_Check Declaration Details Page"
    And I click continue on "C285_Multiple_Check Declaration Details Page"
    Then I am presented with the "C285_Scheduled_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "C285_Scheduled_Enter Movement Reference Number Page"
    And I click continue on "C285_Scheduled_Enter Movement Reference Number Page"
    Then I am presented with the "C285_Scheduled_Check Declaration Details Page"
    And I select radio button "yes" on "C285_Scheduled_Check Declaration Details Page"
    And I click continue on "C285_Scheduled_Check Declaration Details Page"

  @testFail
  Scenario: error scenario - test file upload size and format fail pages
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page"
    When I select radio button "schedule" on "C285_Choose How Many Mrns Page"
    And I click continue on "C285_Choose How Many Mrns Page"
    Then I am presented with the "C285_Scheduled_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "C285_Scheduled_Enter Movement Reference Number Page"
    And I click continue on "C285_Scheduled_Enter Movement Reference Number Page"
    Then I am presented with the "C285_Scheduled_Check Declaration Details Page"
    And I select radio button "yes" on "C285_Scheduled_Check Declaration Details Page"
    And I click continue on "C285_Scheduled_Check Declaration Details Page"
    Then I am presented with the "UDF_Choose File Page"
    # I upload a file that is too big
    When I upload a 1 "image-big.jpg" file on "UDF_Choose File Page"
    And I click continue if I'm on "UDF_Choose File Page"
    Then I am presented with the "UDF_Size Fail Page"
