Feature: MRN file upload (bulk enabled, entry disabled)

  Background:
    Given the "Bulk Claim" feature is "enabled"
    Given the "Entry Number" feature is "disabled"
    Given the "Northern Ireland" feature is "disabled"

  @test
  Scenario: happy path (mrn) - upload 3 files
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Choose How Many Mrns Page"
    When I select radio button "individual" on "Choose How Many Mrns Page"
    And I click continue on "Choose How Many Mrns Page"
    Then I am presented with the "Single_Enter Movement Reference Number Page" and content "bulk-enabled,entry-disabled"
    When I enter "10AAAAAAAAAAAAAAA1" on "Single_Enter Movement Reference Number Page"
    And I click continue on "Single_Enter Movement Reference Number Page"
    Then I am presented with the "Single_Check Declaration Details Page" and content "10AAAAAAAAAAAAAAA1"
    And I select radio button "yes" on "Single_Check Declaration Details Page"
    And I click continue on "Single_Check Declaration Details Page"
    Then I am presented with the "Single_Who Is The Declarant Page"
    When I select radio button "I am a private individual importer" on "Single_Who Is The Declarant Page"
    And I click continue on "Single_Who Is The Declarant Page"
    Then I am presented with the "Single_Claimant Details Check Page"
    When I select radio button "yes" on "Single_Claimant Details Check Page"
    And I click continue on "Single_Claimant Details Check Page"
    Then I am presented with the "Single_Choose Basis For Claim Page"
    When I select radio button "Duty Suspension" on "Single_Choose Basis For Claim Page"
    And I click continue on "Single_Choose Basis For Claim Page"
    Then I am presented with the "Single_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Single_Enter Commodity Details Page"
    And I click continue on "Single_Enter Commodity Details Page"
    Then I am presented with the "Single_Select Duties Page"
    When I select "A80,A95,A90,A85" on "Single_Select Duties Page"
    And I click continue on "Single_Select Duties Page"
    Then I am presented with the "Single_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty" and content "£218.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Enter Claim Page" "A95 - Provisional Countervailing Duty" and content "£211.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Enter Claim Page" "A90 - Definitive Countervailing Duty" and content "£228.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty" and content "£171.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Check Claim Page"
    And I select radio button "yes" on "Single_Check Claim Page"
    When I click continue on "Single_Check Claim Page"
    Then I am presented with the "Single_Check These Bank Details Are Correct Page"
    When I click continue on "Single_Check These Bank Details Are Correct Page"
    # upload file 1
    Then I am presented with the "Single_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Single_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Single_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Single_Supporting Evidence Scan Progress Page"
    Then I am presented with the "Single_Supporting Evidence Select Supporting Evidence Type Page"
    When I select radio button "Commercial invoice" on "Single_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Single_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Single_Supporting Evidence Check Your Answers Page" and content "1 file"
    # upload file 2
    When I select radio button "Yes" on "Single_Supporting Evidence Check Your Answers Page"
    And I click continue on "Single_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Single_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Single_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Single_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Single_Supporting Evidence Scan Progress Page"
    Then I am presented with the "Single_Supporting Evidence Select Supporting Evidence Type Page"
    When I select radio button "Import and export declaration" on "Single_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Single_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Single_Supporting Evidence Check Your Answers Page" and content "2 files"
    # upload file 3
    When I select radio button "Yes" on "Single_Supporting Evidence Check Your Answers Page"
    And I click continue on "Single_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Single_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Single_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Single_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Single_Supporting Evidence Scan Progress Page"
    Then I am presented with the "Single_Supporting Evidence Select Supporting Evidence Type Page"
    When I select radio button "Packing list" on "Single_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Single_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Single_Supporting Evidence Check Your Answers Page" and content "3 files"
    # continue journey
    When I select radio button "No" on "Single_Supporting Evidence Check Your Answers Page"
    And I click continue on "Single_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Single_Check Answers Accept Send Page"
    And I click continue on "Single_Check Answers Accept Send Page"
    Then I am presented with the "Single_Claim Submitted Page" and content "£40.00"
