@Regression @Bulk

Feature: Bulk NI (bulk enabled, entry disabled)

  Background:
    Given the "Bulk Claim" feature is "enabled"
    Given the "Entry Number" feature is "disabled"
    Given the "Northern Ireland" feature is "enabled"

  @test
  Scenario: test temp NI pages - NI enabled
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Choose How Many Mrns Page"
    When I select radio button "bulk" on "Choose How Many Mrns Page"
    And I click continue on "Choose How Many Mrns Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number Page"
    And I click continue on "Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "Multiple_Check Declaration Details Page"
    And I select radio button "yes" on "Multiple_Check Declaration Details Page"
    And I click continue on "Multiple_Check Declaration Details Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number 2 Page"
    When I enter "20AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "Multiple_Check Movement Reference Numbers Page"
    When I select radio button "No" on "Multiple_Check Movement Reference Numbers Page"
    And I click continue on "Multiple_Check Movement Reference Numbers Page"
    Then I am presented with the "Multiple_Who Is The Declarant Page"
    When I select radio button "I am a private individual importer" on "Multiple_Who Is The Declarant Page"
    And I click continue on "Multiple_Who Is The Declarant Page"
    Then I am presented with the "Multiple_Claimant Details Check Page"
    And I select radio button "yes" on "Multiple_Claimant Details Check Page"
    And I click continue on "Multiple_Claimant Details Check Page"
    Then I am presented with the "Multiple_Claim Northern Ireland Page"
    And I select radio button "yes" on "Single_Claim Northern Ireland Page"
    And I click continue on "Multiple_Claim Northern Ireland Page"
    Then I am presented with the "Multiple_Choose Basis For Claim Page"
    When I select radio button "Incorrect Additional Information code (excluding NIAID) - Northern Ireland claims only" on "Multiple_Choose Basis For Claim Page"
    And I click continue on "Multiple_Choose Basis For Claim Page"
    Then I am presented with the "Multiple_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Multiple_Enter Commodity Details Page"
    And I click continue on "Multiple_Enter Commodity Details Page"
    Then I am presented with the "Multiple_Select Duties 1 Page"
    When I select "A80,A95" on "Multiple_Select Duties 1 Page"
    And I click continue on "Multiple_Select Duties 1 Page"
    Then I am presented with the "Multiple_Select Duties 1 Duty Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "Multiple_Select Duties 1 Duty Page"
    And I click continue on "Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "Multiple_Select Duties 1 Duty Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "Multiple_Select Duties 1 Duty Page"
    And I click continue on "Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "Multiple_Select Duties 2 Page"
    When I select "A90,A85" on "Multiple_Select Duties 2 Page"
    And I click continue on "Multiple_Select Duties 2 Page"
    Then I am presented with the "Multiple_Select Duties 2 Duty Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "Multiple_Select Duties 2 Duty Page"
    And I click continue on "Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "Multiple_Select Duties 2 Duty Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "Multiple_Select Duties 2 Duty Page"
    And I click continue on "Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "Multiple_Check Claim Page"
    And I select radio button "yes" on "Multiple_Check Claim Page"
    When I click continue on "Multiple_Check Claim Page"
    Then I am presented with the "Multiple_Check These Bank Details Are Correct Page"
    When I click continue on "Multiple_Check These Bank Details Are Correct Page"
    Then I am presented with the "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Multiple_Supporting Evidence Upload Progress Page"
    When I select radio button "Commercial invoice" on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Multiple_Supporting Evidence Check Your Answers Page"
    When I select radio button "No" on "Multiple_Supporting Evidence Check Your Answers Page"
    And I click continue on "Multiple_Supporting Evidence Check Your Answers Page"
#    Then I am presented with the "Multiple_Check Answers Accept Send Page"
#    And I click continue on "Multiple_Check Answers Accept Send Page"
#    Then I am presented with the "Multiple_Claim Submitted Page" and content "£40.00"
