@Regression @Scheduled

Feature: Scheduled (bulk enabled, entry disabled)

  Background:
    Given the "Bulk Claim" feature is "enabled"
    Given the "Entry Number" feature is "disabled"
    Given the "Northern Ireland" feature is "disabled"

  @test @a11y @ZAP
  Scenario: test temp pages
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Number Of Claims Page"
    When I select radio button "schedule" on "Select Number Of Claims Page"
    And I click continue on "Select Number Of Claims Page"
    Then I am presented with the "Scheduled_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "Scheduled_Enter Movement Reference Number Page"
    And I click continue on "Scheduled_Enter Movement Reference Number Page"
    Then I am presented with the "Scheduled_Check Declaration Details Page" and content "10AAAAAAAAAAAAAAA1"
    And I select radio button "yes" on "Scheduled_Check Declaration Details Page"
    And I click continue on "Scheduled_Check Declaration Details Page"
    Then I am presented with the "Scheduled_Scheduled Document Upload Upload Page"
    When I upload a "image.jpg" file on "Scheduled_Scheduled Document Upload Upload Page"
    And I click continue on "Scheduled_Scheduled Document Upload Upload Page"
    And I click continue if I'm on "Scheduled_Scheduled Document Upload Progress Page"
    Then I am presented with the "Scheduled_Scheduled Document Upload Review Page"
    And I click continue on "Scheduled_Scheduled Document Upload Review Page"
    Then I am presented with the "Scheduled_Who Is The Declarant Page"
    When I select radio button "0" on "Scheduled_Who Is The Declarant Page"
    And I click continue on "Scheduled_Who Is The Declarant Page"
    Then I am presented with the "Scheduled_Claimant Details Page"
    When I select radio button "yes" on "Scheduled_Claimant Details Page"
    And I click continue on "Scheduled_Claimant Details Page"
    Then I am presented with the "Scheduled_Choose Basis For Claim Page"
    When I select radio button "OPR" on "Scheduled_Choose Basis For Claim Page"
    And I click continue on "Scheduled_Choose Basis For Claim Page"
    Then I am presented with the "Scheduled_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Scheduled_Enter Commodity Details Page"
    And I click continue on "Scheduled_Enter Commodity Details Page"
    Then I am presented with the "Scheduled_Select Duties Select Duty Types Page"
    When I select "uk-duty,eu-duty,beer,wine,made-wine,miscellaneous-road-fuels,tobacco,climate-change-levy" on "Scheduled_Select Duties Select Duty Types Page"
    And I click continue on "Scheduled_Select Duties Select Duty Types Page"
    When I select "A00,B00" on "Scheduled_SelectDuties Uk Duty Page"
    And I click continue on "Scheduled_SelectDuties Uk Duty Page"
    When I select "A50,B05" on "Scheduled_SelectDuties Eu Duty Page"
    And I click continue on "Scheduled_SelectDuties Eu Duty Page"
    When I select "407,447" on "Scheduled_Select Duties Beer Page"
    And I click continue on "Scheduled_Select Duties Beer Page"
    When I select "411,415" on "Scheduled_Select Duties Wine Page"
    And I click continue on "Scheduled_Select Duties Wine Page"
    When I select "421,429" on "Scheduled_Select Duties Made Wine Page"
    And I click continue on "Scheduled_Select Duties Made Wine Page"
    When I select "591,592" on "Scheduled_Select Duties Miscellaneous Road Fuels Page"
    And I click continue on "Scheduled_Select Duties Miscellaneous Road Fuels Page"
    When I select "611,633" on "Scheduled_Select Duties Tobacco Page"
    And I click continue on "Scheduled_Select Duties Tobacco Page"
    When I select "99A,99D" on "Scheduled_Select Duties Climate Change Levy Page"
    And I click continue on "Scheduled_Select Duties Climate Change Levy Page"

  @test
  Scenario: test temp pages - wrong mrn
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Number Of Claims Page"
    When I select radio button "schedule" on "Select Number Of Claims Page"
    And I click continue on "Select Number Of Claims Page"
    Then I am presented with the "Scheduled_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "Scheduled_Enter Movement Reference Number Page"
    And I click continue on "Scheduled_Enter Movement Reference Number Page"
    Then I am presented with the "Scheduled_Check Declaration Details Page" and content "10AAAAAAAAAAAAAAA1"
    And I select radio button "no" on "Scheduled_Check Declaration Details Page"
    And I click continue on "Multiple_Check Declaration Details Page"
    Then I am presented with the "Scheduled_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "Scheduled_Enter Movement Reference Number Page"
    And I click continue on "Scheduled_Enter Movement Reference Number Page"
    Then I am presented with the "Scheduled_Check Declaration Details Page" and content "10AAAAAAAAAAAAAAA1"
    And I select radio button "yes" on "Scheduled_Check Declaration Details Page"
    And I click continue on "Scheduled_Check Declaration Details Page"

  @test
  Scenario: test temp pages - test file upload size and format fail pages
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Number Of Claims Page"
    When I select radio button "schedule" on "Select Number Of Claims Page"
    And I click continue on "Select Number Of Claims Page"
    Then I am presented with the "Scheduled_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "Scheduled_Enter Movement Reference Number Page"
    And I click continue on "Scheduled_Enter Movement Reference Number Page"
    Then I am presented with the "Scheduled_Check Declaration Details Page" and content "10AAAAAAAAAAAAAAA1"
    And I select radio button "yes" on "Scheduled_Check Declaration Details Page"
    And I click continue on "Scheduled_Check Declaration Details Page"
    Then I am presented with the "Scheduled_Scheduled Document Upload Upload Page"
    # I upload a file that is too big
    When I upload a "image-big.jpg" file on "Scheduled_Scheduled Document Upload Upload Page"
    And I click continue on "Scheduled_Scheduled Document Upload Upload Page"
    And I click continue if I'm on "Scheduled_Scheduled Document Upload Progress Page"
    Then I am presented with the "Scheduled_Scheduled Document Upload Size Fail Page"