@Regression @Bulk

Feature: Bulk NI (bulk enabled, entry disabled)

  Background:
    Given the "Bulk Claim" feature is "enabled"
    Given the "Entry Number" feature is "disabled"
    Given the "Northern Ireland" feature is "enabled"

  @test
  Scenario: test temp NI pages - NI enabled
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000005" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000005,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Choose How Many Mrns Page"
    When I select radio button "bulk" on "Choose How Many Mrns Page"
    And I click continue on "Choose How Many Mrns Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Page"
    When I enter "50AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number Page"
    And I click continue on "Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "Multiple_Check Declaration Details Page" and content "50AAAAAAAAAAAAAAA1"
    And I select radio button "yes" on "Multiple_Check Declaration Details Page"
    And I click continue on "Multiple_Check Declaration Details Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Second Page"
    And I click continue on "Multiple_Enter Movement Reference Number Second Page"
    Then I am presented with the "Multiple_Who Is The Declarant Page"
    When I select radio button "I am a private individual importer" on "Multiple_Who Is The Declarant Page"
    And I click continue on "Multiple_Who Is The Declarant Page"
    Then I am presented with the "Multiple_Claimant Details Check Page"
    And I select radio button "yes" on "Multiple_Claimant Details Check Page"
    And I click continue on "Multiple_Claimant Details Check Page"
    Then I am presented with the "Multiple_Claim Northern Ireland Page"
    And I select radio button "yes" on "Mrn_Claim Northern Ireland Page"
    And I click continue on "Multiple_Claim Northern Ireland Page"
    Then I am presented with the "Multiple_Choose Basis For Claim Page" and content "50AAAAAAAAAAAAAAA1"
    When I select radio button "Incorrect excise value - Northern Ireland claims only" on "Multiple_Choose Basis For Claim Page"
    And I click continue on "Multiple_Choose Basis For Claim Page"
    Then I am presented with the "Multiple_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Multiple_Enter Commodity Details Page"
    And I click continue on "Multiple_Enter Commodity Details Page"
    Then I am presented with the "Mrn_Select Duties Page"
    When I select "421,623" on "Mrn_Select Duties Page"
    And I click continue on "Mrn_Select Duties Page"
    Then I am presented with the "Mrn_Enter Claim Page" "421 - Made-wine (sparkling), exceeding 8.5% vol. but not exceeding 15% vol." and content "£171.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "623 - Smoking tobacco – other" and content "£171.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Check Claim Page"
    And I select radio button "yes" on "Mrn_Check Claim Page"
    When I click continue on "Mrn_Check Claim Page"
    Then I am presented with the "Multiple_Check These Bank Details Are Correct Page"
    When I click continue on "Multiple_Check These Bank Details Are Correct Page"
    Then I am presented with the "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Multiple_Supporting Evidence Upload Progress Page"
    When I select radio button "Commercial invoice" on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Multiple_Supporting Evidence Check Your Answers Page"
    When I select radio button "No" on "Multiple_Supporting Evidence Check Your Answers Page"
    And I click continue on "Multiple_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Multiple_Check Answers Accept Send Page"
    And I click continue on "Multiple_Check Answers Accept Send Page"
    Then I am presented with the "Multiple_Claim Submitted Page" and content "£40.00"

