@Regression @Bulk

Feature: Bulk (bulk enabled, entry disabled)

  Background:
    Given the "Bulk Claim" feature is "enabled"
    Given the "Entry Number" feature is "disabled"
    Given the "Northern Ireland" feature is "disabled"

  @test @a11y @ZAP
  Scenario: test temp pages
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Number Of Claims Page"
    When I select radio button "bulk" on "Select Number Of Claims Page"
    And I click continue on "Select Number Of Claims Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number Page"
    And I click continue on "Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "Multiple_Check Declaration Details Page" and content "10AAAAAAAAAAAAAAA1"
    And I select radio button "yes" on "Multiple_Check Declaration Details Page"
    And I click continue on "Multiple_Check Declaration Details Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Second Page"
    And I click continue on "Multiple_Enter Movement Reference Number Second Page"
    Then I am presented with the "Multiple_Who Is The Declarant Page"
    When I select radio button "0" on "Multiple_Who Is The Declarant Page"
    And I click continue on "Multiple_Who Is The Declarant Page"
    Then I am presented with the "Multiple_Claimant Details Check Page"
    When I select radio button "yes" on "Multiple_Claimant Details Check Page"
    And I click continue on "Multiple_Claimant Details Check Page"
    Then I am presented with the "Multiple_Choose Basis For Claim Page"
    When I select radio button "OPR" on "Multiple_Choose Basis For Claim Page"
    And I click continue on "Multiple_Choose Basis For Claim Page"
    Then I am presented with the "Multiple_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Multiple_Enter Commodity Details Page"
    And I click continue on "Multiple_Enter Commodity Details Page"
    Then I am presented with the "Mrn_Select Duties Page"
    When I select "A80,A95,A90,A85" on "Mrn_Select Duties Page"
    And I click continue on "Mrn_Select Duties Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty" and content "£218.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A95 - Provisional Countervailing Duty" and content "£211.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A90 - Definitive Countervailing Duty" and content "£228.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty" and content "£171.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Check Claim Page"
    And I select radio button "yes" on "Mrn_Check Claim Page"
    When I click continue on "Mrn_Check Claim Page"
    Then I am presented with the "Multiple_Check These Bank Details Are Correct Page"
    When I click continue on "Multiple_Check These Bank Details Are Correct Page"
    Then I am presented with the "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Multiple_Supporting Evidence Upload Progress Page"
    When I select radio button "Commercial invoice" on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Multiple_Supporting Evidence Check Your Answers Page"
    When I select radio button "No" on "Multiple_Supporting Evidence Check Your Answers Page"
    And I click continue on "Multiple_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Multiple_Check Answers Accept Send Page"
    And I click continue on "Multiple_Check Answers Accept Send Page"
    Then I am presented with the "Multiple_Claim Submitted Page" and content "£40.00"

  @test
  Scenario: wrong mrn
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Number Of Claims Page"
    When I select radio button "bulk" on "Select Number Of Claims Page"
    And I click continue on "Select Number Of Claims Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number Page"
    And I click continue on "Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "Multiple_Check Declaration Details Page" and content "10AAAAAAAAAAAAAAA1"
    And I select radio button "no" on "Multiple_Check Declaration Details Page"
    And I click continue on "Multiple_Check Declaration Details Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number Page"
    And I click continue on "Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "Multiple_Check Declaration Details Page" and content "10AAAAAAAAAAAAAAA1"
    And I select radio button "yes" on "Multiple_Check Declaration Details Page"
    And I click continue on "Multiple_Check Declaration Details Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Second Page"
    And I click continue on "Multiple_Enter Movement Reference Number Second Page"
    Then I am presented with the "Multiple_Who Is The Declarant Page"

  @test @ALF
  Scenario: happy path (mrn) - confirm ALF data works in journey
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Number Of Claims Page"
    When I select radio button "bulk" on "Select Number Of Claims Page"
    And I click continue on "Select Number Of Claims Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Page" and content "bulk-enabled,entry-disabled"
    When I enter "10AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number Page"
    And I click continue on "Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "Multiple_Check Declaration Details Page" and content "10AAAAAAAAAAAAAAA1"
    And I select radio button "yes" on "Multiple_Check Declaration Details Page"
    And I click continue on "Multiple_Check Declaration Details Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Second Page"
    And I click continue on "Multiple_Enter Movement Reference Number Second Page"
    Then I am presented with the "Multiple_Who Is The Declarant Page"
    When I select radio button "0" on "Multiple_Who Is The Declarant Page"
    And I click continue on "Multiple_Who Is The Declarant Page"
    Then I am presented with the "Multiple_Claimant Details Check Page"
    When I select radio button "no" on "Multiple_Claimant Details Check Page"
    And I click continue on "Multiple_Claimant Details Check Page"
    Then I am presented with the "Multiple_Claimant Details Add Page" and content "missing details"
    When I select radio button "yes" on "Multiple_Claimant Details Add Page"
    And I click continue on "Multiple_Claimant Details Add Page"
    Then I am presented with the "Multiple_Claimant Details Enter Contact Details Page"
    And I enter "" on "Multiple_Claimant Details Enter Contact Details Page"
    And I click continue on "Multiple_Claimant Details Enter Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Multiple_Claimant Details Check Page" and content "10AAAAAAAAAAAAAAA1 - change details"
    When I select radio button "yes" on "Multiple_Claimant Details Check Page"
    And I click continue on "Multiple_Claimant Details Check Page"
    Then I am presented with the "Multiple_Choose Basis For Claim Page"
    When I select radio button "OPR" on "Multiple_Choose Basis For Claim Page"
    And I click continue on "Multiple_Choose Basis For Claim Page"
    Then I am presented with the "Multiple_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Multiple_Enter Commodity Details Page"
    And I click continue on "Multiple_Enter Commodity Details Page"
    Then I am presented with the "Mrn_Select Duties Page"
    When I select "A80,A95,A90,A85" on "Mrn_Select Duties Page"
    And I click continue on "Mrn_Select Duties Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty" and content "£218.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A95 - Provisional Countervailing Duty" and content "£211.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A90 - Definitive Countervailing Duty" and content "£228.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty" and content "£171.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Check Claim Page"
    And I select radio button "yes" on "Mrn_Check Claim Page"
    When I click continue on "Mrn_Check Claim Page"
    Then I am presented with the "Multiple_Check These Bank Details Are Correct Page"
    When I click continue on "Multiple_Check These Bank Details Are Correct Page"
    Then I am presented with the "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Multiple_Supporting Evidence Upload Progress Page"
    When I select radio button "Commercial invoice" on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Multiple_Supporting Evidence Check Your Answers Page"
    When I select radio button "No" on "Multiple_Supporting Evidence Check Your Answers Page"
    And I click continue on "Multiple_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Multiple_Check Answers Accept Send Page"
    And I click continue on "Multiple_Check Answers Accept Send Page"
    Then I am presented with the "Multiple_Claim Submitted Page" and content "£40.00"

  @testFail @ALF
  Scenario: test temp pages - confirm ALF data works in journey (no contact details)
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000006" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000006,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Number Of Claims Page"
    When I select radio button "bulk" on "Select Number Of Claims Page"
    And I click continue on "Select Number Of Claims Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA6" on "Multiple_Enter Movement Reference Number Page"
    And I click continue on "Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "Multiple_Check Declaration Details Page" and content "10AAAAAAAAAAAAAAA6"
    And I select radio button "yes" on "Multiple_Check Declaration Details Page"
    And I click continue on "Multiple_Check Declaration Details Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Second Page"
    And I click continue on "Multiple_Enter Movement Reference Number Second Page"
    Then I am presented with the "Multiple_Who Is The Declarant Page"
    When I select radio button "0" on "Multiple_Who Is The Declarant Page"
    And I click continue on "Multiple_Who Is The Declarant Page"
    Then I am presented with the "Multiple_Claimant Details Check Page" and content "10AAAAAAAAAAAAAAA6"
    When I select radio button "yes" on "Multiple_Claimant Details Check Page"
    And I click continue on "Multiple_Claimant Details Check Page"
    Then I am presented with the "Multiple_Claimant Details Enter Contact Details Page"
    And I enter "" on "Multiple_Claimant Details Enter Contact Details Page"
    And I click continue on "Multiple_Claimant Details Enter Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Multiple_Claimant Details Check Page" and content "10AAAAAAAAAAAAAAA6 - change details"
    When I select radio button "yes" on "Multiple_Claimant Details Check Page"
    And I click continue on "Multiple_Claimant Details Check Page"
    Then I am presented with the "Multiple_Choose Basis For Claim Page"
    When I select radio button "IP" on "Multiple_Choose Basis For Claim Page"
    And I click continue on "Multiple_Choose Basis For Claim Page"
    Then I am presented with the "Multiple_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Multiple_Enter Commodity Details Page"
    And I click continue on "Multiple_Enter Commodity Details Page"
    Then I am presented with the "Mrn_Select Duties Page"
    When I select "A80,A95,A90,A85" on "Mrn_Select Duties Page"
    And I click continue on "Mrn_Select Duties Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty" and content "£218.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A95 - Provisional Countervailing Duty" and content "£211.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A90 - Definitive Countervailing Duty" and content "£228.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty" and content "£171.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Check Claim Page"
    And I select radio button "yes" on "Mrn_Check Claim Page"
    When I click continue on "Mrn_Check Claim Page"
    Then I am presented with the "Multiple_Check These Bank Details Are Correct Page"
    When I click continue on "Multiple_Check These Bank Details Are Correct Page"
    Then I am presented with the "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Multiple_Supporting Evidence Upload Progress Page"
    When I select radio button "Commercial invoice" on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Multiple_Supporting Evidence Check Your Answers Page"
    When I click continue on "Multiple_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Multiple_Check Answers Accept Send Page"
    And I click continue on "Multiple_Check Answers Accept Send Page"
    Then I am presented with the "Multiple_Claim Submitted Page" and content "£40.00"
