@C285 @Multiple
Feature: C285 Multiple NI

  @test
  Scenario: happy path
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "bulk" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number Page v2"
    When I enter "10AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Multiple_Check Declaration Details Page v2"
    And I select radio button "yes" on "C285_Multiple_Check Declaration Details Page v2"
    And I click continue on "C285_Multiple_Check Declaration Details Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    When I enter "20AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    Then I am presented with the "C285_Multiple_Check Movement Reference Numbers Page v2"
    When I select radio button "No" on "C285_Multiple_Check Movement Reference Numbers Page v2"
    And I click continue on "C285_Multiple_Check Movement Reference Numbers Page v2"
    Then I am presented with the "C285_Multiple_Claimant Details Page v2"

  @test
  Scenario: happy path
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "bulk" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number Page v2"
    When I enter "10AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Multiple_Check Declaration Details Page v2"
    And I select radio button "yes" on "C285_Multiple_Check Declaration Details Page v2"
    And I click continue on "C285_Multiple_Check Declaration Details Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    When I enter "20AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    Then I am presented with the "C285_Multiple_Check Movement Reference Numbers Page v2"
    When I select radio button "No" on "C285_Multiple_Check Movement Reference Numbers Page v2"
    And I click continue on "C285_Multiple_Check Movement Reference Numbers Page v2"
    Then I am presented with the "C285_Multiple_Claimant Details Page v2"
    And I click continue on "C285_Multiple_Claimant Details Page v2"
    Then I am presented with the "C285_Multiple_Claim Northern Ireland Page v2"
    And I select radio button "yes" on "C285_Single_Claim Northern Ireland Page v2"
    And I click continue on "C285_Multiple_Claim Northern Ireland Page v2"
    Then I am presented with the "C285_Multiple_Choose Basis For Claim Page v2"
    When I select radio button "Incorrect additional information code (excluding NIAID)" on "C285_Multiple_Choose Basis For Claim Page v2"
    And I click continue on "C285_Multiple_Choose Basis For Claim Page v2"
    Then I am presented with the "C285_Multiple_Enter Additional Details Page v2"
    When I enter "under 500 characters" on "C285_Multiple_Enter Additional Details Page v2"
    And I click continue on "C285_Multiple_Enter Additional Details Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Page v2"
    When I select "A80,A95" on "C285_Multiple_Select Duties 1 Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Duty Page v2" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "C285_Multiple_Select Duties 1 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Duty Page v2" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "C285_Multiple_Select Duties 1 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Page v2"
    When I select "A90,A85" on "C285_Multiple_Select Duties 2 Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Duty Page v2" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "C285_Multiple_Select Duties 2 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Duty Page v2" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "C285_Multiple_Select Duties 2 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Duty Page v2"
    Then I am presented with the "C285_Multiple_Check Claim Page v2"
    And I select radio button "yes" on "C285_Multiple_Check Claim Page v2"
    When I click continue on "C285_Multiple_Check Claim Page v2"
    Then I am presented with the "C285_Multiple_Check These Bank Details Are Correct Page v2"
    When I click continue on "C285_Multiple_Check These Bank Details Are Correct Page v2"
    Then I am presented with the "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    When I select radio button "Commercial invoice" on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    And I click continue on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    Then I am presented with the "UCDF_Choose File Other Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    Then I am presented with the "C285_Multiple_Check Answers Accept Send Page v2"
    And I should see the following details
      | This is the basis behind the claim                      | Import date      | Contact details                                      | Importer email       | Contact address                                  | Name on the account | Importer telephone | Importer name    | Account number   | Declarant name     | Were your goods imported into Northern Ireland? | Importer address                                 | This is the reason for the claim | Declarant address                                 | Total   | Duties paid | Sort code      | First MRN          | Second MRN         | 20AAAAAAAAAAAAAAA1 | 10AAAAAAAAAAAAAAA1 | Uploaded                        |
      | Incorrect additional information code (excluding NIAID) | 12 February 2021 | Online Sales LTD,automation@gmail.com,+4420723934397 | automation@gmail.com | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | CDS E2E To E2E Bank | +4420723934397     | IT Solutions LTD | Ending with 5678 | Foxpro Central LTD | Yes                                             | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | under 500 characters             | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | £788.00 | £828.00     | Ending with 44 | 10AAAAAAAAAAAAAAA1 | 20AAAAAAAAAAAAAAA1 | £379.00            | £409.00            | document.pdf,Commercial invoice |
    And I click continue on "C285_Multiple_Check Answers Accept Send Page v2"
    Then I am presented with the "C285_Multiple_Claim Submitted Page v2"
