@C285 @Multiple
Feature: C285 Multiple

  @test @a11y @ZAP
  Scenario: happy path - check importer/declarant eori pages
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "bulk" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number Page v2"
    When I enter "10AAAAAAAAAAAAAAA2" on "C285_Multiple_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Multiple_Enter Importer Eori Page v2"
    When I enter "GB000000000000002" on "C285_Multiple_Enter Importer Eori Page v2"
    And I click continue on "C285_Multiple_Enter Importer Eori Page v2"
    Then I am presented with the "C285_Multiple_Enter Declarant Eori Page v2"
    When I enter "GB000000000000002" on "C285_Multiple_Enter Declarant Eori Page v2"
    And I click continue on "C285_Multiple_Enter Declarant Eori Page v2"
    Then I am presented with the "C285_Multiple_Check Declaration Details Page v2"
    And I select radio button "yes" on "C285_Multiple_Check Declaration Details Page v2"
    And I click continue on "C285_Multiple_Check Declaration Details Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    When I enter "20AAAAAAAAAAAAAAA2" on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    Then I am presented with the "C285_Multiple_Check Movement Reference Numbers Page v2"
    When I select radio button "No" on "C285_Multiple_Check Movement Reference Numbers Page v2"
    And I click continue on "C285_Multiple_Check Movement Reference Numbers Page v2"
    Then I am presented with the "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I enter "" on "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I click continue on "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "C285_Multiple_Claimant Details Page v2"
    And I click continue on "C285_Multiple_Claimant Details Page v2"
    Then I am presented with the "C285_Multiple_Choose Basis For Claim Page v2"
    When I select radio button "Outward processing relief" on "C285_Multiple_Choose Basis For Claim Page v2"
    And I click continue on "C285_Multiple_Choose Basis For Claim Page v2"
    Then I am presented with the "C285_Multiple_Enter Additional Details Page v2"
    When I enter "under 500 characters" on "C285_Multiple_Enter Additional Details Page v2"
    And I click continue on "C285_Multiple_Enter Additional Details Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Page v2"
    When I select "A80,A95" on "C285_Multiple_Select Duties 1 Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Duty Page v2" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "C285_Multiple_Select Duties 1 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Duty Page v2" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "C285_Multiple_Select Duties 1 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Page v2"
    When I select "A90,A85" on "C285_Multiple_Select Duties 2 Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Duty Page v2" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "C285_Multiple_Select Duties 2 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Duty Page v2" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "C285_Multiple_Select Duties 2 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Duty Page v2"
    Then I am presented with the "C285_Multiple_Check Claim Page v2"
    And I select radio button "yes" on "C285_Multiple_Check Claim Page v2"
    When I click continue on "C285_Multiple_Check Claim Page v2"
    Then I am presented with the "C285_Multiple_Choose Payee Type v2"
    And I select radio button "Importer" on "C285_Multiple_Choose Payee Type v2"
    When I click continue on "C285_Multiple_Choose Payee Type v2"
#    Then I am presented with the "C285_Multiple_Check These Bank Details Are Correct Page v2"
#    And I select radio button "yes" on "C285_Multiple_Check These Bank Details Are Correct Page v2"
#    When I click continue on "C285_Multiple_Check These Bank Details Are Correct Page v2"
    Then I am presented with the "C285_Multiple_Enter Bank Account Details Page v2"
    And I enter "" on "C285_Multiple_Enter Bank Account Details Page v2"
    When I click continue on "C285_Multiple_Enter Bank Account Details Page v2"
    Then I am presented with the "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    When I select radio button "Commercial invoice" on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    And I click continue on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    Then I am presented with the "UCDF_Choose File Other Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    Then I am presented with the "C285_Multiple_Check Answers Accept Send Page v2"
    And I should see the following details
      | Basis of claim | Import date      | Contact details             | Importer email       | Contact address                                   | Name on the account | Importer telephone | Importer name    | Account number   | Declarant name     | Importer address                                 | Additional claim details | Declarant address                                 | Total   |Method of payment | Duties paid | Sort code      | First MRN          | Second MRN         | Uploaded                        | 20AAAAAAAAAAAAAAA2 | 10AAAAAAAAAAAAAAA2 |
      | Outward processing relief          | 12 February 2021 | John Smith,john@smith.com,01234567890 | automation@gmail.com | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | Mr John Smith | +4420723934397     | IT Solutions LTD | 11001001 | Foxpro Central LTD | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | under 500 characters             | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | £788.00 | Immediate Payment| £828.00     | 123456 | 10AAAAAAAAAAAAAAA2 | 20AAAAAAAAAAAAAAA2 | document.pdf,Commercial invoice | £379.00            | £409.00            |
    And I click continue on "C285_Multiple_Check Answers Accept Send Page v2"
    Then I am presented with the "C285_Multiple_Claim Submitted Page v2"


  @test
  Scenario: happy path - with no bank details (user is both importer and declarant)
    #  60AAAAAAAAAAAAAAA1 => No bank details (user is both importer and declarant), - skips payee indicator page and navigates to /choose Bank account transfer,> /enter-bank-account-details page
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "bulk" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number Page v2"
    When I enter "60AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Multiple_Check Declaration Details Page v2"
    And I select radio button "yes" on "C285_Multiple_Check Declaration Details Page v2"
    And I click continue on "C285_Multiple_Check Declaration Details Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    When I enter "20AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    Then I am presented with the "C285_Multiple_Check Movement Reference Numbers Page v2"
    When I select radio button "No" on "C285_Multiple_Check Movement Reference Numbers Page v2"
    And I click continue on "C285_Multiple_Check Movement Reference Numbers Page v2"
    Then I am presented with the "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I enter "" on "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I click continue on "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "C285_Multiple_Claimant Details Page v2"
    And I click continue on "C285_Multiple_Claimant Details Page v2"
    Then I am presented with the "C285_Multiple_Choose Basis For Claim Page v2"
    When I select radio button "Outward processing relief" on "C285_Multiple_Choose Basis For Claim Page v2"
    And I click continue on "C285_Multiple_Choose Basis For Claim Page v2"
    Then I am presented with the "C285_Multiple_Enter Additional Details Page v2"
    When I enter "under 500 characters" on "C285_Multiple_Enter Additional Details Page v2"
    And I click continue on "C285_Multiple_Enter Additional Details Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Page v2"
    When I select "A80,A95" on "C285_Multiple_Select Duties 1 Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Duty Page v2" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "C285_Multiple_Select Duties 1 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Duty Page v2" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "C285_Multiple_Select Duties 1 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Page v2"
    When I select "A90,A85" on "C285_Multiple_Select Duties 2 Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Duty Page v2" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "C285_Multiple_Select Duties 2 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Duty Page v2" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "C285_Multiple_Select Duties 2 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Duty Page v2"
    Then I am presented with the "C285_Multiple_Check Claim Page v2"
    And I select radio button "yes" on "C285_Multiple_Check Claim Page v2"
    When I click continue on "C285_Multiple_Check Claim Page v2"
    Then I am presented with the "C285_Multiple_Choose Payee Type v2"
    And I select radio button "Importer" on "C285_Multiple_Choose Payee Type v2"
    When I click continue on "C285_Multiple_Choose Payee Type v2"
    Then I am presented with the "C285_Multiple_Enter Bank Account Details Page v2"
    And I enter "" on "C285_Multiple_Enter Bank Account Details Page v2"
    When I click continue on "C285_Multiple_Enter Bank Account Details Page v2"
#    Then I am presented with the "C285_Multiple_Check These Bank Details Are Correct Page v2"
#    And I select radio button "yes" on "C285_Multiple_Check These Bank Details Are Correct Page v2"
#    When I click continue on "C285_Multiple_Check These Bank Details Are Correct Page v2"
    Then I am presented with the "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    When I select radio button "Commercial invoice" on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    And I click continue on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    Then I am presented with the "UCDF_Choose File Other Page" "Commercial invoice"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    Then I am presented with the "C285_Multiple_Check Answers Accept Send Page v2"
    And I should see the following details
      | Basis of claim | Import date    | Contact details                                        | Importer email          | Contact address                             | Name on the account | Importer telephone | Importer name   | Account number   | Declarant name         | Importer address                            | Additional claim details | Declarant address                                         | Total   | Method of payment |Local Reference Number (LRN)| Duties paid | Sort code      | First MRN          | Second MRN         | 20AAAAAAAAAAAAAAA1 | 60AAAAAAAAAAAAAAA1 | Uploaded                        |
      | Outward processing relief          | 13 August 2019 | John Smith,john@smith.com,01234567890 | enquiries@swftgoods.com | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | Mr John Smith       | 0207 678 3243      | Swift Goods Ltd | 11001001 | Fred Bloggs and Co Ltd | 14 Briar Lane,London,Pimlico,United Kingdom | under 500 characters             | 10 Rillington Place,London,Pimlico,W11 1RH,United Kingdom | £788.00 | Immediate Payment |XFGLKJDSE5GDPOIJEW985T                 |£828.00     | 123456 | 60AAAAAAAAAAAAAAA1 | 20AAAAAAAAAAAAAAA1 | £379.00            | £409.00            | document.pdf,Commercial invoice |
    And I click continue on "C285_Multiple_Check Answers Accept Send Page v2"
    Then I am presented with the "C285_Multiple_Claim Submitted Page v2"

  @test
  Scenario: error scenario - second mrn not linked to eori
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
#    When the "overpayments v2" feature is "enabled"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "bulk" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number Page v2"
    When I enter "10AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Multiple_Check Declaration Details Page v2"
    And I select radio button "yes" on "C285_Multiple_Check Declaration Details Page v2"
    And I click continue on "C285_Multiple_Check Declaration Details Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    When I enter "10AAAAAAAAAAAAAAA2" on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 2 Page v2" error page

  Scenario: error scenario - second mrn not linked to importer/declarant eori
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
#    When the "overpayments v2" feature is "enabled"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "bulk" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number Page v2"
    When I enter "10AAAAAAAAAAAAAAA2" on "C285_Multiple_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Multiple_Enter Importer Eori Page v2"
    When I enter "GB000000000000002" on "C285_Multiple_Enter Importer Eori Page v2"
    And I click continue on "C285_Multiple_Enter Importer Eori Page v2"
    Then I am presented with the "C285_Multiple_Enter Declarant Eori Page v2"
    When I enter "GB000000000000002" on "C285_Multiple_Enter Declarant Eori Page v2"
    And I click continue on "C285_Multiple_Enter Declarant Eori Page v2"
    Then I am presented with the "C285_Multiple_Check Declaration Details Page v2"
    And I select radio button "yes" on "C285_Multiple_Check Declaration Details Page v2"
    And I click continue on "C285_Multiple_Check Declaration Details Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    When I enter "10AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 2 Page v2" error page

  @smoke
  Scenario: error scenario - wrong mrn
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
#    When the "overpayments v2" feature is "enabled"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "bulk" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number Page v2"
    When I enter "10AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Multiple_Check Declaration Details Page v2"
    And I select radio button "no" on "C285_Multiple_Check Declaration Details Page v2"
    And I click continue on "C285_Multiple_Check Declaration Details Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number Page v2"
    When I enter "10AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Multiple_Check Declaration Details Page v2"
    And I select radio button "Yes" on "C285_Multiple_Check Declaration Details Page v2"
    And I click continue on "C285_Multiple_Check Declaration Details Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    When I enter "20AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    Then I am presented with the "C285_Multiple_Check Movement Reference Numbers Page v2"
    When I select radio button "No" on "C285_Multiple_Check Movement Reference Numbers Page v2"
    And I click continue on "C285_Multiple_Check Movement Reference Numbers Page v2"

  @test
  Scenario: happy path with many MRNs and duties
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
#    When the "overpayments v2" feature is "enabled"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "bulk" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number Page v2"
    When I enter "01AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Multiple_Check Declaration Details Page v2"
    And I select radio button "Yes" on "C285_Multiple_Check Declaration Details Page v2"
    And I click continue on "C285_Multiple_Check Movement Reference Numbers Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    When I enter "02AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    Then I am presented with the "C285_Multiple_Check Movement Reference Numbers Page v2"
    When I select radio button "Yes" on "C285_Multiple_Check Movement Reference Numbers Page v2"
    And I click continue on "C285_Multiple_Check Movement Reference Numbers Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 3 Page v2"
    When I enter "10XXXXXXXXXXXXXXX1" on "C285_Multiple_Enter Movement Reference Number 3 Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number 3 Page v2"
    Then I am presented with the "C285_Multiple_Check Movement Reference Numbers Page v2"
    When I select radio button "Yes" on "C285_Multiple_Check Movement Reference Numbers Page v2"
    And I click continue on "C285_Multiple_Check Movement Reference Numbers Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 4 Page v2"
    When I enter "10YYYYYYYYYYYYYYY1" on "C285_Multiple_Enter Movement Reference Number 4 Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number 4 Page v2"
    Then I am presented with the "C285_Multiple_Check Movement Reference Numbers Page v2"
    When I select radio button "Yes" on "C285_Multiple_Check Movement Reference Numbers Page v2"
    And I click continue on "C285_Multiple_Check Movement Reference Numbers Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 5 Page v2"
    When I enter "10ZZZZZZZZZZZZZZZ1" on "C285_Multiple_Enter Movement Reference Number 5 Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number 5 Page v2"
    Then I am presented with the "C285_Multiple_Check Movement Reference Numbers Page v2"
    When I select radio button "No" on "C285_Multiple_Check Movement Reference Numbers Page v2"
    And I click continue on "C285_Multiple_Check Movement Reference Numbers Page v2"
    Then I am presented with the "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I enter "" on "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I click continue on "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "C285_Multiple_Claimant Details Page v2"
    And I click continue on "C285_Multiple_Claimant Details Page v2"
    Then I am presented with the "C285_Multiple_Choose Basis For Claim Page v2"
    When I select radio button "Outward processing relief" on "C285_Multiple_Choose Basis For Claim Page v2"
    And I click continue on "C285_Multiple_Choose Basis For Claim Page v2"
    Then I am presented with the "C285_Multiple_Enter Additional Details Page v2"
    When I enter "under 500 characters" on "C285_Multiple_Enter Additional Details Page v2"
    And I click continue on "C285_Multiple_Enter Additional Details Page v2"

    Then I am presented with the "C285_Multiple_Select Duties 1 Page v2"
    When I select "A80,A95" on "C285_Multiple_Select Duties 1 Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Duty Page v2" "A80 - Definitive Anti-Dumping Duty"
    When I enter "0" on "C285_Multiple_Select Duties 1 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Duty Page v2" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "C285_Multiple_Select Duties 1 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Duty Page v2"

    Then I am presented with the "C285_Multiple_Select Duties 2 Page v2"
    When I select "A90,A85" on "C285_Multiple_Select Duties 2 Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Duty Page v2" "A90 - Definitive Countervailing Duty"
    When I enter "5" on "C285_Multiple_Select Duties 2 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Duty Page v2" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "C285_Multiple_Select Duties 2 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Duty Page v2"

    Then I am presented with the "C285_Multiple_Select Duties 3 Page v2"
    When I select "591,433,463" on "C285_Multiple_Select Duties 3 Page v2"
    And I click continue on "C285_Multiple_Select Duties 3 Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 3 Duty Page v2" "Excise Duty- Miscellaneous road fuels 591"
    When I enter "0" on "C285_Multiple_Select Duties 3 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 3 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 3 Duty Page v2" "Excise Duty - Low alcohol beverages 433"
    When I enter "5" on "C285_Multiple_Select Duties 3 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 3 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 3 Duty Page v2" "Excise Duty - Spirits 463"
    When I enter "20" on "C285_Multiple_Select Duties 3 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 3 Duty Page v2"

    Then I am presented with the "C285_Multiple_Select Duties 4 Page v2"
    When I select "A70,421,422,435,487" on "C285_Multiple_Select Duties 4 Page v2"
    And I click continue on "C285_Multiple_Select Duties 4 Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 4 Duty Page v2" "A70 - Additional Duty"
    When I enter "0" on "C285_Multiple_Select Duties 4 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 4 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 4 Duty Page v2" "Excise Duty - Made-wine 421"
    When I enter "5" on "C285_Multiple_Select Duties 4 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 4 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 4 Duty Page v2" "Excise Duty - Made-wine 422"
    When I enter "20" on "C285_Multiple_Select Duties 4 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 4 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 4 Duty Page v2" "Excise Duty - Low alcohol beverages 435"
    When I enter "30" on "C285_Multiple_Select Duties 4 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 4 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 4 Duty Page v2" "Excise Duty - Cider and perry 487"
    When I enter "5" on "C285_Multiple_Select Duties 4 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 4 Duty Page v2"

    Then I am presented with the "C285_Multiple_Select Duties 5 Page v2"
    When I select "561,589,595,591,592" on "C285_Multiple_Select Duties 5 Page v2"
    And I click continue on "C285_Multiple_Select Duties 5 Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 5 Duty Page v2" "Excise Duty - Hydrocarbon oil 561"
    When I enter "0" on "C285_Multiple_Select Duties 5 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 5 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 5 Duty Page v2" "Excise Duty - Biofuels 589"
    When I enter "5" on "C285_Multiple_Select Duties 5 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 5 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 5 Duty Page v2" "Excise Duty - Biofuels 595"
    When I enter "15" on "C285_Multiple_Select Duties 5 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 5 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 5 Duty Page v2" "Excise Duty - Miscellaneous road fuels 591"
    When I enter "5" on "C285_Multiple_Select Duties 5 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 5 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 5 Duty Page v2" "Excise Duty - Miscellaneous road fuels 592"
    When I enter "10" on "C285_Multiple_Select Duties 5 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 5 Duty Page v2"

    Then I am presented with the "C285_Multiple_Check Claim Page v2"
    And I select radio button "yes" on "C285_Multiple_Check Claim Page v2"
    When I click continue on "C285_Multiple_Check Claim Page v2"
    Then I am presented with the "C285_Multiple_Choose Payee Type v2"
    And I select radio button "Importer" on "C285_Multiple_Choose Payee Type v2"
    When I click continue on "C285_Multiple_Choose Payee Type v2"
#    Then I am presented with the "C285_Multiple_Check These Bank Details Are Correct Page v2"
#    And I select radio button "yes" on "C285_Multiple_Check These Bank Details Are Correct Page v2"
#    When I click continue on "C285_Multiple_Check These Bank Details Are Correct Page v2"
    Then I am presented with the "C285_Multiple_Enter Bank Account Details Page v2"
    And I enter "" on "C285_Multiple_Enter Bank Account Details Page v2"
    When I click continue on "C285_Multiple_Enter Bank Account Details Page v2"
    Then I am presented with the "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    When I select radio button "Commercial invoice" on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    And I click continue on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    Then I am presented with the "UCDF_Choose File Other Page" "Commercial invoice"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    Then I am presented with the "C285_Multiple_Check Answers Accept Send Page v2"
    And I should see the following details
      | Basis of claim | Import date      | Contact details                                      | Importer email       | Contact address                                  | Name on the account | Importer telephone | Importer name    | Account number   | Declarant name     | Importer address                                 | Additional claim details | Declarant address                                 | Total     | Method of payment |Duties paid | Sort code      | First MRN          | Second MRN         | Third MRN          | Fourth MRN         | Fifth MRN          | 01AAAAAAAAAAAAAAA1 | 02AAAAAAAAAAAAAAA1 | 10XXXXXXXXXXXXXXX1 | 10YYYYYYYYYYYYYYY1 | 10ZZZZZZZZZZZZZZZ1 | Uploaded                        |
      | Outward processing relief          | 12 February 2021 | John Smith,john@smith.com,01234567890 | automation@gmail.com | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | Mr John Smith | +4420723934397     | IT Solutions LTD | 11001001 | Foxpro Central LTD | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | under 500 characters             | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | £1,284.20 | Immediate Payment |£828.00     | 123456 | 01AAAAAAAAAAAAAAA1 | 02AAAAAAAAAAAAAAA1 | 10XXXXXXXXXXXXXXX1 | 10YYYYYYYYYYYYYYY1 | 10ZZZZZZZZZZZZZZZ1 | £419.00            | £384.00            | £96.20             | £340.00            | £45.00             | document.pdf,Commercial invoice |
    And I click continue on "C285_Multiple_Check Answers Accept Send Page v2"
    Then I am presented with the "C285_Multiple_Claim Submitted Page v2"


  @testFail
  Scenario: test temp pages - confirm ALF data works in journey (no contact details)
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000006" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
#    When the "overpayments v2" feature is "enabled"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "bulk" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number Page v2"
    When I enter "10AAAAAAAAAAAAAAA6" on "C285_Multiple_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Multiple_Check Declaration Details Page v2"
    And I select radio button "yes" on "C285_Multiple_Check Declaration Details Page v2"
    And I click continue on "C285_Multiple_Check Declaration Details Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    When I enter "10AAAAAAAAAAAAAAA2" on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    Then I am presented with the "C285_Multiple_Check Movement Reference Numbers Page v2"
    When I select radio button "No" on "C285_Multiple_Check Movement Reference Numbers Page v2"
    And I click continue on "C285_Multiple_Check Movement Reference Numbers Page v2"
    Then I am presented with the "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I enter "" on "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I click continue on "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "C285_Multiple_Claimant Details Add Page v2"
    When I select radio button "yes" on "C285_Multiple_Claimant Details Add Page v2"
    And I click continue on "C285_Multiple_Claimant Details Add Page v2"
    Then I am presented with the "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I enter "" on "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I click continue on "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page v2"
    And I enter "" on "ALF_Lookup Address Edit Page v2"
    And I click continue on "ALF_Lookup Address Edit Page v2"
    And I click continue on "ALF_Lookup Address Confirm Page v2"
    Then I am presented with the "C285_Multiple_Claimant Details Page v2"
    And I click continue on "C285_Multiple_Claimant Details Page v2"
    Then I am presented with the "C285_Multiple_Choose Basis For Claim Page v2"
    When I select radio button "Inward processing relief from Customs Duty" on "C285_Multiple_Choose Basis For Claim Page v2"
    And I click continue on "C285_Multiple_Choose Basis For Claim Page v2"
    Then I am presented with the "C285_Multiple_Enter Additional Details Page v2"
    When I enter "under 500 characters" on "C285_Multiple_Enter Additional Details Page v2"
    And I click continue on "C285_Multiple_Enter Additional Details Page v2"
    Then I am presented with the "C285_Single_Select Duties Page v2"
    When I select "A80,A95,A90,A85" on "C285_Single_Select Duties Page v2"
    And I click continue on "C285_Single_Select Duties Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Check Claim Page v2"
    And I select radio button "yes" on "C285_Single_Check Claim Page v2"
    When I click continue on "C285_Single_Check Claim Page v2"
    Then I am presented with the "C285_Multiple_Choose Payee Type v2"
    And I select radio button "Importer" on "C285_Multiple_Choose Payee Type v2"
    When I click continue on "C285_Multiple_Choose Payee Type v2"
    Then I am presented with the "C285_Multiple_Check These Bank Details Are Correct Page v2"
    And I select radio button "yes" on "C285_Multiple_Check These Bank Details Are Correct Page v2"
    When I click continue on "C285_Multiple_Check These Bank Details Are Correct Page v2"
    Then I am presented with the "C285_Multiple_Supporting Evidence Upload Supporting Evidence Page v2"
    When I upload a "document.pdf" file on "C285_Multiple_Supporting Evidence Upload Supporting Evidence Page v2"
    And I click continue on "C285_Multiple_Supporting Evidence Upload Supporting Evidence Page v2"
    And I click continue if I'm on "C285_Multiple_Supporting Evidence Upload Progress Page v2"
    When I select radio button "Commercial invoice" on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    And I click continue on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    Then I am presented with the "C285_Multiple_Supporting Evidence Check Your Answers Page v2"
    When I select radio button "No" on "C285_Multiple_Supporting Evidence Check Your Answers Page v2"
    And I click continue on "C285_Multiple_Supporting Evidence Check Your Answers Page v2"
    Then I am presented with the "C285_Multiple_Check Answers Accept Send Page v2"
    And I click continue on "C285_Multiple_Check Answers Accept Send Page v2"
    Then I am presented with the "C285_Multiple_Claim Submitted Page v2"


  @test
  Scenario: happy path with new payee type page - user with only importer bank details and selects declarant user - CMA not eligible
    #  60AAAAAAAAAAAAAAA5 => only importer bank details (user is only importer ) - CMA not eligible - display payee indicator page and navigates to /enter-bank-account-details after /bank-account-type page
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "bulk" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number Page v2"
    When I enter "60AAAAAAAAAAAAAAA5" on "C285_Multiple_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Multiple_Check Declaration Details Page v2"
    And I select radio button "yes" on "C285_Multiple_Check Declaration Details Page v2"
    And I click continue on "C285_Multiple_Check Declaration Details Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    When I enter "20AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    Then I am presented with the "C285_Multiple_Check Movement Reference Numbers Page v2"
    When I select radio button "No" on "C285_Multiple_Check Movement Reference Numbers Page v2"
    And I click continue on "C285_Multiple_Check Movement Reference Numbers Page v2"
    Then I am presented with the "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I enter "" on "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I click continue on "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "C285_Multiple_Claimant Details Page v2"
    And I click continue on "C285_Multiple_Claimant Details Page v2"
    Then I am presented with the "C285_Multiple_Choose Basis For Claim Page v2"
    When I select radio button "Outward processing relief" on "C285_Multiple_Choose Basis For Claim Page v2"
    And I click continue on "C285_Multiple_Choose Basis For Claim Page v2"
    Then I am presented with the "C285_Multiple_Enter Additional Details Page v2"
    When I enter "under 500 characters" on "C285_Multiple_Enter Additional Details Page v2"
    And I click continue on "C285_Multiple_Enter Additional Details Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Page v2"
    When I select "A80,A95" on "C285_Multiple_Select Duties 1 Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Duty Page v2" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "C285_Multiple_Select Duties 1 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Duty Page v2" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "C285_Multiple_Select Duties 1 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Page v2"
    When I select "A90,A85" on "C285_Multiple_Select Duties 2 Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Duty Page v2" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "C285_Multiple_Select Duties 2 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Duty Page v2" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "C285_Multiple_Select Duties 2 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Duty Page v2"
    Then I am presented with the "C285_Multiple_Check Claim Page v2"
    And I select radio button "yes" on "C285_Multiple_Check Claim Page v2"
    When I click continue on "C285_Multiple_Check Claim Page v2"
    Then I am presented with the "C285_Multiple_Choose Payee Type v2"
    And I select radio button "Declarant / Representative" on "C285_Multiple_Choose Payee Type v2"
    When I click continue on "C285_Multiple_Choose Payee Type v2"
    Then I am presented with the "C285_Multiple_Enter Bank Account Details Page v2"
    And I enter "" on "C285_Multiple_Enter Bank Account Details Page v2"
    When I click continue on "C285_Multiple_Enter Bank Account Details Page v2"
#    Then I am presented with the "C285_Multiple_Check These Bank Details Are Correct Page v2"
#    And I select radio button "yes" on "C285_Multiple_Check These Bank Details Are Correct Page v2"
#    When I click continue on "C285_Multiple_Check These Bank Details Are Correct Page v2"
    Then I am presented with the "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    When I select radio button "Commercial invoice" on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    And I click continue on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    Then I am presented with the "UCDF_Choose File Other Page" "Commercial invoice"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    Then I am presented with the "C285_Multiple_Check Answers Accept Send Page v2"
    And I should see the following details
      | Basis of claim | Import date    | Contact details                                        | Importer email          | Contact address                             | Name on the account | Importer telephone | Importer name   | Account number   | Declarant name         | Importer address                            | Additional claim details | Declarant address                                         | Total   | Method of payment |Local Reference Number (LRN)| Duties paid | Sort code      | First MRN          | Second MRN         | 20AAAAAAAAAAAAAAA1 | 60AAAAAAAAAAAAAAA5 | Uploaded                        |
      | Outward processing relief          | 13 August 2019 | John Smith,john@smith.com,01234567890 | enquiries@swftgoods.com | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | Mr John Smith | 0207 678 3243      | Swift Goods Ltd | 11001001 | Fred Bloggs and Co Ltd       | 14 Briar Lane,London,Pimlico,United Kingdom | under 500 characters             | 10 Rillington Place,London,Pimlico,W11 1RH,United Kingdom | £788.00 | Immediate Payment |XFGLKJDSE5GDPOIJEW985T                 |£828.00     | 123456 | 60AAAAAAAAAAAAAAA5 | 20AAAAAAAAAAAAAAA1 | £379.00            | £409.00            | document.pdf,Commercial invoice |
    And I click continue on "C285_Multiple_Check Answers Accept Send Page v2"
    Then I am presented with the "C285_Multiple_Claim Submitted Page v2"
