@C285 @Multiple
Feature: C285 Multiple - XIEORI V2

  @test
  Scenario: happy path - check importer/declarant eori pages
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
#    When the "overpayments v2" feature is "enabled"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "bulk" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Multiple_Have Your Supporting Document Ready Page v2"
    When I clickContinue on "C285_Multiple_Have Your Supporting Document Ready Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number Page v2"
    When I enter "10XIDCAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Multiple_Enter Importer Eori Page v2"
    When I enter "XI000000000000001" on "C285_Multiple_Enter Importer Eori Page v2"
    And I click continue on "C285_Multiple_Enter Importer Eori Page v2"
    Then I am presented with the "C285_Multiple_Enter Declarant Eori Page v2"
    When I enter "XI000000000000001" on "C285_Multiple_Enter Declarant Eori Page v2"
    And I click continue on "C285_Multiple_Enter Declarant Eori Page v2"
    Then I am presented with the "C285_Multiple_Check Declaration Details Page v2"
    And I select radio button "yes" on "C285_Multiple_Check Declaration Details Page v2"
    And I click continue on "C285_Multiple_Check Declaration Details Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    When I enter "20XIDCAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    Then I am presented with the "C285_Multiple_Check Movement Reference Numbers Page v2"
    When I select radio button "No" on "C285_Multiple_Check Movement Reference Numbers Page v2"
    And I click continue on "C285_Multiple_Check Movement Reference Numbers Page v2"
    # new changes to flow
    Then I am presented with the "C285_Multiple_Choose Basis For Claim Page v2"
    When I select radio button "Outward processing relief" on "C285_Multiple_Choose Basis For Claim Page v2"
    And I click continue on "C285_Multiple_Choose Basis For Claim Page v2"
    Then I am presented with the "C285_Multiple_Enter Additional Details Page v2"
    When I enter "under 500 characters" on "C285_Multiple_Enter Additional Details Page v2"
    And I click continue on "C285_Multiple_Enter Additional Details Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Page v2"
    When I select "A80,A95" on "C285_Multiple_Select Duties 1 Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Duty Page v2" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "C285_Multiple_Select Duties 1 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Duty Page v2" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "C285_Multiple_Select Duties 1 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Page v2"
    When I select "A90,A85" on "C285_Multiple_Select Duties 2 Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Duty Page v2" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "C285_Multiple_Select Duties 2 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Duty Page v2" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "C285_Multiple_Select Duties 2 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Duty Page v2"
    Then I am presented with the "C285_Multiple_Check Claim Page v2"
    And I select radio button "yes" on "C285_Multiple_Check Claim Page v2"
    When I click continue on "C285_Multiple_Check Claim Page v2"
    Then I am presented with the "C285_Multiple_Choose Payee Type v2"
    And I select radio button "Importer" on "C285_Multiple_Choose Payee Type v2"
    When I click continue on "C285_Multiple_Choose Payee Type v2"
#    Then I am presented with the "C285_Multiple_Check These Bank Details Are Correct Page v2"
#    And I select radio button "yes" on "C285_Multiple_Check These Bank Details Are Correct Page v2"
#    When I click continue on "C285_Multiple_Check These Bank Details Are Correct Page v2"
    Then I am presented with the "C285_Multiple_Enter Bank Account Details Page v2"
    And I enter "" on "C285_Multiple_Enter Bank Account Details Page v2"
    When I click continue on "C285_Multiple_Enter Bank Account Details Page v2"
    Then I am presented with the "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    When I select radio button "Commercial invoice" on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    And I click continue on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    Then I am presented with the "UCDF_Choose File Other Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
# new changes to flow
    Then I am presented with the "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I enter "" on "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I click continue on "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "C285_Multiple_Claimant Details Page v2"
    And I click continue on "C285_Multiple_Claimant Details Page v2"
    Then I am presented with the "C285_Multiple_Check Answers Accept Send Page v2"
    And I should see the following details
      | Basis of claim | Import date      | Contact details                   | Contact address                                   | Name on the account   | Account number   | Additional claim details                                 | Total   | Method of payment |Duties paid | Sort code      | First MRN          | Second MRN         | Uploaded                        | 20XIDCAAAAAAAAAAA1 | 10XIDCAAAAAAAAAAA1 |
      | Outward processing relief          | 12 February 2021 | John Smith,john@smith.com,01234567890 | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | Mr John Smith | 11001001 | under 500 characters            | £40.00 | Immediate payment |£828.00     | 123456 | 10XIDCAAAAAAAAAAA1 | 20XIDCAAAAAAAAAAA1 | document.pdf,Commercial invoice | £20.00            | £20.00            |
    And I click continue on "C285_Multiple_Check Answers Accept Send Page v2"
    Then I am presented with the "C285_Multiple_Claim Submitted Page v2"


  @smoke
  Scenario: happy path - don't check importer/declarant eori pages
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
#    When the "overpayments v2" feature is "enabled"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "bulk" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Multiple_Have Your Supporting Document Ready Page v2"
    When I clickContinue on "C285_Multiple_Have Your Supporting Document Ready Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number Page v2"
    When I enter "10XIDAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Multiple_Check Declaration Details Page v2"
    And I select radio button "yes" on "C285_Multiple_Check Declaration Details Page v2"
    And I click continue on "C285_Multiple_Check Declaration Details Page v2"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    When I enter "20AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    And I click continue on "C285_Multiple_Enter Movement Reference Number 2 Page v2"
    Then I am presented with the "C285_Multiple_Check Movement Reference Numbers Page v2"
    When I select radio button "No" on "C285_Multiple_Check Movement Reference Numbers Page v2"
    And I click continue on "C285_Multiple_Check Movement Reference Numbers Page v2"
    # new changes to flow
    Then I am presented with the "C285_Multiple_Choose Basis For Claim Page v2"
    When I select radio button "Outward processing relief" on "C285_Multiple_Choose Basis For Claim Page v2"
    And I click continue on "C285_Multiple_Choose Basis For Claim Page v2"
    Then I am presented with the "C285_Multiple_Enter Additional Details Page v2"
    When I enter "under 500 characters" on "C285_Multiple_Enter Additional Details Page v2"
    And I click continue on "C285_Multiple_Enter Additional Details Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Page v2"
    When I select "A80,A95" on "C285_Multiple_Select Duties 1 Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Duty Page v2" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "C285_Multiple_Select Duties 1 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 1 Duty Page v2" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "C285_Multiple_Select Duties 1 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 1 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Page v2"
    When I select "A90,A85" on "C285_Multiple_Select Duties 2 Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Duty Page v2" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "C285_Multiple_Select Duties 2 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Duty Page v2"
    Then I am presented with the "C285_Multiple_Select Duties 2 Duty Page v2" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "C285_Multiple_Select Duties 2 Duty Page v2"
    And I click continue on "C285_Multiple_Select Duties 2 Duty Page v2"
    Then I am presented with the "C285_Multiple_Check Claim Page v2"
    And I select radio button "yes" on "C285_Multiple_Check Claim Page v2"
    When I click continue on "C285_Multiple_Check Claim Page v2"
    Then I am presented with the "C285_Multiple_Choose Payee Type v2"
    And I select radio button "Importer" on "C285_Multiple_Choose Payee Type v2"
    When I click continue on "C285_Multiple_Choose Payee Type v2"
    Then I am presented with the "C285_Multiple_Check These Bank Details Are Correct Page v2"
    And I select radio button "yes" on "C285_Multiple_Check These Bank Details Are Correct Page v2"
    When I click continue on "C285_Multiple_Check These Bank Details Are Correct Page v2"
    Then I am presented with the "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    When I select radio button "Commercial invoice" on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    And I click continue on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page v2"
    Then I am presented with the "UCDF_Choose File Other Page" "Commercial invoice"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
# new changes to flow
    Then I am presented with the "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I enter "" on "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I click continue on "C285_Multiple_Claimant Details Enter Contact Details Page v2"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "C285_Multiple_Claimant Details Page v2"
    And I click continue on "C285_Multiple_Claimant Details Page v2"
    Then I am presented with the "C285_Multiple_Check Answers Accept Send Page v2"
    And I should see the following details
      | This is the basis behind the claim | Import date      | Contact details                                           | Contact address                                  | Name on the account   | Account number                                | This is the reason for the claim                                | Total   |Method of payment | Duties paid | Sort code      | First MRN          | Second MRN         | 20AAAAAAAAAAAAAAA1 | 10XIDAAAAAAAAAAAA1 | Uploaded                        |
      | Outward processing relief          | 12 February 2021 | John Smith,john@smith.com,01234567890 | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | Mr John Smith | 11001001 | under 500 characters             | £788.00 | Immediate payment| £828.00     | 123456 | 10XIDAAAAAAAAAAAA1 | 20AAAAAAAAAAAAAAA1 | £379.00            | £409.00            | document.pdf,Commercial invoice |
    And I click continue on "C285_Multiple_Check Answers Accept Send Page v2"
    Then I am presented with the "C285_Multiple_Claim Submitted Page v2"

