@C285 @Multiple
Feature: C285 Multiple (bulk enabled, entry disabled)

  Background:
    Given the "Bulk Claim" feature is "enabled"
    Given the "Entry Number" feature is "disabled"
    Given the "Northern Ireland" feature is "enabled"
    Given the "Rejected Goods" feature is "enabled"
    Given the "Internal Upload Documents" feature is "enabled"

  @test
  Scenario: happy path
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Choose How Many Mrns Page"
    When I select radio button "bulk" on "Choose How Many Mrns Page"
    And I click continue on "Choose How Many Mrns Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number Page"
    And I click continue on "Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "Multiple_Check Declaration Details Page"
    And I select radio button "yes" on "Multiple_Check Declaration Details Page"
    And I click continue on "Multiple_Check Declaration Details Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number 2 Page"
    When I enter "20AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "Multiple_Check Movement Reference Numbers Page"
    When I select radio button "No" on "Multiple_Check Movement Reference Numbers Page"
    And I click continue on "Multiple_Check Movement Reference Numbers Page"

    #Then I am presented with the "Multiple_Who Is The Declarant Page"
    #When I select radio button "I am a private individual importer" on "Multiple_Who Is The Declarant Page"
    #And I click continue on "Multiple_Who Is The Declarant Page"

    Then I am presented with the "Multiple_Claimant Details Page"
    #When I select radio button "yes" on "Multiple_Claimant Details Page"
    And I click continue on "Multiple_Claimant Details Page"

    Then I am presented with the "Multiple_Claim Northern Ireland Page"
    And I select radio button "yes" on "Single_Claim Northern Ireland Page"
    And I click continue on "Multiple_Claim Northern Ireland Page"
    Then I am presented with the "Multiple_Choose Basis For Claim Page"
    When I select radio button "Outward processing relief" on "Multiple_Choose Basis For Claim Page"
    And I click continue on "Multiple_Choose Basis For Claim Page"
    Then I am presented with the "Multiple_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Multiple_Enter Commodity Details Page"
    And I click continue on "Multiple_Enter Commodity Details Page"
    Then I am presented with the "Multiple_Select Duties 1 Page"
    When I select "A80,A95" on "Multiple_Select Duties 1 Page"
    And I click continue on "Multiple_Select Duties 1 Page"
    Then I am presented with the "Multiple_Select Duties 1 Duty Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "Multiple_Select Duties 1 Duty Page"
    And I click continue on "Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "Multiple_Select Duties 1 Duty Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "Multiple_Select Duties 1 Duty Page"
    And I click continue on "Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "Multiple_Select Duties 2 Page"
    When I select "A90,A85" on "Multiple_Select Duties 2 Page"
    And I click continue on "Multiple_Select Duties 2 Page"
    Then I am presented with the "Multiple_Select Duties 2 Duty Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "Multiple_Select Duties 2 Duty Page"
    And I click continue on "Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "Multiple_Select Duties 2 Duty Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "Multiple_Select Duties 2 Duty Page"
    And I click continue on "Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "Multiple_Check Claim Page"
    And I select radio button "yes" on "Multiple_Check Claim Page"
    When I click continue on "Multiple_Check Claim Page"
    Then I am presented with the "Multiple_Check These Bank Details Are Correct Page"
    When I click continue on "Multiple_Check These Bank Details Are Correct Page"
    Then I am presented with the "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Multiple_Supporting Evidence Upload Progress Page"
    When I select radio button "Commercial invoice" on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Multiple_Supporting Evidence Check Your Answers Page"
    When I select radio button "No" on "Multiple_Supporting Evidence Check Your Answers Page"
    And I click continue on "Multiple_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Multiple_Check Answers Accept Send Page"
    And I click continue on "Multiple_Check Answers Accept Send Page"
    Then I am presented with the "Multiple_Claim Submitted Page"

  @test
  Scenario: error scenario - second mrn not linked to eori
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Choose How Many Mrns Page"
    When I select radio button "bulk" on "Choose How Many Mrns Page"
    And I click continue on "Choose How Many Mrns Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number Page"
    And I click continue on "Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "Multiple_Check Declaration Details Page"
    And I select radio button "yes" on "Multiple_Check Declaration Details Page"
    And I click continue on "Multiple_Check Declaration Details Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number 2 Page"
    When I enter "10AAAAAAAAAAAAAAA2" on "Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number 2 Page" error page

  @test
  Scenario: error scenario - second mrn not linked to importer/declarant eori
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Choose How Many Mrns Page"
    When I select radio button "bulk" on "Choose How Many Mrns Page"
    And I click continue on "Choose How Many Mrns Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA2" on "Multiple_Enter Movement Reference Number Page"
    And I click continue on "Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "Multiple_Enter Importer Eori Page"
    When I enter "GB000000000000002" on "Multiple_Enter Importer Eori Page"
    And I click continue on "Multiple_Enter Importer Eori Page"
    Then I am presented with the "Multiple_Enter Declarant Eori Page"
    When I enter "GB000000000000002" on "Multiple_Enter Declarant Eori Page"
    And I click continue on "Multiple_Enter Declarant Eori Page"
    Then I am presented with the "Multiple_Check Declaration Details Page"
    And I select radio button "yes" on "Multiple_Check Declaration Details Page"
    And I click continue on "Multiple_Check Declaration Details Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number 2 Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number 2 Page" error page


  @test @a11y @ZAP
  Scenario: happy path - check importer/declarant eori pages
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Choose How Many Mrns Page"
    When I select radio button "bulk" on "Choose How Many Mrns Page"
    And I click continue on "Choose How Many Mrns Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA2" on "Multiple_Enter Movement Reference Number Page"
    And I click continue on "Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "Multiple_Enter Importer Eori Page"
    When I enter "GB000000000000002" on "Multiple_Enter Importer Eori Page"
    And I click continue on "Multiple_Enter Importer Eori Page"
    Then I am presented with the "Multiple_Enter Declarant Eori Page"
    When I enter "GB000000000000002" on "Multiple_Enter Declarant Eori Page"
    And I click continue on "Multiple_Enter Declarant Eori Page"
    Then I am presented with the "Multiple_Check Declaration Details Page"
    And I select radio button "yes" on "Multiple_Check Declaration Details Page"
    And I click continue on "Multiple_Check Declaration Details Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number 2 Page"
    When I enter "20AAAAAAAAAAAAAAA2" on "Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "Multiple_Check Movement Reference Numbers Page"
    When I select radio button "No" on "Multiple_Check Movement Reference Numbers Page"
    And I click continue on "Multiple_Check Movement Reference Numbers Page"
    #Then I am presented with the "Multiple_Who Is The Declarant Page"
    #When I select radio button "I am a private individual importer" on "Multiple_Who Is The Declarant Page"
    #And I click continue on "Multiple_Who Is The Declarant Page"
    Then I am presented with the "Multiple_Claimant Details Page"
    #When I select radio button "yes" on "Multiple_Claimant Details Page"
    And I click continue on "Multiple_Claimant Details Page"
    Then I am presented with the "Multiple_Claim Northern Ireland Page"
    And I select radio button "yes" on "Single_Claim Northern Ireland Page"
    And I click continue on "Multiple_Claim Northern Ireland Page"
    Then I am presented with the "Multiple_Choose Basis For Claim Page"
    When I select radio button "Outward processing relief" on "Multiple_Choose Basis For Claim Page"
    And I click continue on "Multiple_Choose Basis For Claim Page"
    Then I am presented with the "Multiple_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Multiple_Enter Commodity Details Page"
    And I click continue on "Multiple_Enter Commodity Details Page"
    Then I am presented with the "Multiple_Select Duties 1 Page"
    When I select "A80,A95" on "Multiple_Select Duties 1 Page"
    And I click continue on "Multiple_Select Duties 1 Page"
    Then I am presented with the "Multiple_Select Duties 1 Duty Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "Multiple_Select Duties 1 Duty Page"
    And I click continue on "Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "Multiple_Select Duties 1 Duty Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "Multiple_Select Duties 1 Duty Page"
    And I click continue on "Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "Multiple_Select Duties 2 Page"
    When I select "A90,A85" on "Multiple_Select Duties 2 Page"
    And I click continue on "Multiple_Select Duties 2 Page"
    Then I am presented with the "Multiple_Select Duties 2 Duty Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "Multiple_Select Duties 2 Duty Page"
    And I click continue on "Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "Multiple_Select Duties 2 Duty Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "Multiple_Select Duties 2 Duty Page"
    And I click continue on "Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "Multiple_Check Claim Page"
    And I select radio button "yes" on "Multiple_Check Claim Page"
    When I click continue on "Multiple_Check Claim Page"
    Then I am presented with the "Multiple_Check These Bank Details Are Correct Page"
    When I click continue on "Multiple_Check These Bank Details Are Correct Page"
    Then I am presented with the "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Multiple_Supporting Evidence Upload Progress Page"
    When I select radio button "Commercial invoice" on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Multiple_Supporting Evidence Check Your Answers Page"
    When I select radio button "No" on "Multiple_Supporting Evidence Check Your Answers Page"
    And I click continue on "Multiple_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Multiple_Check Answers Accept Send Page"
    And I click continue on "Multiple_Check Answers Accept Send Page"
    Then I am presented with the "Multiple_Claim Submitted Page"

  @test
  Scenario: wrong mrn
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Choose How Many Mrns Page"
    When I select radio button "bulk" on "Choose How Many Mrns Page"
    And I click continue on "Choose How Many Mrns Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number Page"
    And I click continue on "Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "Multiple_Check Declaration Details Page"
    And I select radio button "no" on "Multiple_Check Declaration Details Page"
    And I click continue on "Multiple_Check Declaration Details Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number Page"
    And I click continue on "Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "Multiple_Check Movement Reference Numbers Page"
    And I select radio button "Yes" on "Multiple_Check Movement Reference Numbers Page"
    And I click continue on "Multiple_Check Movement Reference Numbers Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number 2 Page"
    When I enter "20AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "Multiple_Check Movement Reference Numbers Page"
    When I select radio button "No" on "Multiple_Check Movement Reference Numbers Page"
    And I click continue on "Multiple_Check Movement Reference Numbers Page"

  @ALF
  Scenario: happy path (mrn) - confirm ALF data works in journey
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Choose How Many Mrns Page"
    When I select radio button "bulk" on "Choose How Many Mrns Page"
    And I click continue on "Choose How Many Mrns Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number Page"
    And I click continue on "Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "Multiple_Check Declaration Details Page"
    And I select radio button "yes" on "Multiple_Check Declaration Details Page"
    And I click continue on "Multiple_Check Declaration Details Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number 2 Page"
    When I enter "20AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "Multiple_Check Movement Reference Numbers Page"
    When I select radio button "No" on "Multiple_Check Movement Reference Numbers Page"
    And I click continue on "Multiple_Check Movement Reference Numbers Page"
    When I select radio button "I am a private individual importer" on "Multiple_Who Is The Declarant Page"
    And I click continue on "Multiple_Who Is The Declarant Page"
    Then I am presented with the "Multiple_Claimant Details Check Page"
    When I select radio button "no" on "Multiple_Claimant Details Check Page"
    And I click continue on "Multiple_Claimant Details Check Page"
    Then I am presented with the "Multiple_Claimant Details Add Page"
    When I select radio button "yes" on "Multiple_Claimant Details Add Page"
    And I click continue on "Multiple_Claimant Details Add Page"
    Then I am presented with the "Multiple_Claimant Details Enter Contact Details Page"
    And I enter "" on "Multiple_Claimant Details Enter Contact Details Page"
    And I click continue on "Multiple_Claimant Details Enter Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Multiple_Claimant Details Page"
    #When I select radio button "yes" on "Multiple_Claimant Details Page"
    And I click continue on "Multiple_Claimant Details Page"
    Then I am presented with the "Multiple_Claim Northern Ireland Page"
    And I select radio button "yes" on "Single_Claim Northern Ireland Page"
    And I click continue on "Multiple_Claim Northern Ireland Page"
    Then I am presented with the "Multiple_Choose Basis For Claim Page"
    When I select radio button "Outward processing relief" on "Multiple_Choose Basis For Claim Page"
    And I click continue on "Multiple_Choose Basis For Claim Page"
    Then I am presented with the "Multiple_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Multiple_Enter Commodity Details Page"
    And I click continue on "Multiple_Enter Commodity Details Page"
    Then I am presented with the "Multiple_Select Duties 1 Page"
    When I select "A80,A95" on "Multiple_Select Duties 1 Page"
    And I click continue on "Multiple_Select Duties 1 Page"
    Then I am presented with the "Multiple_Select Duties 1 Duty Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "Multiple_Select Duties 1 Duty Page"
    And I click continue on "Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "Multiple_Select Duties 1 Duty Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "Multiple_Select Duties 1 Duty Page"
    And I click continue on "Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "Multiple_Select Duties 2 Page"
    When I select "A90,A85" on "Multiple_Select Duties 2 Page"
    And I click continue on "Multiple_Select Duties 2 Page"
    Then I am presented with the "Multiple_Select Duties 2 Duty Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "Multiple_Select Duties 2 Duty Page"
    And I click continue on "Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "Multiple_Select Duties 2 Duty Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "Multiple_Select Duties 2 Duty Page"
    And I click continue on "Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "Multiple_Check Claim Page"
    And I select radio button "yes" on "Multiple_Check Claim Page"
    When I click continue on "Multiple_Check Claim Page"
    Then I am presented with the "Multiple_Check These Bank Details Are Correct Page"
    When I click continue on "Multiple_Check These Bank Details Are Correct Page"
    Then I am presented with the "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Multiple_Supporting Evidence Upload Progress Page"
    When I select radio button "Commercial invoice" on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Multiple_Supporting Evidence Check Your Answers Page"
    When I select radio button "No" on "Multiple_Supporting Evidence Check Your Answers Page"
    And I click continue on "Multiple_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Multiple_Check Answers Accept Send Page"
    And I click continue on "Multiple_Check Answers Accept Send Page"
    Then I am presented with the "Multiple_Claim Submitted Page"

  @testFail
  Scenario: test temp pages - confirm ALF data works in journey (no contact details)
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000006" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Choose How Many Mrns Page"
    When I select radio button "bulk" on "Choose How Many Mrns Page"
    And I click continue on "Choose How Many Mrns Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA6" on "Multiple_Enter Movement Reference Number Page"
    And I click continue on "Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "Multiple_Check Declaration Details Page"
    And I select radio button "yes" on "Multiple_Check Declaration Details Page"
    And I click continue on "Multiple_Check Declaration Details Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number 2 Page"
    When I enter "10AAAAAAAAAAAAAAA2" on "Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "Multiple_Check Movement Reference Numbers Page"
    When I select radio button "No" on "Multiple_Check Movement Reference Numbers Page"
    And I click continue on "Multiple_Check Movement Reference Numbers Page"
    #Then I am presented with the "Multiple_Who Is The Declarant Page"
    #When I select radio button "I am a private individual importer" on "Multiple_Who Is The Declarant Page"
    #And I click continue on "Multiple_Who Is The Declarant Page"
    Then I am presented with the "Multiple_Claimant Details Add Page"
    When I select radio button "yes" on "Multiple_Claimant Details Add Page"
    And I click continue on "Multiple_Claimant Details Add Page"
    Then I am presented with the "Multiple_Claimant Details Enter Contact Details Page"
    And I enter "" on "Multiple_Claimant Details Enter Contact Details Page"
    And I click continue on "Multiple_Claimant Details Enter Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "Multiple_Claimant Details Page"
    #When I select radio button "yes" on "Multiple_Claimant Details Page"
    And I click continue on "Multiple_Claimant Details Page"
    Then I am presented with the "Multiple_Claim Northern Ireland Page"
    And I select radio button "yes" on "Single_Claim Northern Ireland Page"
    And I click continue on "Multiple_Claim Northern Ireland Page"
    Then I am presented with the "Multiple_Choose Basis For Claim Page"
    When I select radio button "Inward processing relief from Customs Duty" on "Multiple_Choose Basis For Claim Page"
    And I click continue on "Multiple_Choose Basis For Claim Page"
    Then I am presented with the "Multiple_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Multiple_Enter Commodity Details Page"
    And I click continue on "Multiple_Enter Commodity Details Page"
    Then I am presented with the "Single_Select Duties Page"
    When I select "A80,A95,A90,A85" on "Single_Select Duties Page"
    And I click continue on "Single_Select Duties Page"
    Then I am presented with the "Single_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Check Claim Page"
    And I select radio button "yes" on "Single_Check Claim Page"
    When I click continue on "Single_Check Claim Page"
    Then I am presented with the "Multiple_Check These Bank Details Are Correct Page"
    When I click continue on "Multiple_Check These Bank Details Are Correct Page"
    Then I am presented with the "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Multiple_Supporting Evidence Upload Progress Page"
    When I select radio button "Commercial invoice" on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Multiple_Supporting Evidence Check Your Answers Page"
    When I select radio button "No" on "Multiple_Supporting Evidence Check Your Answers Page"
    And I click continue on "Multiple_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Multiple_Check Answers Accept Send Page"
    And I click continue on "Multiple_Check Answers Accept Send Page"
    Then I am presented with the "Multiple_Claim Submitted Page"

  @test
  Scenario: happy path with many MRNs and duties
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Choose How Many Mrns Page"
    When I select radio button "bulk" on "Choose How Many Mrns Page"
    And I click continue on "Choose How Many Mrns Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number Page"
    When I enter "01AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number Page"
    And I click continue on "Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "Multiple_Check Declaration Details Page"
    And I select radio button "Yes" on "Multiple_Check Declaration Details Page"
    And I click continue on "Multiple_Check Movement Reference Numbers Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number 2 Page"
    When I enter "02AAAAAAAAAAAAAAA1" on "Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "Multiple_Check Movement Reference Numbers Page"
    When I select radio button "Yes" on "Multiple_Check Movement Reference Numbers Page"
    And I click continue on "Multiple_Check Movement Reference Numbers Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number 3 Page"
    When I enter "10XXXXXXXXXXXXXXX1" on "Multiple_Enter Movement Reference Number 3 Page"
    And I click continue on "Multiple_Enter Movement Reference Number 3 Page"
    Then I am presented with the "Multiple_Check Movement Reference Numbers Page"
    When I select radio button "Yes" on "Multiple_Check Movement Reference Numbers Page"
    And I click continue on "Multiple_Check Movement Reference Numbers Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number 4 Page"
    When I enter "10YYYYYYYYYYYYYYY1" on "Multiple_Enter Movement Reference Number 4 Page"
    And I click continue on "Multiple_Enter Movement Reference Number 4 Page"
    Then I am presented with the "Multiple_Check Movement Reference Numbers Page"
    When I select radio button "Yes" on "Multiple_Check Movement Reference Numbers Page"
    And I click continue on "Multiple_Check Movement Reference Numbers Page"
    Then I am presented with the "Multiple_Enter Movement Reference Number 5 Page"
    When I enter "10ZZZZZZZZZZZZZZZ1" on "Multiple_Enter Movement Reference Number 5 Page"
    And I click continue on "Multiple_Enter Movement Reference Number 5 Page"
    Then I am presented with the "Multiple_Check Movement Reference Numbers Page"
    When I select radio button "No" on "Multiple_Check Movement Reference Numbers Page"
    And I click continue on "Multiple_Check Movement Reference Numbers Page"
    #Then I am presented with the "Multiple_Who Is The Declarant Page"
    #When I select radio button "I am a private individual importer" on "Multiple_Who Is The Declarant Page"
    #And I click continue on "Multiple_Who Is The Declarant Page"
    Then I am presented with the "Multiple_Claimant Details Page"
    #When I select radio button "yes" on "Multiple_Claimant Details Page"
    And I click continue on "Multiple_Claimant Details Page"
    Then I am presented with the "Multiple_Claim Northern Ireland Page"
    And I select radio button "yes" on "Single_Claim Northern Ireland Page"
    And I click continue on "Multiple_Claim Northern Ireland Page"
    Then I am presented with the "Multiple_Choose Basis For Claim Page"
    When I select radio button "Outward processing relief" on "Multiple_Choose Basis For Claim Page"
    And I click continue on "Multiple_Choose Basis For Claim Page"
    Then I am presented with the "Multiple_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Multiple_Enter Commodity Details Page"
    And I click continue on "Multiple_Enter Commodity Details Page"

    Then I am presented with the "Multiple_Select Duties 1 Page"
    When I select "A80,A95" on "Multiple_Select Duties 1 Page"
    And I click continue on "Multiple_Select Duties 1 Page"
    Then I am presented with the "Multiple_Select Duties 1 Duty Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "0" on "Multiple_Select Duties 1 Duty Page"
    And I click continue on "Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "Multiple_Select Duties 1 Duty Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "Multiple_Select Duties 1 Duty Page"
    And I click continue on "Multiple_Select Duties 1 Duty Page"

    Then I am presented with the "Multiple_Select Duties 2 Page"
    When I select "A90,A85" on "Multiple_Select Duties 2 Page"
    And I click continue on "Multiple_Select Duties 2 Page"
    Then I am presented with the "Multiple_Select Duties 2 Duty Page" "A90 - Definitive Countervailing Duty"
    When I enter "5" on "Multiple_Select Duties 2 Duty Page"
    And I click continue on "Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "Multiple_Select Duties 2 Duty Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "Multiple_Select Duties 2 Duty Page"
    And I click continue on "Multiple_Select Duties 2 Duty Page"

    Then I am presented with the "Multiple_Select Duties 3 Page"
    When I select "591,433,463" on "Multiple_Select Duties 3 Page"
    And I click continue on "Multiple_Select Duties 3 Page"
    Then I am presented with the "Multiple_Select Duties 3 Duty Page" "591 - Road fuel gases - natural gas including biogas"
    When I enter "0" on "Multiple_Select Duties 3 Duty Page"
    And I click continue on "Multiple_Select Duties 3 Duty Page"
    Then I am presented with the "Multiple_Select Duties 3 Duty Page" "433 - Wine, spirit based beverage exceeding 1.2% vol., but not exceeding 4% vol."
    When I enter "5" on "Multiple_Select Duties 3 Duty Page"
    And I click continue on "Multiple_Select Duties 3 Duty Page"
    Then I am presented with the "Multiple_Select Duties 3 Duty Page" "463 - UK produced whisky - blended"
    When I enter "20" on "Multiple_Select Duties 3 Duty Page"
    And I click continue on "Multiple_Select Duties 3 Duty Page"

    Then I am presented with the "Multiple_Select Duties 4 Page"
    When I select "A70,421,422,435,487" on "Multiple_Select Duties 4 Page"
    And I click continue on "Multiple_Select Duties 4 Page"
    Then I am presented with the "Multiple_Select Duties 4 Duty Page" "A70 - Additional Duty"
    When I enter "0" on "Multiple_Select Duties 4 Duty Page"
    And I click continue on "Multiple_Select Duties 4 Duty Page"
    Then I am presented with the "Multiple_Select Duties 4 Duty Page" "421 - Made-wine (sparkling), exceeding 8.5% vol. but not exceeding 15% vol."
    When I enter "5" on "Multiple_Select Duties 4 Duty Page"
    And I click continue on "Multiple_Select Duties 4 Duty Page"
    Then I am presented with the "Multiple_Select Duties 4 Duty Page" "422 - Made-wine (sparkling), exceeding 5.5% vol. but less than 8.5% vol."
    When I enter "20" on "Multiple_Select Duties 4 Duty Page"
    And I click continue on "Multiple_Select Duties 4 Duty Page"
    Then I am presented with the "Multiple_Select Duties 4 Duty Page" "435 - Wine, spirit based beverage exceeding 4% vol., but not exceeding 5.5% vol."
    When I enter "30" on "Multiple_Select Duties 4 Duty Page"
    And I click continue on "Multiple_Select Duties 4 Duty Page"
    Then I am presented with the "Multiple_Select Duties 4 Duty Page" "487 - Cider and Perry (still), made in the UK or imported exceeding 6.9% but not exceeding 7.5%"
    When I enter "5" on "Multiple_Select Duties 4 Duty Page"
    And I click continue on "Multiple_Select Duties 4 Duty Page"
    
    Then I am presented with the "Multiple_Select Duties 5 Page"
    When I select "561,589,595,591,592" on "Multiple_Select Duties 5 Page"
    And I click continue on "Multiple_Select Duties 5 Page"
    Then I am presented with the "Multiple_Select Duties 5 Duty Page" "561 - Heavy oil, fuel oil (unmarked)"
    When I enter "0" on "Multiple_Select Duties 5 Duty Page"
    And I click continue on "Multiple_Select Duties 5 Duty Page"
    Then I am presented with the "Multiple_Select Duties 5 Duty Page" "589 - Biodiesel"
    When I enter "5" on "Multiple_Select Duties 5 Duty Page"
    And I click continue on "Multiple_Select Duties 5 Duty Page"
    Then I am presented with the "Multiple_Select Duties 5 Duty Page" "595 - Bioethanol"
    When I enter "15" on "Multiple_Select Duties 5 Duty Page"
    And I click continue on "Multiple_Select Duties 5 Duty Page"
    Then I am presented with the "Multiple_Select Duties 5 Duty Page" "591 - Road fuel gases - natural gas including biogas"
    When I enter "5" on "Multiple_Select Duties 5 Duty Page"
    And I click continue on "Multiple_Select Duties 5 Duty Page"
    Then I am presented with the "Multiple_Select Duties 5 Duty Page" "592 - Road fuel gases – other than natural gas, for example, LPG"
    When I enter "10" on "Multiple_Select Duties 5 Duty Page"
    And I click continue on "Multiple_Select Duties 5 Duty Page"

    Then I am presented with the "Multiple_Check Claim Page"
    And I select radio button "yes" on "Multiple_Check Claim Page"
    When I click continue on "Multiple_Check Claim Page"
    Then I am presented with the "Multiple_Check These Bank Details Are Correct Page"
    When I click continue on "Multiple_Check These Bank Details Are Correct Page"
    Then I am presented with the "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Multiple_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Multiple_Supporting Evidence Upload Progress Page"
    When I select radio button "Commercial invoice" on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Multiple_Supporting Evidence Check Your Answers Page"
    When I select radio button "No" on "Multiple_Supporting Evidence Check Your Answers Page"
    And I click continue on "Multiple_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Multiple_Check Answers Accept Send Page"
    And I click continue on "Multiple_Check Answers Accept Send Page"
    Then I am presented with the "Multiple_Claim Submitted Page"
