@C285 @Multiple
Feature: C285 Multiple NI

  Background:
    Given the "Internal Upload Documents" feature is "disabled"

  @test
  Scenario: happy path
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page"
    When I select radio button "bulk" on "C285_Choose How Many Mrns Page"
    And I click continue on "C285_Choose How Many Mrns Page"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number Page"
    And I click continue on "C285_Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "C285_Multiple_Check Declaration Details Page"
    And I select radio button "yes" on "C285_Multiple_Check Declaration Details Page"
    And I click continue on "C285_Multiple_Check Declaration Details Page"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 2 Page"
    When I enter "20AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "C285_Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "C285_Multiple_Check Movement Reference Numbers Page"
    When I select radio button "No" on "C285_Multiple_Check Movement Reference Numbers Page"
    And I click continue on "C285_Multiple_Check Movement Reference Numbers Page"
    Then I am presented with the "C285_Multiple_Claimant Details Page"

  @test
  Scenario: happy path
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page"
    When I select radio button "bulk" on "C285_Choose How Many Mrns Page"
    And I click continue on "C285_Choose How Many Mrns Page"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number Page"
    And I click continue on "C285_Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "C285_Multiple_Check Declaration Details Page"
    And I select radio button "yes" on "C285_Multiple_Check Declaration Details Page"
    And I click continue on "C285_Multiple_Check Declaration Details Page"
    Then I am presented with the "C285_Multiple_Enter Movement Reference Number 2 Page"
    When I enter "20AAAAAAAAAAAAAAA1" on "C285_Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "C285_Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "C285_Multiple_Check Movement Reference Numbers Page"
    When I select radio button "No" on "C285_Multiple_Check Movement Reference Numbers Page"
    And I click continue on "C285_Multiple_Check Movement Reference Numbers Page"
    Then I am presented with the "C285_Multiple_Claimant Details Page"
    And I click continue on "C285_Multiple_Claimant Details Page"
    Then I am presented with the "C285_Multiple_Claim Northern Ireland Page"
    And I select radio button "yes" on "C285_Single_Claim Northern Ireland Page"
    And I click continue on "C285_Multiple_Claim Northern Ireland Page"
    Then I am presented with the "C285_Multiple_Choose Basis For Claim Page"
    When I select radio button "Incorrect additional information code (excluding NIAID)" on "C285_Multiple_Choose Basis For Claim Page"
    And I click continue on "C285_Multiple_Choose Basis For Claim Page"
    Then I am presented with the "C285_Multiple_Enter Additional Details Page"
    When I enter "under 500 characters" on "C285_Multiple_Enter Additional Details Page"
    And I click continue on "C285_Multiple_Enter Additional Details Page"
    Then I am presented with the "C285_Multiple_Select Duties 1 Page"
    When I select "A80,A95" on "C285_Multiple_Select Duties 1 Page"
    And I click continue on "C285_Multiple_Select Duties 1 Page"
    Then I am presented with the "C285_Multiple_Select Duties 1 Duty Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "C285_Multiple_Select Duties 1 Duty Page"
    And I click continue on "C285_Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "C285_Multiple_Select Duties 1 Duty Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "C285_Multiple_Select Duties 1 Duty Page"
    And I click continue on "C285_Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "C285_Multiple_Select Duties 2 Page"
    When I select "A90,A85" on "C285_Multiple_Select Duties 2 Page"
    And I click continue on "C285_Multiple_Select Duties 2 Page"
    Then I am presented with the "C285_Multiple_Select Duties 2 Duty Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "C285_Multiple_Select Duties 2 Duty Page"
    And I click continue on "C285_Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "C285_Multiple_Select Duties 2 Duty Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "C285_Multiple_Select Duties 2 Duty Page"
    And I click continue on "C285_Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "C285_Multiple_Check Claim Page"
    And I select radio button "yes" on "C285_Multiple_Check Claim Page"
    When I click continue on "C285_Multiple_Check Claim Page"
    Then I am presented with the "C285_Multiple_Check These Bank Details Are Correct Page"
    When I click continue on "C285_Multiple_Check These Bank Details Are Correct Page"
    Then I am presented with the "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    When I select radio button "Commercial invoice" on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "C285_Multiple_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "UCDF_Choose File Other Page"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    Then I am presented with the "C285_Multiple_Check Answers Accept Send Page"
    And I click continue on "C285_Multiple_Check Answers Accept Send Page"
    Then I am presented with the "C285_Multiple_Claim Submitted Page"
