@C285 @Single
Feature: C285 Single NI

  @test @a11y @ZAP
  Scenario: happy path - duplicate mrn
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page"
    When I select radio button "individual" on "C285_Choose How Many Mrns Page"
    And I click continue on "C285_Choose How Many Mrns Page"
    Then I am presented with the "C285_Single_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "C285_Single_Enter Movement Reference Number Page"
    And I click continue on "C285_Single_Enter Movement Reference Number Page"
    Then I am presented with the "C285_Single_Check Declaration Details Page"
    And I select radio button "yes" on "C285_Single_Check Declaration Details Page"
    And I click continue on "C285_Single_Check Declaration Details Page"
    Then I am presented with the "C285_Single_Claimant Details Page"
    And I click continue on "C285_Single_Claimant Details Page"
    Then I am presented with the "C285_Single_Claim Northern Ireland Page"
    And I select radio button "yes" on "C285_Single_Claim Northern Ireland Page"
    And I click continue on "C285_Single_Claim Northern Ireland Page"
    Then I am presented with the "C285_Single_Choose Basis For Claim Page"
    When I select radio button "Duplicate MRN" on "C285_Single_Choose Basis For Claim Page"
    And I click continue on "C285_Single_Choose Basis For Claim Page"
    Then I am presented with the "C285_Single_Enter Duplicate Movement Reference Number Page"
    When I enter "20AAAAAAAAAAAAAAA1" on "C285_Single_Enter Duplicate Movement Reference Number Page"
    And I click continue on "C285_Single_Enter Duplicate Movement Reference Number Page"
    Then I am presented with the "C285_Single_Check Duplicate Declaration Details Page"
    And I select radio button "yes" on "C285_Single_Check Duplicate Declaration Details Page"
    And I click continue on "C285_Single_Check Duplicate Declaration Details Page"
    Then I am presented with the "C285_Single_Enter Additional Details Page"
    When I enter "under 500 characters" on "C285_Single_Enter Additional Details Page"
    And I click continue on "C285_Single_Enter Additional Details Page"
    Then I am presented with the "C285_Single_Select Duties Page"
    When I select "A80,A95,A90,A85" on "C285_Single_Select Duties Page"
    And I click continue on "C285_Single_Select Duties Page"
    Then I am presented with the "C285_Single_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "C285_Single_Enter Claim Page"
    And I click continue on "C285_Single_Enter Claim Page"
    Then I am presented with the "C285_Single_Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "C285_Single_Enter Claim Page"
    And I click continue on "C285_Single_Enter Claim Page"
    Then I am presented with the "C285_Single_Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "C285_Single_Enter Claim Page"
    And I click continue on "C285_Single_Enter Claim Page"
    Then I am presented with the "C285_Single_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "C285_Single_Enter Claim Page"
    And I click continue on "C285_Single_Enter Claim Page"
    Then I am presented with the "C285_Single_Check Claim Page"
    And I select radio button "yes" on "C285_Single_Check Claim Page"
    When I click continue on "C285_Single_Check Claim Page"
    Then I am presented with the "C285_Single_Check These Bank Details Are Correct Page"
    When I click continue on "C285_Single_Check These Bank Details Are Correct Page"
    Then I am presented with the "C285_Single_Supporting Evidence Select Supporting Evidence Type Page"
    When I select radio button "Commercial invoice" on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "UCDF_Choose File Other Page"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    Then I am presented with the "C285_Single_Check Answers Accept Send Page"
    And I click continue on "C285_Single_Check Answers Accept Send Page"
    Then I am presented with the "C285_Single_Claim Submitted Page"

  @test @a11y @ZAP
  Scenario: happy path - duplicate mrn, not NI
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page"
    When I select radio button "individual" on "C285_Choose How Many Mrns Page"
    And I click continue on "C285_Choose How Many Mrns Page"
    Then I am presented with the "C285_Single_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "C285_Single_Enter Movement Reference Number Page"
    And I click continue on "C285_Single_Enter Movement Reference Number Page"
    Then I am presented with the "C285_Single_Check Declaration Details Page"
    And I select radio button "yes" on "C285_Single_Check Declaration Details Page"
    And I click continue on "C285_Single_Check Declaration Details Page"
    Then I am presented with the "C285_Single_Claimant Details Page"
    And I click continue on "C285_Single_Claimant Details Page"
    Then I am presented with the "C285_Single_Claim Northern Ireland Page"
    And I select radio button "no" on "C285_Single_Claim Northern Ireland Page"
    And I click continue on "C285_Single_Claim Northern Ireland Page"
    Then I am presented with the "C285_Single_Choose Basis For Claim Page"
    When I select radio button "Duplicate MRN" on "C285_Single_Choose Basis For Claim Page"
    And I click continue on "C285_Single_Choose Basis For Claim Page"
    Then I am presented with the "C285_Single_Enter Duplicate Movement Reference Number Page"
    When I enter "20AAAAAAAAAAAAAAA1" on "C285_Single_Enter Duplicate Movement Reference Number Page"
    And I click continue on "C285_Single_Enter Duplicate Movement Reference Number Page"
    Then I am presented with the "C285_Single_Check Duplicate Declaration Details Page"
    And I select radio button "yes" on "C285_Single_Check Duplicate Declaration Details Page"
    And I click continue on "C285_Single_Check Duplicate Declaration Details Page"
    Then I am presented with the "C285_Single_Enter Additional Details Page"
    When I enter "under 500 characters" on "C285_Single_Enter Additional Details Page"
    And I click continue on "C285_Single_Enter Additional Details Page"
    Then I am presented with the "C285_Single_Select Duties Page"
    When I select "A80,A95,A90,A85" on "C285_Single_Select Duties Page"
    And I click continue on "C285_Single_Select Duties Page"
    Then I am presented with the "C285_Single_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "C285_Single_Enter Claim Page"
    And I click continue on "C285_Single_Enter Claim Page"
    Then I am presented with the "C285_Single_Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "C285_Single_Enter Claim Page"
    And I click continue on "C285_Single_Enter Claim Page"
    Then I am presented with the "C285_Single_Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "C285_Single_Enter Claim Page"
    And I click continue on "C285_Single_Enter Claim Page"
    Then I am presented with the "C285_Single_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "C285_Single_Enter Claim Page"
    And I click continue on "C285_Single_Enter Claim Page"
    Then I am presented with the "C285_Single_Check Claim Page"
    And I select radio button "yes" on "C285_Single_Check Claim Page"
    When I click continue on "C285_Single_Check Claim Page"
    Then I am presented with the "C285_Single_Check These Bank Details Are Correct Page"
    When I click continue on "C285_Single_Check These Bank Details Are Correct Page"
    Then I am presented with the "C285_Single_Supporting Evidence Select Supporting Evidence Type Page"
    When I select radio button "Commercial invoice" on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "UCDF_Choose File Other Page"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    Then I am presented with the "C285_Single_Check Answers Accept Send Page"
    And I click continue on "C285_Single_Check Answers Accept Send Page"
    Then I am presented with the "C285_Single_Claim Submitted Page"

  @test
  Scenario: happy path - excise duty selected
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000002" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page"
    When I select radio button "individual" on "C285_Choose How Many Mrns Page"
    And I click continue on "C285_Choose How Many Mrns Page"
    Then I am presented with the "C285_Single_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA3" on "C285_Single_Enter Movement Reference Number Page"
    And I click continue on "C285_Single_Enter Movement Reference Number Page"
    Then I am presented with the "C285_Single_Check Declaration Details Page"
    And I select radio button "yes" on "C285_Single_Check Declaration Details Page"
    And I click continue on "C285_Single_Check Declaration Details Page"
    Then I am presented with the "C285_Single_Claimant Details Page"
    And I click continue on "C285_Single_Claimant Details Page"
    Then I am presented with the "C285_Single_Claim Northern Ireland Page"
    And I select radio button "yes" on "C285_Single_Claim Northern Ireland Page"
    And I click continue on "C285_Single_Claim Northern Ireland Page"
    Then I am presented with the "C285_Single_Choose Basis For Claim Page"
    When I select radio button "Incorrect excise value" on "C285_Single_Choose Basis For Claim Page"
    And I click continue on "C285_Single_Choose Basis For Claim Page"
    Then I am presented with the "C285_Single_Enter Additional Details Page"
    When I enter "under 500 characters" on "C285_Single_Enter Additional Details Page"
    And I click continue on "C285_Single_Enter Additional Details Page"
    Then I am presented with the "C285_Single_Select Duties Page"
    When I select "421,623,99C" on "C285_Single_Select Duties Page"
    And I click continue on "C285_Single_Select Duties Page"
    Then I am presented with the "C285_Single_Enter Claim Page" "421 - Made-wine (sparkling), exceeding 8.5% vol. but not exceeding 15% vol."
    When I enter "10" on "C285_Single_Enter Claim Page"
    And I click continue on "C285_Single_Enter Claim Page"
    Then I am presented with the "C285_Single_Enter Claim Page" "623 - Smoking tobacco – other"
    When I enter "10" on "C285_Single_Enter Claim Page"
    And I click continue on "C285_Single_Enter Claim Page"
    Then I am presented with the "C285_Single_Enter Claim Page" "99C - Gas supplied by a gas utility or any gas supplied in a gaseous state that is of a kind supplied by a gas utility Great Britain"
    When I enter "10" on "C285_Single_Enter Claim Page"
    And I click continue on "C285_Single_Enter Claim Page"
    Then I am presented with the "C285_Single_Check Claim Page"
    And I select radio button "yes" on "C285_Single_Check Claim Page"
    When I click continue on "C285_Single_Check Claim Page"
    Then I am presented with the "C285_Single_Select Reimbursement Method Page"
    When I select radio button "Bank account transfer" on "C285_Single_Select Reimbursement Method Page"
    When I click continue on "C285_Single_Select Reimbursement Method Page"
    Then I am presented with the "C285_Single_Check These Bank Details Are Correct Page"
    When I click continue on "C285_Single_Check These Bank Details Are Correct Page"
    Then I am presented with the "C285_Single_Supporting Evidence Select Supporting Evidence Type Page"
    When I select radio button "Commercial invoice" on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "UCDF_Choose File Other Page"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    Then I am presented with the "C285_Single_Check Answers Accept Send Page"
    And I click continue on "C285_Single_Check Answers Accept Send Page"
    Then I am presented with the "C285_Single_Claim Submitted Page"

  @test
  Scenario: happy path - excise journey but excise not selected
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000002" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page"
    When I select radio button "individual" on "C285_Choose How Many Mrns Page"
    And I click continue on "C285_Choose How Many Mrns Page"
    Then I am presented with the "C285_Single_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA3" on "C285_Single_Enter Movement Reference Number Page"
    And I click continue on "C285_Single_Enter Movement Reference Number Page"
    Then I am presented with the "C285_Single_Check Declaration Details Page"
    And I select radio button "yes" on "C285_Single_Check Declaration Details Page"
    And I click continue on "C285_Single_Check Declaration Details Page"
    Then I am presented with the "C285_Single_Claimant Details Page"
    And I click continue on "C285_Single_Claimant Details Page"
    Then I am presented with the "C285_Single_Claim Northern Ireland Page"
    And I select radio button "yes" on "C285_Single_Claim Northern Ireland Page"
    And I click continue on "C285_Single_Claim Northern Ireland Page"
    Then I am presented with the "C285_Single_Choose Basis For Claim Page"
    When I select radio button "Returned goods relief (RGR)" on "C285_Single_Choose Basis For Claim Page"
    And I click continue on "C285_Single_Choose Basis For Claim Page"
    Then I am presented with the "C285_Single_Enter Additional Details Page"
    When I enter "under 500 characters" on "C285_Single_Enter Additional Details Page"
    And I click continue on "C285_Single_Enter Additional Details Page"
    Then I am presented with the "C285_Single_Select Duties Page"
    When I select "A80,421,623,99C" on "C285_Single_Select Duties Page"
    And I click continue on "C285_Single_Select Duties Page"
    Then I am presented with the "C285_Single_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "C285_Single_Enter Claim Page"
    And I click continue on "C285_Single_Enter Claim Page"
    Then I am presented with the "C285_Single_Enter Claim Page" "421 - Made-wine (sparkling), exceeding 8.5% vol. but not exceeding 15% vol."
    When I enter "10" on "C285_Single_Enter Claim Page"
    And I click continue on "C285_Single_Enter Claim Page"
    Then I am presented with the "C285_Single_Enter Claim Page" "623 - Smoking tobacco – other"
    When I enter "10" on "C285_Single_Enter Claim Page"
    And I click continue on "C285_Single_Enter Claim Page"
    Then I am presented with the "C285_Single_Enter Claim Page" "99C - Gas supplied by a gas utility or any gas supplied in a gaseous state that is of a kind supplied by a gas utility Great Britain"
    When I enter "10" on "C285_Single_Enter Claim Page"
    And I click continue on "C285_Single_Enter Claim Page"
    Then I am presented with the "C285_Single_Check Claim Page"
    And I select radio button "yes" on "C285_Single_Check Claim Page"
    When I click continue on "C285_Single_Check Claim Page"
    Then I am presented with the "C285_Single_Check These Bank Details Are Correct Page"
    When I click continue on "C285_Single_Check These Bank Details Are Correct Page"
    Then I am presented with the "C285_Single_Supporting Evidence Select Supporting Evidence Type Page"
    When I select radio button "Commercial invoice" on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "UCDF_Choose File Other Page"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    Then I am presented with the "C285_Single_Check Answers Accept Send Page"
    And I click continue on "C285_Single_Check Answers Accept Send Page"
    Then I am presented with the "C285_Single_Claim Submitted Page"
