Feature: multiple for C&E1179

  Background:
    Given the "Bulk Claim" feature is "enabled"
    Given the "Entry Number" feature is "disabled"
    Given the "Northern Ireland" feature is "enabled"
    Given the "Rejected Goods" feature is "enabled"

  @test @a11y @ZAP
  Scenario: happy path
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "RejectedGoods_Choose How Many Mrns Page"
    And I select radio button "Enter multiple MRNs" on "RejectedGoods_Choose How Many Mrns Page"
    And I click continue on "RejectedGoods_Choose How Many Mrns Page"
    Then I am presented with the "Rejected Goods_Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "Rejected Goods_Multiple_Enter Movement Reference Number Page"
    And I click continue on "Rejected Goods_Multiple_Enter Movement Reference Number Page"
#    Then I am presented with the "Rejected Goods_Multiple_Enter Importer Eori Page"
#    When I enter "GB000000000000001" on "Rejected Goods_Multiple_Enter Importer Eori Page"
#    And I click continue on "Rejected Goods_Multiple_Enter Importer Eori Page"
#    Then I am presented with the "Rejected Goods_Multiple_Enter Declarant Eori Page"
#    When I enter "GB000000000000001" on "Rejected Goods_Multiple_Enter Declarant Eori Page"
#    And I click continue on "Rejected Goods_Multiple_Enter Declarant Eori Page"
    Then I am presented with the "Rejected Goods_Multiple_Check Declaration Details Page"
    And I select radio button "yes" on "Rejected Goods_Multiple_Check Declaration Details Page"
    And I click continue on "Rejected Goods_Multiple_Check Declaration Details Page"
    Then I am presented with the "Rejected Goods_Multiple_Enter Movement Reference Number 2 Page"
    When I enter "20AAAAAAAAAAAAAAA1" on "Rejected Goods_Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "Rejected Goods_Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "Rejected Goods_Multiple_Check Movement Reference Numbers Page"
    When I select radio button "No" on "Rejected Goods_Multiple_Check Movement Reference Numbers Page"
    And I click continue on "Rejected Goods_Multiple_Check Movement Reference Numbers Page"
    Then I am presented with the "Rejected Goods_Multiple_Claimant Details Page"
    And I click continue on "Rejected Goods_Multiple_Claimant Details Page"
    Then I am presented with the "Rejected Goods_Multiple_Choose Basis For Claim Page"
    When I select radio button "Special circumstances" on "Rejected Goods_Multiple_Choose Basis For Claim Page"
    And I click continue on "Rejected Goods_Multiple_Choose Basis For Claim Page"
    Then I am presented with the "Rejected Goods_Multiple_Enter Special Circumstances Page"
    When I enter "under 500 characters" on "Rejected Goods_Multiple_Enter Special Circumstances Page"
    And I click continue on "Rejected Goods_Multiple_Enter Special Circumstances Page"
    Then I am presented with the "Rejected Goods_Multiple_Choose Disposal Method Page"
    When I select radio button "Export" on "Rejected Goods_Multiple_Choose Disposal Method Page"
    And I click continue on "Rejected Goods_Multiple_Choose Disposal Method Page"
    Then I am presented with the "Rejected Goods_Multiple_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "Rejected Goods_Multiple_Enter Rejected Goods Details Page"
    And I click continue on "Rejected Goods_Multiple_Enter Rejected Goods Details Page"
    Then I am presented with the "Rejected Goods_Multiple_Select Duties 1 Page"
    When I select "A80,A95" on "Rejected Goods_Multiple_Select Duties 1 Page"
    And I click continue on "Rejected Goods_Multiple_Select Duties 1 Page"
    Then I am presented with the "Rejected Goods_Multiple_Select Duties 1 Duty Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "Rejected Goods_Multiple_Select Duties 1 Duty Page"
    And I click continue on "Rejected Goods_Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "Rejected Goods_Multiple_Select Duties 1 Duty Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "Rejected Goods_Multiple_Select Duties 1 Duty Page"
    And I click continue on "Rejected Goods_Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "Rejected Goods_Multiple_Select Duties 2 Page"
    When I select "A90,A85" on "Rejected Goods_Multiple_Select Duties 2 Page"
    And I click continue on "Rejected Goods_Multiple_Select Duties 2 Page"
    Then I am presented with the "Rejected Goods_Multiple_Select Duties 2 Duty Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "Rejected Goods_Multiple_Select Duties 2 Duty Page"
    And I click continue on "Rejected Goods_Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "Rejected Goods_Multiple_Select Duties 2 Duty Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "Rejected Goods_Multiple_Select Duties 2 Duty Page"
    And I click continue on "Rejected Goods_Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "Rejected Goods_Multiple_Check Claim Page"
    And I select radio button "yes" on "Rejected Goods_Multiple_Check Claim Page"
    When I click continue on "Rejected Goods_Multiple_Check Claim Page"
#    Then I am presented with the "Rejected Goods_Multiple_Check These Bank Details Are Correct Page"
#    When I click continue on "Rejected Goods_Multiple_Check These Bank Details Are Correct Page"
#    Then I am presented with the "Rejected Goods_Multiple_Supporting Evidence Upload Supporting Evidence Page"
#    When I upload a "document.pdf" file on "Rejected Goods_Multiple_Supporting Evidence Upload Supporting Evidence Page"
#    And I click continue on "Rejected Goods_Multiple_Supporting Evidence Upload Supporting Evidence Page"
#    And I click continue if I'm on "Rejected Goods_Multiple_Supporting Evidence Upload Progress Page"
#    When I select radio button "Commercial invoice" on "Rejected Goods_Multiple_Supporting Evidence Select Supporting Evidence Type Page"
#    And I click continue on "Rejected Goods_Multiple_Supporting Evidence Select Supporting Evidence Type Page"
#    Then I am presented with the "Rejected Goods_Multiple_Supporting Evidence Check Your Answers Page"
#    When I select radio button "No" on "Rejected Goods_Multiple_Supporting Evidence Check Your Answers Page"
#    And I click continue on "Rejected Goods_Multiple_Supporting Evidence Check Your Answers Page"
#    Then I am presented with the "Rejected Goods_Multiple_Check Answers Accept Send Page"
#    And I click continue on "Rejected Goods_Multiple_Check Answers Accept Send Page"
#    Then I am presented with the "Rejected Goods_Multiple_Claim Submitted Page"