@Regression @Mrn

Feature: MRN Northern Ireland (bulk disabled, entry disabled)

  Background:
    Given the "Bulk Claim" feature is "disabled"
    Given the "Entry Number" feature is "disabled"
    Given the "Northern Ireland" feature is "enabled"

  @test @a11y @ZAP
  Scenario: happy path (mrn ni) - duplicate mrn
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Single_Enter Movement Reference Number Page" and content "bulk-disabled,entry-disabled"
    When I enter "10AAAAAAAAAAAAAAA1" on "Single_Enter Movement Reference Number Page"
    And I click continue on "Single_Enter Movement Reference Number Page"
    Then I am presented with the "Single_Check Declaration Details Page" and content "10AAAAAAAAAAAAAAA1"
    And I select radio button "yes" on "Single_Check Declaration Details Page"
    And I click continue on "Single_Check Declaration Details Page"
    Then I am presented with the "Single_Who Is The Declarant Page"
    When I select radio button "I am a private individual importer" on "Single_Who Is The Declarant Page"
    And I click continue on "Single_Who Is The Declarant Page"
    Then I am presented with the "Single_Claimant Details Check Page"
    When I select radio button "yes" on "Single_Claimant Details Check Page"
    And I click continue on "Single_Claimant Details Check Page"
    Then I am presented with the "Single_Claim Northern Ireland Page"
    And I select radio button "yes" on "Single_Claim Northern Ireland Page"
    And I click continue on "Single_Claim Northern Ireland Page"
    Then I am presented with the "Single_Choose Basis For Claim Page" and content "ni"
    When I select radio button "Duplicate MRN" on "Single_Choose Basis For Claim Page"
    And I click continue on "Single_Choose Basis For Claim Page"
    Then I am presented with the "Single_Enter Duplicate Movement Reference Number Page"
    When I enter "20AAAAAAAAAAAAAAA1" on "Single_Enter Duplicate Movement Reference Number Page"
    And I click continue on "Single_Enter Duplicate Movement Reference Number Page"
    Then I am presented with the "Single_Check Duplicate Declaration Details Page" and content "20AAAAAAAAAAAAAAA1"
    And I select radio button "yes" on "Single_Check Duplicate Declaration Details Page"
    And I click continue on "Single_Check Duplicate Declaration Details Page"
    Then I am presented with the "Single_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Single_Enter Commodity Details Page"
    And I click continue on "Single_Enter Commodity Details Page"
    Then I am presented with the "Single_Select Duties Page"
    When I select "A80,A95,A90,A85" on "Single_Select Duties Page"
    And I click continue on "Single_Select Duties Page"
    Then I am presented with the "Single_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty" and content "£218.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Enter Claim Page" "A95 - Provisional Countervailing Duty" and content "£211.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Enter Claim Page" "A90 - Definitive Countervailing Duty" and content "£228.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty" and content "£171.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Check Claim Page"
    And I select radio button "yes" on "Single_Check Claim Page"
    When I click continue on "Single_Check Claim Page"
    Then I am presented with the "Single_Check These Bank Details Are Correct Page"
    When I click continue on "Single_Check These Bank Details Are Correct Page"
    Then I am presented with the "Single_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Single_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Single_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Single_Supporting Evidence Scan Progress Page"
    When I select radio button "Commercial invoice" on "Single_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Single_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Single_Supporting Evidence Check Your Answers Page"
    When I select radio button "No" on "Single_Supporting Evidence Check Your Answers Page"
    And I click continue on "Single_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Single_Check Answers Accept Send Page"
    And I click continue on "Single_Check Answers Accept Send Page"
    Then I am presented with the "Single_Claim Submitted Page" and content "£40.00"

  @test
  Scenario: happy path (mrn ni) - excise duty selected
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000002" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000002,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Single_Enter Movement Reference Number Page" and content "bulk-disabled,entry-disabled"
    When I enter "10AAAAAAAAAAAAAAA3" on "Single_Enter Movement Reference Number Page"
    And I click continue on "Single_Enter Movement Reference Number Page"
    Then I am presented with the "Single_Check Declaration Details Page" and content "10AAAAAAAAAAAAAAA3"
    And I select radio button "yes" on "Single_Check Declaration Details Page"
    And I click continue on "Single_Check Declaration Details Page"
    Then I am presented with the "Single_Who Is The Declarant Page"
    When I select radio button "I am a private individual importer" on "Single_Who Is The Declarant Page"
    And I click continue on "Single_Who Is The Declarant Page"
    Then I am presented with the "Single_Claimant Details Check Page"
    When I select radio button "yes" on "Single_Claimant Details Check Page"
    And I click continue on "Single_Claimant Details Check Page"
    Then I am presented with the "Single_Claim Northern Ireland Page"
    And I select radio button "yes" on "Single_Claim Northern Ireland Page"
    And I click continue on "Single_Claim Northern Ireland Page"
    Then I am presented with the "Single_Choose Basis For Claim Page" and content "10AAAAAAAAAAAAAAA3"
    When I select radio button "Incorrect excise value - Northern Ireland claims only" on "Single_Choose Basis For Claim Page"
    And I click continue on "Single_Choose Basis For Claim Page"
    Then I am presented with the "Single_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Single_Enter Commodity Details Page"
    And I click continue on "Single_Enter Commodity Details Page"
    Then I am presented with the "Single_Select Duties Page" and content "10AAAAAAAAAAAAAAA3 - excise"
    When I select "421,623,99C" on "Single_Select Duties Page"
    And I click continue on "Single_Select Duties Page"
    Then I am presented with the "Single_Enter Claim Page" "421 - Made-wine (sparkling), exceeding 8.5% vol. but not exceeding 15% vol." and content "£211.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Enter Claim Page" "623 - Smoking tobacco – other" and content "£228.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Enter Claim Page" "99C - Gas supplied by a gas utility or any gas supplied in a gaseous state that is of a kind supplied by a gas utility Great Britain" and content "£171.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Check Claim Page" and content "excise"
    And I select radio button "yes" on "Single_Check Claim Page"
    When I click continue on "Single_Check Claim Page"
    Then I am presented with the "Single_Check These Bank Details Are Correct Page"
    When I click continue on "Single_Check These Bank Details Are Correct Page"
    Then I am presented with the "Single_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Single_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Single_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Single_Supporting Evidence Scan Progress Page"
    Then I am presented with the "Single_Supporting Evidence Select Supporting Evidence Type Page"
    When I select radio button "Commercial invoice" on "Single_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Single_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Single_Supporting Evidence Check Your Answers Page"
    When I select radio button "No" on "Single_Supporting Evidence Check Your Answers Page"
    And I click continue on "Single_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Single_Check Answers Accept Send Page"
    And I click continue on "Single_Check Answers Accept Send Page"
    Then I am presented with the "Single_Claim Submitted Page" and content "£30.00"

  @test
  Scenario: happy path (mrn ni) - excise journey but excise not selected
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000002" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000002,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Single_Enter Movement Reference Number Page" and content "bulk-disabled,entry-disabled"
    When I enter "10AAAAAAAAAAAAAAA3" on "Single_Enter Movement Reference Number Page"
    And I click continue on "Single_Enter Movement Reference Number Page"
    Then I am presented with the "Single_Check Declaration Details Page" and content "10AAAAAAAAAAAAAAA3"
    And I select radio button "yes" on "Single_Check Declaration Details Page"
    And I click continue on "Single_Check Declaration Details Page"
    Then I am presented with the "Single_Who Is The Declarant Page"
    When I select radio button "I am a private individual importer" on "Single_Who Is The Declarant Page"
    And I click continue on "Single_Who Is The Declarant Page"
    Then I am presented with the "Single_Claimant Details Check Page"
    When I select radio button "yes" on "Single_Claimant Details Check Page"
    And I click continue on "Single_Claimant Details Check Page"
    Then I am presented with the "Single_Claim Northern Ireland Page"
    And I select radio button "yes" on "Single_Claim Northern Ireland Page"
    And I click continue on "Single_Claim Northern Ireland Page"
    Then I am presented with the "Single_Choose Basis For Claim Page" and content "10AAAAAAAAAAAAAAA3"
    When I select radio button "RGR" on "Single_Choose Basis For Claim Page"
    And I click continue on "Single_Choose Basis For Claim Page"
    Then I am presented with the "Single_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Single_Enter Commodity Details Page"
    And I click continue on "Single_Enter Commodity Details Page"
    Then I am presented with the "Single_Select Duties Page" and content "10AAAAAAAAAAAAAAA3"
    When I select "A80,421,623,99C" on "Single_Select Duties Page"
    And I click continue on "Single_Select Duties Page"
    Then I am presented with the "Single_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty" and content "£218.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Enter Claim Page" "421 - Made-wine (sparkling), exceeding 8.5% vol. but not exceeding 15% vol." and content "£211.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Enter Claim Page" "623 - Smoking tobacco – other" and content "£228.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Enter Claim Page" "99C - Gas supplied by a gas utility or any gas supplied in a gaseous state that is of a kind supplied by a gas utility Great Britain" and content "£171.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Check Claim Page" and content "10AAAAAAAAAAAAAAA3"
    And I select radio button "yes" on "Single_Check Claim Page"
    When I click continue on "Single_Check Claim Page"
    Then I am presented with the "Single_Check These Bank Details Are Correct Page"
    When I click continue on "Single_Check These Bank Details Are Correct Page"
    Then I am presented with the "Single_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Single_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Single_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Single_Supporting Evidence Scan Progress Page"
    When I select radio button "Commercial invoice" on "Single_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Single_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Single_Supporting Evidence Check Your Answers Page"
    When I select radio button "No" on "Single_Supporting Evidence Check Your Answers Page"
    And I click continue on "Single_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Single_Check Answers Accept Send Page"
    And I click continue on "Single_Check Answers Accept Send Page"
    Then I am presented with the "Single_Claim Submitted Page" and content "£40.00"

  @test @a11y @ZAP
  Scenario: happy path (mrn ni) - duplicate mrn - not ni
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Single_Enter Movement Reference Number Page" and content "bulk-disabled,entry-disabled"
    When I enter "10AAAAAAAAAAAAAAA1" on "Single_Enter Movement Reference Number Page"
    And I click continue on "Single_Enter Movement Reference Number Page"
    Then I am presented with the "Single_Check Declaration Details Page" and content "10AAAAAAAAAAAAAAA1"
    And I select radio button "yes" on "Single_Check Declaration Details Page"
    And I click continue on "Single_Check Declaration Details Page"
    Then I am presented with the "Single_Who Is The Declarant Page"
    When I select radio button "I am a private individual importer" on "Single_Who Is The Declarant Page"
    And I click continue on "Single_Who Is The Declarant Page"
    Then I am presented with the "Single_Claimant Details Check Page"
    When I select radio button "yes" on "Single_Claimant Details Check Page"
    And I click continue on "Single_Claimant Details Check Page"
    Then I am presented with the "Single_Claim Northern Ireland Page"
    And I select radio button "no" on "Single_Claim Northern Ireland Page"
    And I click continue on "Single_Claim Northern Ireland Page"
    Then I am presented with the "Single_Choose Basis For Claim Page"
    When I select radio button "Duplicate MRN" on "Single_Choose Basis For Claim Page"
    And I click continue on "Single_Choose Basis For Claim Page"
    Then I am presented with the "Single_Enter Duplicate Movement Reference Number Page"
    When I enter "20AAAAAAAAAAAAAAA1" on "Single_Enter Duplicate Movement Reference Number Page"
    And I click continue on "Single_Enter Duplicate Movement Reference Number Page"
    Then I am presented with the "Single_Check Duplicate Declaration Details Page" and content "20AAAAAAAAAAAAAAA1"
    And I select radio button "yes" on "Single_Check Duplicate Declaration Details Page"
    And I click continue on "Single_Check Duplicate Declaration Details Page"
    Then I am presented with the "Single_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Single_Enter Commodity Details Page"
    And I click continue on "Single_Enter Commodity Details Page"
    Then I am presented with the "Single_Select Duties Page"
    When I select "A80,A95,A90,A85" on "Single_Select Duties Page"
    And I click continue on "Single_Select Duties Page"
    Then I am presented with the "Single_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty" and content "£218.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Enter Claim Page" "A95 - Provisional Countervailing Duty" and content "£211.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Enter Claim Page" "A90 - Definitive Countervailing Duty" and content "£228.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty" and content "£171.00"
    When I enter "10" on "Single_Enter Claim Page"
    And I click continue on "Single_Enter Claim Page"
    Then I am presented with the "Single_Check Claim Page"
    And I select radio button "yes" on "Single_Check Claim Page"
    When I click continue on "Single_Check Claim Page"
    Then I am presented with the "Single_Check These Bank Details Are Correct Page"
    When I click continue on "Single_Check These Bank Details Are Correct Page"
    Then I am presented with the "Single_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Single_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Single_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Single_Supporting Evidence Scan Progress Page"
    When I select radio button "Commercial invoice" on "Single_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Single_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Single_Supporting Evidence Check Your Answers Page"
    When I select radio button "No" on "Single_Supporting Evidence Check Your Answers Page"
    And I click continue on "Single_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Single_Check Answers Accept Send Page"
    And I click continue on "Single_Check Answers Accept Send Page"
    Then I am presented with the "Single_Claim Submitted Page" and content "£40.00"