@Regression @Mrn

Feature: MRN (bulk disabled, entry disabled)

  Background:
    Given the "Bulk Claim" feature is "disabled"
    Given the "Entry Number" feature is "disabled"
    Given the "Northern Ireland" feature is "disabled"

  @test @a11y @ZAP
  Scenario: happy path (mrn) - duplicate mrn
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Enter Movement Reference Number Page" and content "bulk-disabled,entry-disabled"
    When I enter "10AAAAAAAAAAAAAAA1" on "Enter Movement Reference Number Page"
    And I click continue on "Enter Movement Reference Number Page"
    Then I am presented with the "Mrn_Check Declaration Details Page" and content "10AAAAAAAAAAAAAAA1"
    And I select radio button "yes" on "Mrn_Check Declaration Details Page"
    And I click continue on "Mrn_Check Declaration Details Page"
    Then I am presented with the "Mrn_Who Is The Declarant Page"
    When I select radio button "0" on "Mrn_Who Is The Declarant Page"
    And I click continue on "Mrn_Who Is The Declarant Page"
    Then I am presented with the "Mrn_Claimant Details Page"
    When I select radio button "yes" on "Mrn_Claimant Details Page"
    And I click continue on "Mrn_Claimant Details Page"
    Then I am presented with the "Mrn_Choose Basis For Claim Page"
    When I select radio button "Duplicate MRN" on "Mrn_Choose Basis For Claim Page"
    And I click continue on "Mrn_Choose Basis For Claim Page"
    Then I am presented with the "Mrn_Enter Duplicate Movement Reference Number Page"
    When I enter "20AAAAAAAAAAAAAAA1" on "Mrn_Enter Duplicate Movement Reference Number Page"
    And I click continue on "Mrn_Enter Duplicate Movement Reference Number Page"
    Then I am presented with the "Mrn_Check Duplicate Declaration Details Page" and content "20AAAAAAAAAAAAAAA1"
    And I select radio button "yes" on "Mrn_Check Duplicate Declaration Details Page"
    And I click continue on "Mrn_Check Duplicate Declaration Details Page"
    Then I am presented with the "Mrn_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Mrn_Enter Commodity Details Page"
    And I click continue on "Mrn_Enter Commodity Details Page"
    Then I am presented with the "Mrn_Select Duties Page"
    When I select "A80,A95,A90,A85" on "Mrn_Select Duties Page"
    And I click continue on "Mrn_Select Duties Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty" and content "£218.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A95 - Provisional Countervailing Duty" and content "£211.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A90 - Definitive Countervailing Duty" and content "£228.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty" and content "£171.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Check Claim Page"
    And I select radio button "yes" on "Mrn_Check Claim Page"
    When I click continue on "Mrn_Check Claim Page"
    Then I am presented with the "Mrn_Check These Bank Details Are Correct Page"
    When I click continue on "Mrn_Check These Bank Details Are Correct Page"
    Then I am presented with the "Mrn_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Mrn_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Mrn_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Mrn_Supporting Evidence Scan Progress Page"
    Then I am presented with the "Mrn_Supporting Evidence Select Supporting Evidence Type Page"
    When I select radio button "Commercial Invoice" on "Mrn_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Mrn_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Mrn_Supporting Evidence Check Your Answers Page"
    When I select radio button "No" on "Mrn_Supporting Evidence Check Your Answers Page"
    And I click continue on "Mrn_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Mrn_Check Answers Accept Send Page" and content "check content"
    And I click continue on "Mrn_Check Answers Accept Send Page"
    Then I am presented with the "Mrn_Claim Submitted Page" and content "£40.00"

  @test
  Scenario: wrong mrn
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Enter Movement Reference Number Page" and content "bulk-disabled,entry-disabled"
    When I enter "10AAAAAAAAAAAAAAA1" on "Enter Movement Reference Number Page"
    And I click continue on "Enter Movement Reference Number Page"
    Then I am presented with the "Mrn_Check Declaration Details Page" and content "10AAAAAAAAAAAAAAA1"
    And I select radio button "no" on "Mrn_Check Declaration Details Page"
    And I click continue on "Mrn_Check Declaration Details Page"
    Then I am presented with the "Enter Movement Reference Number Page" and content "bulk-disabled,entry-disabled"
    When I enter "10AAAAAAAAAAAAAAA1" on "Enter Movement Reference Number Page"
    And I click continue on "Enter Movement Reference Number Page"
    Then I am presented with the "Mrn_Check Declaration Details Page" and content "10AAAAAAAAAAAAAAA1"
    And I select radio button "yes" on "Mrn_Check Declaration Details Page"
    And I click continue on "Mrn_Check Declaration Details Page"
    Then I am presented with the "Mrn_Who Is The Declarant Page"

  @test
  Scenario: attempt entry journey
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Enter Movement Reference Number Page" and content "bulk-disabled,entry-disabled"
    When I enter "123456789A12345678" on "Enter Movement Reference Number Page"
    And I click continue on "Enter Movement Reference Number Page"
    Then I am presented with the "Enter Movement Reference Number Page" error page
