@Regression @Individual @MRN

Feature: C285 - MRN - importer-company

  Background:
    Given the "Bulk Claim" feature is "disabled"
    Given the "Northern Ireland" feature is "disabled"

  @testOld
  Scenario: User is a CDS Trader - happy path (mrn) - duplicate mrn
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "Enter Movement Reference Number Page"
    And I click continue on "Enter Movement Reference Number Page"
    Then I am presented with the "Mrn_Check Declaration Details Page"
    And I click continue on "Mrn_Check Declaration Details Page"
    Then I am presented with the "Mrn_Who Is The Declarant Page"
    When I select radio button "1" on "Mrn_Who Is The Declarant Page"
    And I click continue on "Mrn_Who Is The Declarant Page"
    Then I am presented with the "Mrn_Enter Your Details As Registered With CDS Page"
    When I enter "" on "Mrn_Enter Your Details As Registered With CDS Page"
    Then I am presented with the "Mrn_Choose Basis For Claim Page"
    When I select radio button "Duplicate Entry" on "Mrn_Choose Basis For Claim Page"
    And I click continue on "Mrn_Choose Basis For Claim Page"
    Then I am presented with the "Mrn_Enter Duplicate Movement Reference Number Page"
    When I enter "20AAAAAAAAAAAAAAA1" on "Mrn_Enter Duplicate Movement Reference Number Page"
    And I click continue on "Mrn_Enter Duplicate Movement Reference Number Page"
    Then I am presented with the "Mrn_Check Duplicate Declaration Details Page"
    And I click continue on "Mrn_Check Duplicate Declaration Details Page"
    Then I am presented with the "Mrn_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Mrn_Enter Commodity Details Page"
    And I click continue on "Mrn_Enter Commodity Details Page"
    Then I am presented with the "Mrn_Select Duties Page"
    When I select "A80,A95,A90,A85" on "Mrn_Select Duties Page"
    And I click continue on "Mrn_Select Duties Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Check Claim Page"
    And I select radio button "yes" on "Mrn_Check Claim Page"
    When I click continue on "Mrn_Check Claim Page"
    Then I am presented with the "Mrn_Check These Bank Details Are Correct Page"
    When I click continue on "Mrn_Check These Bank Details Are Correct Page"
    Then I am presented with the "Mrn_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Mrn_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Mrn_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Mrn_Supporting Evidence Scan Progress Page"
    When I select dropdown value "Commercial Invoice" on "Mrn_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Mrn_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Mrn_Supporting Evidence Check Your Answers Page"
    When I click continue on "Mrn_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Mrn_Check Answers Accept Send Page"
    And I click continue on "Mrn_Check Answers Accept Send Page"
    Then I am presented with the "Mrn_Claim Submitted Page"

  @testOld @a11y @ZAP
  Scenario: User is a CDS Trader - happy path (mrn - enter importer and declarant EORIs)
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Enter Movement Reference Number Page"
    When I enter "10ABCDEFGHIJKLMNO0" on "Enter Movement Reference Number Page"
    And I click continue on "Enter Movement Reference Number Page"
    Then I am presented with the "Mrn_Importer Eori Entry Page"
    When I enter "GB123456789012345" on "Mrn_Importer Eori Entry Page"
    And I click continue on "Mrn_Importer Eori Entry Page"
    Then I am presented with the "Mrn_Declarant Eori Entry Page"
    When I enter "GB123456789012345" on "Mrn_Declarant Eori Entry Page"
    And I click continue on "Mrn_Declarant Eori Entry Page"
    Then I am presented with the "Mrn_Check Declaration Details Page"
    And I click continue on "Mrn_Check Declaration Details Page"
    Then I am presented with the "Mrn_Who Is The Declarant Page"
    When I select radio button "1" on "Mrn_Who Is The Declarant Page"
    And I click continue on "Mrn_Who Is The Declarant Page"
    Then I am presented with the "Mrn_Enter Your Details As Registered With CDS Page"
    When I enter "" on "Mrn_Enter Your Details As Registered With CDS Page"
    Then I am presented with the "Mrn_Choose Basis For Claim Page"
    When I select radio button "Incorrect EORI & Deferment Acc. Num." on "Mrn_Choose Basis For Claim Page"
    And I click continue on "Mrn_Choose Basis For Claim Page"
    Then I am presented with the "Mrn_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Mrn_Enter Commodity Details Page"
    And I click continue on "Mrn_Enter Commodity Details Page"
    Then I am presented with the "Mrn_Select Duties Page"
    When I select "A80,A95,A90,A85" on "Mrn_Select Duties Page"
    And I click continue on "Mrn_Select Duties Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Check Claim Page"
    And I select radio button "yes" on "Mrn_Check Claim Page"
    When I click continue on "Mrn_Check Claim Page"
    Then I am presented with the "Mrn_Check These Bank Details Are Correct Page"
    When I click continue on "Mrn_Check These Bank Details Are Correct Page"
    Then I am presented with the "Mrn_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Mrn_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Mrn_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Mrn_Supporting Evidence Scan Progress Page"
    When I select dropdown value "Commercial Invoice" on "Mrn_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Mrn_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Mrn_Supporting Evidence Check Your Answers Page"
    When I click continue on "Mrn_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Mrn_Check Answers Accept Send Page"
    And I click continue on "Mrn_Check Answers Accept Send Page"
    Then I am presented with the "Mrn_Claim Submitted Page"
