Feature: temp file for C&E1179

  Background:
    Given the "Bulk Claim" feature is "enabled"
    Given the "Entry Number" feature is "disabled"
    Given the "Northern Ireland" feature is "enabled"
    Given the "Rejected Goods" feature is "enabled"

  @test @a11y @ZAP
  Scenario: run before other journeys to get file upload to work
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "RejectedGoods_Choose How Many Mrns Page"
    And I select radio button "Enter one MRN" on "RejectedGoods_Choose How Many Mrns Page"
    And I click continue on "RejectedGoods_Choose How Many Mrns Page"
    Then I am presented with the "Rejected Goods_Single_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA2" on "Rejected Goods_Single_Enter Movement Reference Number Page"
    And I click continue on "Rejected Goods_Single_Enter Movement Reference Number Page"
    Then I am presented with the "Rejected Goods_Single_Enter Importer Eori Page"
    When I enter "GB000000000000002" on "Rejected Goods_Single_Enter Importer Eori Page"
    And I click continue on "Rejected Goods_Single_Enter Importer Eori Page"
    Then I am presented with the "Rejected Goods_Single_Enter Declarant Eori Page"
    When I enter "GB000000000000002" on "Rejected Goods_Single_Enter Declarant Eori Page"
    And I click continue on "Rejected Goods_Single_Enter Declarant Eori Page"
    Then I am presented with the "Rejected Goods_Single_Check Declaration Details Page"
    When I select radio button "yes" on "Rejected Goods_Single_Check Declaration Details Page"
    And I click continue on "Rejected Goods_Single_Check Declaration Details Page"
    Then I am presented with the "Rejected Goods_Single_Claimant Details Page"
    And I click continue on "Rejected Goods_Single_Claimant Details Page"
    Then I am presented with the "Rejected Goods_Single_Choose Basis For Claim Page"
    When I select radio button "Not in accordance with contract" on "Rejected Goods_Single_Choose Basis For Claim Page"
    And I click continue on "Rejected Goods_Single_Choose Basis For Claim Page"
    Then I am presented with the "Rejected Goods_Single_Choose Disposal Method Page"
    When I select radio button "Export" on "Rejected Goods_Single_Choose Disposal Method Page"
    And I click continue on "Rejected Goods_Single_Choose Disposal Method Page"
    Then I am presented with the "Rejected Goods_Single_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "Rejected Goods_Single_Enter Rejected Goods Details Page"
    And I click continue on "Rejected Goods_Single_Enter Rejected Goods Details Page"
    Then I am presented with the "Rejected Goods_Single_Select Duties Page"
    When I select "A80,A95,A90,A85" on "Rejected Goods_Single_Select Duties Page"
    And I click continue on "Rejected Goods_Single_Select Duties Page"
    Then I am presented with the "Rejected Goods_Single_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "Rejected Goods_Single_Enter Claim Page"
    And I click continue on "Rejected Goods_Single_Enter Claim Page"
    Then I am presented with the "Rejected Goods_Single_Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "Rejected Goods_Single_Enter Claim Page"
    And I click continue on "Rejected Goods_Single_Enter Claim Page"
    Then I am presented with the "Rejected Goods_Single_Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "Rejected Goods_Single_Enter Claim Page"
    And I click continue on "Rejected Goods_Single_Enter Claim Page"
    Then I am presented with the "Rejected Goods_Single_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "Rejected Goods_Single_Enter Claim Page"
    And I click continue on "Rejected Goods_Single_Enter Claim Page"
    Then I am presented with the "Rejected Goods_Single_Check Claim Page"
    When I select radio button "yes" on "Rejected Goods_Single_Check Claim Page"
    And I click continue on "Rejected Goods_Single_Check Claim Page"
    Then I am presented with the "Rejected Goods_Single_Enter Inspection Date Page"
    When I enter "10,10,2020" on "Rejected Goods_Single_Enter Inspection Date Page"
    And I click continue on "Rejected Goods_Single_Enter Inspection Date Page"
    Then I am presented with the "Rejected Goods_Single_Inspection Address Choose Type Page"
    When I select radio button "11 Mount Road, London, E10 7PP" on "Rejected Goods_Single_Inspection Address Choose Type Page"
    And I click continue on "Rejected Goods_Single_Inspection Address Choose Type Page"
    Then I am presented with the "Rejected Goods_Single_Check Bank Details Page"
    When I click continue on "Rejected Goods_Single_Check Bank Details Page"
    Then I am presented with the "Rejected Goods_Single_Choose File Type Page"
    When I select radio button "Commercial invoice" on "Rejected Goods_Single_Choose File Type Page"
    And I click continue on "Rejected Goods_Single_Choose File Type Page"

  @test @a11y @ZAP
  Scenario: happy path
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "RejectedGoods_Choose How Many Mrns Page"
    And I select radio button "Enter one MRN" on "RejectedGoods_Choose How Many Mrns Page"
    And I click continue on "RejectedGoods_Choose How Many Mrns Page"
    Then I am presented with the "Rejected Goods_Single_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA2" on "Rejected Goods_Single_Enter Movement Reference Number Page"
    And I click continue on "Rejected Goods_Single_Enter Movement Reference Number Page"
    Then I am presented with the "Rejected Goods_Single_Enter Importer Eori Page"
    When I enter "GB000000000000002" on "Rejected Goods_Single_Enter Importer Eori Page"
    And I click continue on "Rejected Goods_Single_Enter Importer Eori Page"
    Then I am presented with the "Rejected Goods_Single_Enter Declarant Eori Page"
    When I enter "GB000000000000002" on "Rejected Goods_Single_Enter Declarant Eori Page"
    And I click continue on "Rejected Goods_Single_Enter Declarant Eori Page"
    Then I am presented with the "Rejected Goods_Single_Check Declaration Details Page"
    When I select radio button "yes" on "Rejected Goods_Single_Check Declaration Details Page"
    And I click continue on "Rejected Goods_Single_Check Declaration Details Page"
    Then I am presented with the "Rejected Goods_Single_Claimant Details Page"
    And I click continue on "Rejected Goods_Single_Claimant Details Page"
    Then I am presented with the "Rejected Goods_Single_Choose Basis For Claim Page"
    When I select radio button "Not in accordance with contract" on "Rejected Goods_Single_Choose Basis For Claim Page"
    And I click continue on "Rejected Goods_Single_Choose Basis For Claim Page"
    Then I am presented with the "Rejected Goods_Single_Choose Disposal Method Page"
    When I select radio button "Export" on "Rejected Goods_Single_Choose Disposal Method Page"
    And I click continue on "Rejected Goods_Single_Choose Disposal Method Page"
    Then I am presented with the "Rejected Goods_Single_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "Rejected Goods_Single_Enter Rejected Goods Details Page"
    And I click continue on "Rejected Goods_Single_Enter Rejected Goods Details Page"
    Then I am presented with the "Rejected Goods_Single_Select Duties Page"
    When I select "A80,A95,A90,A85" on "Rejected Goods_Single_Select Duties Page"
    And I click continue on "Rejected Goods_Single_Select Duties Page"
    Then I am presented with the "Rejected Goods_Single_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "Rejected Goods_Single_Enter Claim Page"
    And I click continue on "Rejected Goods_Single_Enter Claim Page"
    Then I am presented with the "Rejected Goods_Single_Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "Rejected Goods_Single_Enter Claim Page"
    And I click continue on "Rejected Goods_Single_Enter Claim Page"
    Then I am presented with the "Rejected Goods_Single_Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "Rejected Goods_Single_Enter Claim Page"
    And I click continue on "Rejected Goods_Single_Enter Claim Page"
    Then I am presented with the "Rejected Goods_Single_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "Rejected Goods_Single_Enter Claim Page"
    And I click continue on "Rejected Goods_Single_Enter Claim Page"
    Then I am presented with the "Rejected Goods_Single_Check Claim Page"
    When I select radio button "yes" on "Rejected Goods_Single_Check Claim Page"
    And I click continue on "Rejected Goods_Single_Check Claim Page"
    Then I am presented with the "Rejected Goods_Single_Enter Inspection Date Page"
    When I enter "10,10,2020" on "Rejected Goods_Single_Enter Inspection Date Page"
    And I click continue on "Rejected Goods_Single_Enter Inspection Date Page"
    Then I am presented with the "Rejected Goods_Single_Inspection Address Choose Type Page"
    When I select radio button "11 Mount Road, London, E10 7PP" on "Rejected Goods_Single_Inspection Address Choose Type Page"
    And I click continue on "Rejected Goods_Single_Inspection Address Choose Type Page"
    Then I am presented with the "Rejected Goods_Single_Check Bank Details Page"
    When I click continue on "Rejected Goods_Single_Check Bank Details Page"
    Then I am presented with the "Rejected Goods_Single_Choose File Type Page"
    When I select radio button "Commercial invoice" on "Rejected Goods_Single_Choose File Type Page"
    And I click continue on "Rejected Goods_Single_Choose File Type Page"
    Then I am presented with the "Upload Documents_Choose Files Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "Upload Documents_Choose Files Page"
    And I select radio button "Yes" on "Upload Documents_Choose Files Page"
    And I click continue on "Upload Documents_Choose Files Page"
    Then I am presented with the "Rejected Goods_Single_Choose File Type Page"
    When I select radio button "Import and export declaration" on "Rejected Goods_Single_Choose File Type Page"
    And I click continue on "Rejected Goods_Single_Choose File Type Page"
    Then I am presented with the "Upload Documents_Choose Files Page" "import and export declaration"
    When I upload a 2 "image.jpg" file on "Upload Documents_Choose Files Page"
    And I select radio button "No" on "Upload Documents_Choose Files Page"
    And I click continue on "Upload Documents_Choose Files Page"
    Then I am presented with the "Rejected Goods_Single_Check Your Answers Page"
    And I click continue on "Rejected Goods_Single_Check Your Answers Page"
    Then I am presented with the "Rejected Goods_Single_Claim Submitted Page"

  @test @a11y @ZAP
  Scenario: happy path - Special circumstances and CMA eligible
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "RejectedGoods_Choose How Many Mrns Page"
    And I select radio button "Enter one MRN" on "RejectedGoods_Choose How Many Mrns Page"
    And I click continue on "RejectedGoods_Choose How Many Mrns Page"
    Then I am presented with the "Rejected Goods_Single_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA2" on "Rejected Goods_Single_Enter Movement Reference Number Page"
    And I click continue on "Rejected Goods_Single_Enter Movement Reference Number Page"
    Then I am presented with the "Rejected Goods_Single_Enter Importer Eori Page"
    When I enter "GB000000000000002" on "Rejected Goods_Single_Enter Importer Eori Page"
    And I click continue on "Rejected Goods_Single_Enter Importer Eori Page"
    Then I am presented with the "Rejected Goods_Single_Enter Declarant Eori Page"
    When I enter "GB000000000000002" on "Rejected Goods_Single_Enter Declarant Eori Page"
    And I click continue on "Rejected Goods_Single_Enter Declarant Eori Page"
    Then I am presented with the "Rejected Goods_Single_Check Declaration Details Page"
    When I select radio button "yes" on "Rejected Goods_Single_Check Declaration Details Page"
    And I click continue on "Rejected Goods_Single_Check Declaration Details Page"
    Then I am presented with the "Rejected Goods_Single_Claimant Details Page"
    And I click continue on "Rejected Goods_Single_Claimant Details Page"
    Then I am presented with the "Rejected Goods_Single_Choose Basis For Claim Page"
    When I select radio button "Special circumstances" on "Rejected Goods_Single_Choose Basis For Claim Page"
    And I click continue on "Rejected Goods_Single_Choose Basis For Claim Page"
    Then I am presented with the "Rejected Goods_Single_Enter Special Circumstances Page"
    When I enter "under 500 characters" on "Rejected Goods_Single_Enter Special Circumstances Page"
    And I click continue on "Rejected Goods_Single_Enter Special Circumstances Page"
    Then I am presented with the "Rejected Goods_Single_Choose Disposal Method Page"
    When I select radio button "Export" on "Rejected Goods_Single_Choose Disposal Method Page"
    And I click continue on "Rejected Goods_Single_Choose Disposal Method Page"
    Then I am presented with the "Rejected Goods_Single_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "Rejected Goods_Single_Enter Rejected Goods Details Page"
    And I click continue on "Rejected Goods_Single_Enter Rejected Goods Details Page"
    Then I am presented with the "Rejected Goods_Single_Select Duties Page"
    When I select "A95,A90,A85" on "Rejected Goods_Single_Select Duties Page"
    And I click continue on "Rejected Goods_Single_Select Duties Page"
    Then I am presented with the "Rejected Goods_Single_Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "Rejected Goods_Single_Enter Claim Page"
    And I click continue on "Rejected Goods_Single_Enter Claim Page"
    Then I am presented with the "Rejected Goods_Single_Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "Rejected Goods_Single_Enter Claim Page"
    And I click continue on "Rejected Goods_Single_Enter Claim Page"
    Then I am presented with the "Rejected Goods_Single_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "Rejected Goods_Single_Enter Claim Page"
    And I click continue on "Rejected Goods_Single_Enter Claim Page"
    Then I am presented with the "Rejected Goods_Single_Check Claim Page"
    And I select radio button "yes" on "Rejected Goods_Single_Check Claim Page"
    When I click continue on "Rejected Goods_Single_Check Claim Page"
    Then I am presented with the "Rejected Goods_Single_Enter Inspection Date Page"
    When I enter "10,10,2020" on "Rejected Goods_Single_Enter Inspection Date Page"
    And I click continue on "Rejected Goods_Single_Enter Inspection Date Page"
    Then I am presented with the "Rejected Goods_Single_Inspection Address Choose Type Page"
    When I select radio button "11 Mount Road, London, E10 7PP" on "Rejected Goods_Single_Inspection Address Choose Type Page"
    And I click continue on "Rejected Goods_Single_Inspection Address Choose Type Page"
    Then I am presented with the "Rejected Goods_Single_Choose Repayment Method Page"
    When I select radio button "cma" on "Rejected Goods_Single_Choose Repayment Method Page"
    And I click continue on "Rejected Goods_Single_Choose Repayment Method Page"
    Then I am presented with the "Rejected Goods_Single_Choose File Type Page"
    When I select radio button "Commercial invoice" on "Rejected Goods_Single_Choose File Type Page"
    And I click continue on "Rejected Goods_Single_Choose File Type Page"
    Then I am presented with the "Upload Documents_Choose Files Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "Upload Documents_Choose Files Page"
    And I select radio button "Yes" on "Upload Documents_Choose Files Page"
    And I click continue on "Upload Documents_Choose Files Page"
    Then I am presented with the "Rejected Goods_Single_Choose File Type Page"
    When I select radio button "Import and export declaration" on "Rejected Goods_Single_Choose File Type Page"
    And I click continue on "Rejected Goods_Single_Choose File Type Page"
    Then I am presented with the "Upload Documents_Choose Files Page" "import and export declaration"
    When I upload a 2 "image.jpg" file on "Upload Documents_Choose Files Page"
    And I select radio button "No" on "Upload Documents_Choose Files Page"
    And I click continue on "Upload Documents_Choose Files Page"
    Then I am presented with the "Rejected Goods_Single_Check Your Answers Page"
    And I click continue on "Rejected Goods_Single_Check Your Answers Page"
    Then I am presented with the "Rejected Goods_Single_Claim Submitted Page"
