@C&E1179 @Scheduled
Feature: C&E1179 Scheduled

  @test @a11y @ZAP @wip
  Scenario: happy path - check importer/declarant eori pages, Special circumstances
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    And I select radio button "Upload a file with a list of MRNs" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Scheduled_Have Your Supporting Document Ready Page v2"
    When I clickContinue on "CE1179_Scheduled_Have Your Supporting Document Ready Page v2"
    Then I am presented with the "CE1179_Scheduled_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA2" on "CE1179_Scheduled_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Scheduled_Enter Movement Reference Number Page"
    Then I am presented with the "CE1179_Scheduled_Enter Importer Eori Page"
    When I enter "GB000000000000002" on "CE1179_Scheduled_Enter Importer Eori Page"
    And I click continue on "CE1179_Scheduled_Enter Importer Eori Page"
    Then I am presented with the "CE1179_Scheduled_Enter Declarant Eori Page"
    When I enter "GB000000000000002" on "CE1179_Scheduled_Enter Declarant Eori Page"
    And I click continue on "CE1179_Scheduled_Enter Declarant Eori Page"
    Then I am presented with the "CE1179_Scheduled_Check Declaration Details Page"
    #When I select radio button "Yes" on "CE1179_Scheduled_Check Declaration Details Page"
    And I click continue on "CE1179_Scheduled_Check Declaration Details Page"
    #New change CDSR-3829

    Then I am presented with the "UDF_Choose File Page"
    When I upload a 1 "image.jpg" file on "UDF_Choose File Page"
    And I click continue if I'm on "UDF_Choose File Page"
    Then I am presented with the "CE1179_Scheduled_Choose Basis For Claim Page"
    When I select radio button "Special circumstances" on "CE1179_Scheduled_Choose Basis For Claim Page"
    And I click continue on "CE1179_Scheduled_Choose Basis For Claim Page"
    Then I am presented with the "CE1179_Scheduled_Enter Special Circumstances Page"
    When I enter "under 500 characters" on "CE1179_Multiple_Enter Special Circumstances Page"
    And I click continue on "CE1179_Multiple_Enter Special Circumstances Page"
    Then I am presented with the "CE1179_Scheduled_Choose Disposal Method Page"
    When I select radio button "Return the goods by road, rail, air or ship" on "CE1179_Scheduled_Choose Disposal Method Page"
    And I click continue on "CE1179_Scheduled_Choose Disposal Method Page"
    Then I am presented with the "CE1179_Scheduled_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "CE1179_Scheduled_Enter Rejected Goods Details Page"
    And I click continue on "CE1179_Scheduled_Enter Rejected Goods Details Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Select Duty Types Page"
    #CDSR-3948
    When I select "uk-duty,eu-duty,excise-duty" on "CE1179_Scheduled_Select Duties Select Duty Types Page"
    And I click continue on "CE1179_Scheduled_Select Duties Select Duty Types Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Uk Duty Page"
    When I select "A00,B00" on "CE1179_Scheduled_Select Duties Uk Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties Uk Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "A00-Customs Duty"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "B00-Value Added Tax (VAT)"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Eu Duty Page"
    When I select "A50,B05" on "CE1179_Scheduled_Select Duties Eu Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties Eu Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "A50-Customs Duty"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "B05-Value Added Tax (VAT)"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Excise Duty Page v2"

    When I select "beer,wine,made-wine,miscellaneous-road-fuels,tobacco,climate-change-levy" on "C285_Scheduled_Select Duties Excise Duty Page v2"
    And I click continue on "CE1179_Scheduled_Select Duties Excise Duty Page v2"
    Then I am presented with the "CE1179_Scheduled_Select Duties Beer Page"
    When I select "407,447" on "CE1179_Scheduled_Select Duties Excise Duty Page v2"
    And I click continue on "CE1179_Scheduled_Select Duties Excise Duty Page v2"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Excise Duty-407 Beer"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Excise Duty-447 Beer"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"

    Then I am presented with the "CE1179_Scheduled_Select Duties Wine Page"
    When I select "411,415" on "CE1179_Scheduled_Select Duties Wine Page"
    And I click continue on "CE1179_Scheduled_Select Duties Wine Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Excise Duty-411 Wine"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Excise Duty-415 Wine"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"

    Then I am presented with the "CE1179_Scheduled_Select Duties Made Wine Page"
    When I select "421,429" on "CE1179_Scheduled_Select Duties Made Wine Page"
    And I click continue on "CE1179_Scheduled_Select Duties Made Wine Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Excise Duty-421 Made-wine"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
   Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Excise Duty-429 Made-wine"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"

    Then I am presented with the "CE1179_Scheduled_Select Duties Miscellaneous Road Fuels Page"
    When I select "591,592" on "CE1179_Scheduled_Select Duties Miscellaneous Road Fuels Page"
    And I click continue on "CE1179_Scheduled_Select Duties Miscellaneous Road Fuels Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Excise Duty-591 Miscellaneous road fuels"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Excise Duty-592 Miscellaneous road fuels"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"

    Then I am presented with the "CE1179_Scheduled_Select Duties Tobacco Page"
    When I select "611,633" on "CE1179_Scheduled_Select Duties Tobacco Page"
    And I click continue on "CE1179_Scheduled_Select Duties Tobacco Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Excise Duty-611 Tobacco products"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Excise Duty-633 Tobacco products"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"

    Then I am presented with the "CE1179_Scheduled_Select Duties Climate Change Levy Page"
    When I select "99A,99D" on "CE1179_Scheduled_Select Duties Climate Change Levy Page"
    And I click continue on "CE1179_Scheduled_Select Duties Climate Change Levy Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Excise Duty-99A Climate Change Levy"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
   And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Excise Duty-99D Climate Change Levy "
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"

    Then I am presented with the "CE1179_Scheduled_Check Claim Page"
    #When I select radio button "Yes" on "CE1179_Scheduled_Check Claim Page"
    And I click continue on "CE1179_Scheduled_Check Claim Page"
    Then I am presented with the "CE1179_Scheduled_Enter Inspection Date Page"
    When I enter "10,10,2020" on "CE1179_Scheduled_Enter Inspection Date Page"
    And I click continue on "CE1179_Scheduled_Enter Inspection Date Page"
    Then I am presented with the "CE1179_Scheduled_Inspection Address Choose Type Page"
    When I select radio button "11 Mount Road, London, E10 7PP" on "CE1179_Scheduled_Inspection Address Choose Type Page"
    And I click continue on "CE1179_Scheduled_Inspection Address Choose Type Page"
    Then I am presented with the "CE1179_Scheduled_Choose Payee Type Page"
    And I select radio button "Importer" on "CE1179_Scheduled_Choose Payee Type Page"
    When I click continue on "CE1179_Scheduled_Choose Payee Type Page"
    Then I am presented with the "CE1179_Scheduled_Enter Bank Account Details Page"
    When I enter "" on "CE1179_Scheduled_Enter Bank Account Details Page"
    And I click continue on "CE1179_Scheduled_Enter Bank Account Details Page"
#    Then I am presented with the "CE1179_Scheduled_Check Bank Details Page"
#    And I select radio button "yes" on "CE1179_Scheduled_Check Bank Details Page"
#    When I click continue on "CE1179_Scheduled_Check Bank Details Page"
    Then I am presented with the "CE1179_Scheduled_Choose File Type Page"
    When I select radio button "Commercial invoice" on "CE1179_Scheduled_Choose File Type Page"
    And I click continue on "CE1179_Scheduled_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
     #New change CDSR-3829
    Then I am presented with the "CE1179_Scheduled_Claimant Details Change Contact Details Page"
    And I enter "" on "CE1179_Scheduled_Claimant Details Change Contact Details Page"
    And I click continue on "CE1179_Scheduled_Claimant Details Change Contact Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "CE1179_Scheduled_Claimant Details Page"
    And I click continue on "CE1179_Scheduled_Claimant Details Page"
    Then I am presented with the "CE1179_Scheduled_Check Your Answers Page"
    And I should see the following details
      | Reason for claim     | Personal details                | Uploaded files                        | Address                                 | Total |	First Movement Reference Number (MRN)           | Inspection date | UK duty | EU duty | Excise duty  | Additional claim information | Inspection address                          | Disposal method   | Details of the special circumstances | Bank details      | Payee   | Claim summary document |
      | Special circumstances | John Smith,john@smith.com,01234567890 | Commercial invoice:,document.pdf| 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom  | £80.00 |10AAAAAAAAAAAAAAA2            | 10 October 2020 | £10.00  | £10.00  | £60.00    | under 500 characters                        | Importer address:,11 Mount Road,London,E10 7PP,United Kingdom | Return the goods by road, rail, air or ship | under 500 characters   | Mr John Smith,123456,11001001 | Importer | image.jpg          |
    And I click continue on "CE1179_Scheduled_Check Your Answers Page"
    Then I am presented with the "CE1179_Scheduled_Claim Submitted Page"

  @smoke
  Scenario: UnHappy path with no document upload
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    And I select radio button "Upload a file with a list of MRNs" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Scheduled_Have Your Supporting Document Ready Page v2"
    When I clickContinue on "CE1179_Scheduled_Have Your Supporting Document Ready Page v2"
    Then I am presented with the "CE1179_Scheduled_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA2" on "CE1179_Scheduled_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Scheduled_Enter Movement Reference Number Page"
    Then I am presented with the "CE1179_Scheduled_Enter Importer Eori Page"
    When I enter "GB000000000000002" on "CE1179_Scheduled_Enter Importer Eori Page"
    And I click continue on "CE1179_Scheduled_Enter Importer Eori Page"
    Then I am presented with the "CE1179_Scheduled_Enter Declarant Eori Page"
    When I enter "GB000000000000002" on "CE1179_Scheduled_Enter Declarant Eori Page"
    And I click continue on "CE1179_Scheduled_Enter Declarant Eori Page"
    Then I am presented with the "CE1179_Scheduled_Check Declaration Details Page"
   # When I select radio button "Yes" on "CE1179_Scheduled_Check Declaration Details Page"
    And I click continue on "CE1179_Scheduled_Check Declaration Details Page"
     #New change CDSR-3829

    Then I am presented with the "UDF_Choose File Page"
    When I upload a 1 "image.jpg" file on "UDF_Choose File Page"
    And I click continue if I'm on "UDF_Choose File Page"
    Then I am presented with the "CE1179_Scheduled_Choose Basis For Claim Page"
    When I select radio button "Special circumstances" on "CE1179_Scheduled_Choose Basis For Claim Page"
    And I click continue on "CE1179_Scheduled_Choose Basis For Claim Page"
    Then I am presented with the "CE1179_Scheduled_Enter Special Circumstances Page"
    When I enter "under 500 characters" on "CE1179_Multiple_Enter Special Circumstances Page"
    And I click continue on "CE1179_Multiple_Enter Special Circumstances Page"
    Then I am presented with the "CE1179_Scheduled_Choose Disposal Method Page"
    When I select radio button "Return the goods by road, rail, air or ship" on "CE1179_Scheduled_Choose Disposal Method Page"
    And I click continue on "CE1179_Scheduled_Choose Disposal Method Page"
    Then I am presented with the "CE1179_Scheduled_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "CE1179_Scheduled_Enter Rejected Goods Details Page"
    And I click continue on "CE1179_Scheduled_Enter Rejected Goods Details Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Select Duty Types Page"
    When I select "uk-duty" on "CE1179_Scheduled_Select Duties Select Duty Types Page"
    And I click continue on "CE1179_Scheduled_Select Duties Select Duty Types Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Uk Duty Page"
    When I select "A00" on "CE1179_Scheduled_Select Duties Uk Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties Uk Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "UK Duty A00-Customs Duty"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Check Claim Page"
    When I select radio button "Yes" on "CE1179_Scheduled_Check Claim Page"
    And I click continue on "CE1179_Scheduled_Check Claim Page"
    Then I am presented with the "CE1179_Scheduled_Enter Inspection Date Page"
    When I enter "10,10,2020" on "CE1179_Scheduled_Enter Inspection Date Page"
    And I click continue on "CE1179_Scheduled_Enter Inspection Date Page"
    Then I am presented with the "CE1179_Scheduled_Inspection Address Choose Type Page"
    When I select radio button "11 Mount Road, London, E10 7PP" on "CE1179_Scheduled_Inspection Address Choose Type Page"
    And I click continue on "CE1179_Scheduled_Inspection Address Choose Type Page"
    Then I am presented with the "CE1179_Scheduled_Choose Payee Type Page"
    And I select radio button "Importer" on "CE1179_Scheduled_Choose Payee Type Page"
    When I click continue on "CE1179_Scheduled_Choose Payee Type Page"
    Then I am presented with the "CE1179_Scheduled_Check Bank Details Page"
    And I select radio button "yes" on "CE1179_Scheduled_Check Bank Details Page"
    When I click continue on "CE1179_Scheduled_Check Bank Details Page"
    Then I am presented with the "CE1179_Scheduled_Choose File Type Page"
    When I select radio button "Commercial invoice" on "CE1179_Scheduled_Choose File Type Page"
    And I click continue on "CE1179_Scheduled_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    When I select radio button "No" on "UDF_Choose Files Page"
    And I click continue on "UDF_Choose Files Page"
    Then The error summary title is "There is a problem" and the error message is "Upload a supporting document"

    #Then I am presented with the "CE1179_Scheduled_Claimant Details Change Contact Details Page"
    #And I enter "" on "CE1179_Scheduled_Claimant Details Change Contact Details Page"
    #And I click continue on "CE1179_Scheduled_Claimant Details Change Contact Details Page"
    #And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    #And I enter "" on "ALF_Lookup Address Edit Page"
    #And I click continue on "ALF_Lookup Address Edit Page"
    #And I click continue on "ALF_Lookup Address Confirm Page"
    #Then I am presented with the "CE1179_Scheduled_Claimant Details Page"
    #And I click continue on "CE1179_Scheduled_Claimant Details Page"
