@C&E1179 @Scheduled
Feature: C&E1179 Scheduled - XIEORI

  @test
  Scenario: happy path - check importer/declarant eori pages, Special circumstances
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    And I select radio button "Upload multiple MRNs" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Scheduled_Enter Movement Reference Number Page"
    When I enter "10AAAXICDAAAAAAAA1" on "CE1179_Scheduled_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Scheduled_Enter Movement Reference Number Page"
    Then I am presented with the "CE1179_Scheduled_Enter Importer Eori Page"
    When I enter "XI000000000000001" on "CE1179_Scheduled_Enter Importer Eori Page"
    And I click continue on "CE1179_Scheduled_Enter Importer Eori Page"
    Then I am presented with the "CE1179_Scheduled_Enter Declarant Eori Page"
    When I enter "XI000000000000001" on "CE1179_Scheduled_Enter Declarant Eori Page"
    And I click continue on "CE1179_Scheduled_Enter Declarant Eori Page"
    Then I am presented with the "CE1179_Scheduled_Check Declaration Details Page"
    When I select radio button "Yes" on "CE1179_Scheduled_Check Declaration Details Page"
    And I click continue on "CE1179_Scheduled_Check Declaration Details Page"
    Then I am presented with the "UDF_Choose File Page"
    When I upload a 1 "image.jpg" file on "UDF_Choose File Page"
    And I click continue if I'm on "UDF_Choose File Page"
    Then I am presented with the "CE1179_Scheduled_Claimant Details Page"
    When I click continue on "CE1179_Scheduled_Claimant Details Page"
    Then I am presented with the "CE1179_Scheduled_Choose Basis For Claim Page"
    When I select radio button "Special circumstances" on "CE1179_Scheduled_Choose Basis For Claim Page"
    And I click continue on "CE1179_Scheduled_Choose Basis For Claim Page"
    Then I am presented with the "CE1179_Scheduled_Enter Special Circumstances Page"
    When I enter "under 500 characters" on "CE1179_Multiple_Enter Special Circumstances Page"
    And I click continue on "CE1179_Multiple_Enter Special Circumstances Page"
    Then I am presented with the "CE1179_Scheduled_Choose Disposal Method Page"
    When I select radio button "Return the goods by road, rail, air or ship" on "CE1179_Scheduled_Choose Disposal Method Page"
    And I click continue on "CE1179_Scheduled_Choose Disposal Method Page"
    Then I am presented with the "CE1179_Scheduled_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "CE1179_Scheduled_Enter Rejected Goods Details Page"
    And I click continue on "CE1179_Scheduled_Enter Rejected Goods Details Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Select Duty Types Page"
    When I select "uk-duty,eu-duty,beer,wine,made-wine,miscellaneous-road-fuels,tobacco,climate-change-levy" on "CE1179_Scheduled_Select Duties Select Duty Types Page"
    And I click continue on "CE1179_Scheduled_Select Duties Select Duty Types Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Uk Duty Page"
    When I select "A00,B00" on "CE1179_Scheduled_Select Duties Uk Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties Uk Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Eu Duty Page"
    When I select "A50,B05" on "CE1179_Scheduled_Select Duties Eu Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties Eu Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Beer Page"
    When I select "407,447" on "CE1179_Scheduled_Select Duties Beer Page"
    And I click continue on "CE1179_Scheduled_Select Duties Beer Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Wine Page"
    When I select "411,415" on "CE1179_Scheduled_Select Duties Wine Page"
    And I click continue on "CE1179_Scheduled_Select Duties Wine Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Made Wine Page"
    When I select "421,429" on "CE1179_Scheduled_Select Duties Made Wine Page"
    And I click continue on "CE1179_Scheduled_Select Duties Made Wine Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Miscellaneous Road Fuels Page"
    When I select "591,592" on "CE1179_Scheduled_Select Duties Miscellaneous Road Fuels Page"
    And I click continue on "CE1179_Scheduled_Select Duties Miscellaneous Road Fuels Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Tobacco Page"
    When I select "611,633" on "CE1179_Scheduled_Select Duties Tobacco Page"
    And I click continue on "CE1179_Scheduled_Select Duties Tobacco Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Climate Change Levy Page"
    When I select "99A,99D" on "CE1179_Scheduled_Select Duties Climate Change Levy Page"
    And I click continue on "CE1179_Scheduled_Select Duties Climate Change Levy Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "UK Duty A00"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "UK Duty B00"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "EU Duty A50"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "EU Duty B05"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Beer 407"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Beer 447"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Wine 411"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Wine 415"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Made-wine 421"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Made-wine 429"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Miscellaneous road fuels 591"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Miscellaneous road fuels 592"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Tobacco products 611"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Tobacco products 633"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Climate Change Levy 99A"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "Climate Change Levy 99D"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Check Claim Page"
    When I select radio button "Yes" on "CE1179_Scheduled_Check Claim Page"
    And I click continue on "CE1179_Scheduled_Check Claim Page"
    Then I am presented with the "CE1179_Scheduled_Enter Inspection Date Page"
    When I enter "10,10,2020" on "CE1179_Scheduled_Enter Inspection Date Page"
    And I click continue on "CE1179_Scheduled_Enter Inspection Date Page"
    Then I am presented with the "CE1179_Scheduled_Inspection Address Choose Type Page"
    When I select radio button "11 Mount Road, London, E10 7PP" on "CE1179_Scheduled_Inspection Address Choose Type Page"
    And I click continue on "CE1179_Scheduled_Inspection Address Choose Type Page"
    Then I am presented with the "CE1179_Scheduled_Check Bank Details Page"
    When I click continue on "CE1179_Scheduled_Check Bank Details Page"
    Then I am presented with the "CE1179_Scheduled_Choose File Type Page"
    When I select radio button "Commercial invoice" on "CE1179_Scheduled_Choose File Type Page"
    And I click continue on "CE1179_Scheduled_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "CE1179_Scheduled_Check Your Answers Page"
    And I should see the following details
      | This is the basis behind the claim | VAT paid | Import date      | Contact details             | Importer email       | Uploaded                        | Contact address                                   | Importer telephone | Importer name    | Declarant name     | Importer address                                 | Declarant address                                 | Total  | First MRN          | Duties paid | Inspection address type | Inspection date | UK Duty | EU Duty | Made-wine | Tobacco products | Climate Change Levy | Wine   | Beer   | Miscellaneous road fuels | These are the details of the rejected goods | Inspection address                          | This is how the goods will be disposed of   | Any special circumstances relating to your claim | Name on the account | Sort code      | Account number   | Scheduled document |
      | Special circumstances              | £0.00    | 12 February 2021 | TestUser,someemail@mail.com | automation@gmail.com | document.pdf,Commercial invoice | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | +4420723934397     | IT Solutions LTD | Foxpro Central LTD | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | £80.00 | 10AAAXICDAAAAAAAA1 | £828.00     | Importer address        | 10 October 2020 | £10.00  | £10.00  | £10.00    | £10.00           | £10.00              | £10.00 | £10.00 | £10.00                   | under 500 characters                        | 11 Mount Road,London,E10 7PP,United Kingdom | Return the goods by road, rail, air or ship | under 500 characters                             | CDS E2E To E2E Bank | Ending with 44 | Ending with 5678 | image.jpg          |
    And I click continue on "CE1179_Scheduled_Check Your Answers Page"
    Then I am presented with the "CE1179_Scheduled_Claim Submitted Page"

  @smoke
  Scenario: Happy path with no document upload
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    And I select radio button "Upload multiple MRNs" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Scheduled_Enter Movement Reference Number Page"
    When I enter "10XIDCAAAAAAAAAAA1" on "CE1179_Scheduled_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Scheduled_Enter Movement Reference Number Page"
    Then I am presented with the "CE1179_Scheduled_Enter Importer Eori Page"
    When I enter "XI000000000000001" on "CE1179_Scheduled_Enter Importer Eori Page"
    And I click continue on "CE1179_Scheduled_Enter Importer Eori Page"
    Then I am presented with the "CE1179_Scheduled_Enter Declarant Eori Page"
    When I enter "XI000000000000001" on "CE1179_Scheduled_Enter Declarant Eori Page"
    And I click continue on "CE1179_Scheduled_Enter Declarant Eori Page"
    Then I am presented with the "CE1179_Scheduled_Check Declaration Details Page"
    When I select radio button "Yes" on "CE1179_Scheduled_Check Declaration Details Page"
    And I click continue on "CE1179_Scheduled_Check Declaration Details Page"
    Then I am presented with the "UDF_Choose File Page"
    When I upload a 1 "image.jpg" file on "UDF_Choose File Page"
    And I click continue if I'm on "UDF_Choose File Page"
    Then I am presented with the "CE1179_Scheduled_Claimant Details Page"
    When I click continue on "CE1179_Scheduled_Claimant Details Page"
    Then I am presented with the "CE1179_Scheduled_Choose Basis For Claim Page"
    When I select radio button "Special circumstances" on "CE1179_Scheduled_Choose Basis For Claim Page"
    And I click continue on "CE1179_Scheduled_Choose Basis For Claim Page"
    Then I am presented with the "CE1179_Scheduled_Enter Special Circumstances Page"
    When I enter "under 500 characters" on "CE1179_Multiple_Enter Special Circumstances Page"
    And I click continue on "CE1179_Multiple_Enter Special Circumstances Page"
    Then I am presented with the "CE1179_Scheduled_Choose Disposal Method Page"
    When I select radio button "Return the goods by road, rail, air or ship" on "CE1179_Scheduled_Choose Disposal Method Page"
    And I click continue on "CE1179_Scheduled_Choose Disposal Method Page"
    Then I am presented with the "CE1179_Scheduled_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "CE1179_Scheduled_Enter Rejected Goods Details Page"
    And I click continue on "CE1179_Scheduled_Enter Rejected Goods Details Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Select Duty Types Page"
    When I select "uk-duty" on "CE1179_Scheduled_Select Duties Select Duty Types Page"
    And I click continue on "CE1179_Scheduled_Select Duties Select Duty Types Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Uk Duty Page"
    When I select "A00" on "CE1179_Scheduled_Select Duties Uk Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties Uk Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "UK Duty A00"
    When I enter "10,5" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Check Claim Page"
    When I select radio button "Yes" on "CE1179_Scheduled_Check Claim Page"
    And I click continue on "CE1179_Scheduled_Check Claim Page"
    Then I am presented with the "CE1179_Scheduled_Enter Inspection Date Page"
    When I enter "10,10,2020" on "CE1179_Scheduled_Enter Inspection Date Page"
    And I click continue on "CE1179_Scheduled_Enter Inspection Date Page"
    Then I am presented with the "CE1179_Scheduled_Inspection Address Choose Type Page"
    When I select radio button "11 Mount Road, London, E10 7PP" on "CE1179_Scheduled_Inspection Address Choose Type Page"
    And I click continue on "CE1179_Scheduled_Inspection Address Choose Type Page"
    Then I am presented with the "CE1179_Scheduled_Check Bank Details Page"
    When I click continue on "CE1179_Scheduled_Check Bank Details Page"
    Then I am presented with the "CE1179_Scheduled_Choose File Type Page"
    When I select radio button "Commercial invoice" on "CE1179_Scheduled_Choose File Type Page"
    And I click continue on "CE1179_Scheduled_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue on "UDF_Choose Files Page"
    Then I am presented with the "CE1179_Scheduled_Check Your Answers Page"
    And I click continue on "CE1179_Scheduled_Check Your Answers Page"
    Then I am presented with the "CE1179_Scheduled_Claim Submitted Page"