@C&E1179 @Scheduled
Feature: C&E1179 Scheduled Subsidy

  @test
  Scenario: cannot submit a C&E1179 Scheduled claim when lead MRN is subsidy
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    When the "block subsidies" feature is "enabled"
    When the "subsidies for rejected goods" feature is "disabled"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    And I select radio button "Upload multiple MRNs" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Scheduled_Enter Movement Reference Number Page"
    When I enter "10DDDDDDDDDDDDDDD1" on "CE1179_Scheduled_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Scheduled_Enter Movement Reference Number Page"
    And The error summary title is "There is a problem" and the error message is "Subsidy MRNs cannot be added to online claims at this time"


  @test
  Scenario: C&E1179 scheduled MRN claim for Subsidy repayment online
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    When the "block subsidies" feature is "enabled"
    When the "subsidies for rejected goods" feature is "enabled"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    And I select radio button "Upload multiple MRNs" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Scheduled_Enter Movement Reference Number Page"
    When I enter "00AA006AAAAAAAAA01" on "CE1179_Scheduled_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Scheduled_Enter Movement Reference Number Page"
    Then I am presented with the "CE1179_Scheduled_Check Declaration Details Page"
    When I select radio button "yes" on "CE1179_Scheduled_Check Declaration Details Page"
    And I click continue on "CE1179_Scheduled_Check Declaration Details Page"
    Then I am presented with the "UDF_Choose Filess Page"
    When I upload a 1 "image.jpg" file on "UDF_Choose Filess Page"
    And I click continue if I'm on "UDF_Choose Filess Page"
    Then I am presented with the "CE1179_Scheduled_Claimant Details Page"
    When I click continue on "CE1179_Scheduled_Claimant Details Page"
    And I select radio button "Special circumstances" on "CE1179_Scheduled_Choose Basis For Claim Page"
    And I click continue on "CE1179_Scheduled_Choose Basis For Claim Page"
    Then I am presented with the "CE1179_Scheduled_Enter Special Circumstances Page"
    When I enter "under 500 characters" on "CE1179_Multiple_Enter Special Circumstances Page"
    And I click continue on "CE1179_Multiple_Enter Special Circumstances Page"
    Then I am presented with the "CE1179_Scheduled_Choose Disposal Method Page"
    When I select radio button "Return the goods by road, rail, air or ship" on "CE1179_Scheduled_Choose Disposal Method Page"
    And I click continue on "CE1179_Scheduled_Choose Disposal Method Page"
    Then I am presented with the "CE1179_Scheduled_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "CE1179_Scheduled_Enter Rejected Goods Details Page"
    And I click continue on "CE1179_Scheduled_Enter Rejected Goods Details Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties Eu Duty Page"
    When I select "A50,A90" on "CE1179_Scheduled_Select Duties Eu Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties Eu Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "EU Duty A50"
    When I enter "50,30" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    #And I click continue on "CE1179_Scheduled_Select Duties Eu Duty Page"
    Then I am presented with the "CE1179_Scheduled_Select Duties DutyType Duty Page" "EU Duty A90"
    When I enter "50,30" on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    And I click continue on "CE1179_Scheduled_Select Duties DutyType Duty Page"
    Then I am presented with the "CE1179_Scheduled_Check Claim Page"
    When I select radio button "Yes" on "CE1179_Scheduled_Check Claim Page"
    And I click continue on "CE1179_Scheduled_Check Claim Page"
    Then I am presented with the "CE1179_Scheduled_Enter Inspection Date Page"
    When I enter "10,10,2020" on "CE1179_Scheduled_Enter Inspection Date Page"
    And I click continue on "CE1179_Scheduled_Enter Inspection Date Page"
    Then I am presented with the "CE1179_Scheduled_Inspection Address Choose Type Page"
    When I select radio button "11 Mount Road, London, E10 7PP" on "CE1179_Scheduled_Inspection Address Choose Type Page"
    And I click continue on "CE1179_Scheduled_Inspection Address Choose Type Page"
    Then I am presented with the "CE1179_Scheduled_Choose File Type Page"
    When I select radio button "Commercial invoice" on "CE1179_Scheduled_Choose File Type Page"
    And I click continue on "CE1179_Scheduled_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "CE1179_Scheduled_Check Your Answers Page"
    And I should see the following details
      | This is the basis behind the claim | Import date      | Contact details                                       | Importer email       | Uploaded                        | Contact address                                   | Importer telephone | Importer name    | Declarant name     | Importer address                                 | Declarant address                                 | Total  | First MRN          | Duties paid | Inspection address type | Inspection date | These are the details of the rejected goods | Inspection address                          | This is how the goods will be disposed of   | Method of payment | Method             | EU Duty | Scheduled document   | Any special circumstances relating to your claim |
      | Special circumstances                | 12 February 2021 | Online Sales LTD,automation@gmail.com,+4420723934397  | automation@gmail.com | document.pdf,Commercial invoice | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom  | +4420723934397     | IT Solutions LTD | Foxpro Central LTD | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | £40.00 | 00AA006AAAAAAAAA01 | £828.00     | Importer address        | 10 October 2020 | under 500 characters                        | 11 Mount Road,London,E10 7PP,United Kingdom | Return the goods by road, rail, air or ship | Subsidy           | Subsidy allocation | £40.00  | image.jpg          | under 500 characters                             |
    And I click continue on "CE1179_Scheduled_Check Your Answers Page"
    #Then I am presented with the "CE1179_Scheduled_Claim Submitted Page"