@Security @Single
Feature: Securities Single Change Link Tests

  @test
  Scenario: Happy path - Change link tests
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "securities" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"
    When I enter "01AAAAAAAAAAAAAAA1" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I select radio button "Manual override of duty amount" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 5,DEF6543213"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "3 of 5,DEF6543212"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "4 of 5,DEF6543210"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "5 of 5,DEF6543211"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    When I click "Change MRN" on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    When I click "Change reason for security" on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    When I click "Change claim for ABC0123456" on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Select Securities Security Id Page1"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page1"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    When I click "Change claim for DEF6543213" on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Select Securities Security Id Page2"
    When I select radio button "no" on "Securities_Select Securities Security Id Page2"
    And I click continue on "Securities_Select Securities Security Id Page2"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Claimant Details Page"
    When I click "Change contact details" on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Change Contact Details Page"
    And I click continue on "Securities_Change Contact Details Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page3" "ABC0123456"
    When I select radio button "Yes" on "Securities_Confirm Full Repayment Security Id Page3"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page3"
    Then I am presented with the "Securities_Check Claim Page"
    And I click continue on "Securities_Check Claim Page"
    Then I am presented with the "Securities_Check Bank Details Page"
    When I click "Change bank details" on "Securities_Check Bank Details Page"
    Then I am presented with the "Securities_Letter Of Authority Confirmation Page"
    When I select radio button "Yes" on "Securities_Letter Of Authority Confirmation Page"
    And I click continue on "Securities_Letter Of Authority Confirmation Page"
    Then I am presented with the "Securities_Choose Bank Account Type Page"
    When I select radio button "Business bank account" on "Securities_Choose Bank Account Type Page"
    And I click continue on "Securities_Choose Bank Account Type Page"
    Then I am presented with the "Securities_Enter Bank Account Details Page"
    When I enter "" on "Securities_Enter Bank Account Details Page"
    And I click continue on "Securities_Enter Bank Account Details Page"
    Then I am presented with the "Securities_Check Bank Details Page"
    And I select radio button "yes" on "Securities_Check Bank Details Page"
    And I click continue on "Securities_Check Bank Details Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I select radio button "Proof of authority" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "letter of authority"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    When I click "Change import MRN" on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    When I click "Change reason for security deposit" on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    When I click "Change claim for ABC0123456" on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 5,ABC0123456"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Your Answers Page"
#    When I click "Change contact address" on "Securities_Check Your Answers Page"
#    Then I am presented with the "ALF_Lookup Address Lookup Page"
#    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
#    Then I am presented with the "ALF_Lookup Address Edit Page"
#    And I enter "" on "ALF_Lookup Address Edit Page"
#    And I click continue on "ALF_Lookup Address Edit Page"
#    Then I am presented with the "ALF_Lookup Address Confirm Page"
#    And I click continue on "ALF_Lookup Address Confirm Page"
#    Then I am presented with the "Securities_Check Your Answers Page"
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"