@Security @Single
Feature: Securities Single Error Messages

  @test
  Scenario: To test the error messages for the Securities journey
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I click continue on "Check Eori Details Page"
    Then I am presented with the "Check Eori Details Page" error page
    And The error summary title is "There is a problem" and the error message is "Select yes if these EORI details are correct"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I click continue on "Select Claim Type Page"
    Then I am presented with the "Select Claim Type Page" error page
    And The error summary title is "There is a problem" and the error message is "Select the reason for making this claim"
    When I select radio button "securities" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page"
    When I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Enter Movement Reference Number Page" error page
    And The error summary title is "There is a problem" and the error message is "Enter a movement reference number (MRN)"
    When I enter "01AAAAAAAAAAAAAAA1" on "Securities_Enter Movement Reference Number Page"
    And I click continue on "Securities_Enter Movement Reference Number Page"
    Then I am presented with the "Securities_Choose Reason For Security Page"
    When I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Choose Reason For Security Page" error page
    And The error summary title is "There is a problem" and the error message is "Choose the reason for security"
    When I select radio button "Outward Processing Relief (OPR)" on "Securities_Choose Reason For Security Page"
    And I click continue on "Securities_Choose Reason For Security Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "1 of 2,ABC0123456"
    When I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" error page
    And The error summary title is "There is a problem" and the error message is "Select Yes if you are claiming for this Security"
    When I select radio button "yes" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Select Securities Security Id Page" "2 of 2,DEF6543210"
    When I select radio button "no" on "Securities_Select Securities Security Id Page"
    And I click continue on "Securities_Select Securities Security Id Page"
    Then I am presented with the "Securities_Check Declaration Details Page"
    And I click continue on "Securities_Check Declaration Details Page"
    Then I am presented with the "Securities_Claimant Details Page"
    And I click continue on "Securities_Claimant Details Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page" "ABC0123456"
    When I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Confirm Full Repayment Security Id Page" error page
    And The error summary title is "There is a problem" and the error message is "Choose 'Yes' if you would like to claim back the full amount"
    When I select radio button "Yes" on "Securities_Confirm Full Repayment Security Id Page"
    And I click continue on "Securities_Confirm Full Repayment Security Id Page"
    Then I am presented with the "Securities_Check Claim Page"
    And I click continue on "Securities_Check Claim Page"
    Then I am presented with the "Securities_Check Bank Details Page"
    When I click "Change bank details" on "Securities_Check Bank Details Page"
    Then I am presented with the "Securities_Letter Of Authority Confirmation Page"
    When I click continue on "Securities_Letter Of Authority Confirmation Page"
    Then I am presented with the "Securities_Letter Of Authority Confirmation Page" error page
    And The error summary title is "There is a problem" and the error message is "Select yes to continue updating bank account details"
    When I select radio button "Yes" on "Securities_Letter Of Authority Confirmation Page"
    And I click continue on "Securities_Letter Of Authority Confirmation Page"
    Then I am presented with the "Securities_Choose Bank Account Type Page"
    When I click continue on "Securities_Choose Bank Account Type Page"
    Then I am presented with the "Securities_Choose Bank Account Type Page" error page
    And The error summary title is "There is a problem" and the error message is "Select if this is a business bank account or a personal bank account"
    When I select radio button "Business bank account" on "Securities_Choose Bank Account Type Page"
    And I click continue on "Securities_Choose Bank Account Type Page"
    Then I am presented with the "Securities_Enter Bank Account Details Page"
    When I click continue on "Securities_Enter Bank Account Details Page"
    Then I am presented with the "Securities_Enter Bank Account Details Page" error page
    And The error summary title is "There is a problem" and the error message is "Enter the name on the account"
    When I enter "" on "Securities_Enter Bank Account Details Page"
    And I click continue on "Securities_Enter Bank Account Details Page"
    Then I am presented with the "Securities_Check Bank Details Page"
    And I click continue on "Securities_Check Bank Details Page"
    Then I am presented with the "Securities_Choose File Type Page"
    When I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "Securities_Choose File Type Page" error page
    And The error summary title is "There is a problem" and the error message is "Select which type of document you are uploading"
    When I select radio button "Commercial invoice" on "Securities_Choose File Type Page"
    And I click continue on "Securities_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    When I click continue on "UDF_Choose Files Page"
    And The error summary title is "There is a problem" and the error message is "Select yes to add a different type of supporting document to your claim"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "Securities_Check Your Answers Page"
    When I click continue on "Securities_Check Your Answers Page"
    Then I am presented with the "Securities_Claim Submitted Page"