@Regression @new

Feature: C285 - File upload

  Background:
    Given the "Bulk Claim" feature is "disabled"
    Given the "Entry Number" feature is "enabled"
    Given the "Northern Ireland" feature is "disabled"

  @test @a11y @ZAP
  Scenario: User is a CDS Trader - uploads 3 valid files
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Enter Movement Reference Number Page"
    When I enter "000000001A00000001" on "Enter Movement Reference Number Page"
    And I click continue on "Enter Movement Reference Number Page"
    Then I am presented with the "Entry_Enter Declaration Details Page" and content "000000001A00000001"
    When I enter "" on "Entry_Enter Declaration Details Page"
    And I click continue on "Entry_Enter Declaration Details Page"
    Then I am presented with the "Entry_Who Is The Declarant Page"
    When I select radio button "0" on "Entry_Who Is The Declarant Page"
    And I click continue on "Entry_Who Is The Declarant Page"
    Then I am presented with the "Entry_Enter Your Details As Registered With CDS"
    When I enter "" on "Entry_Enter Your Details As Registered With CDS"
    And I select radio button "yes" on "Entry_Enter Your Details As Registered With CDS"
    And I click continue on "Entry_Enter Your Details As Registered With CDS"
    Then I am presented with the "Entry_Enter Your Contact Details Page"
    When I enter "" on "Entry_Enter Your Contact Details Page"
    And I click continue on "Entry_Enter Your Contact Details Page"
    Then I am presented with the "Entry_Enter Reason For Claim And Basis Page"
    When I select dropdown value "Duplicate Entry,Special circumstances" on "Entry_Enter Reason For Claim And Basis Page"
    And I click continue on "Entry_Enter Reason For Claim And Basis Page"
    Then I am presented with the "Entry_Enter Duplicate Movement Reference Number Page"
    When I enter "000000002B00000002" on "Entry_Enter Duplicate Movement Reference Number Page"
    And I click continue on "Entry_Enter Duplicate Movement Reference Number Page"
    ### line below is an error and should be changed when fixed, to: Then I am presented with the "Entry_Enter Duplicate Declaration Details Page" and content "000000002B00000002"
    Then I am presented with the "Entry_Enter Duplicate Declaration Details Page" and content "000000001A00000001"
    When I enter "" on "Entry_Enter Duplicate Declaration Details Page"
    And I click continue on "Entry_Enter Duplicate Declaration Details Page"
    Then I am presented with the "Entry_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Entry_Enter Commodity Details Page"
    And I click continue on "Entry_Enter Commodity Details Page"
    Then I am presented with the "Entry_Select Duties Page"
    When I select "A00" on "Entry_Select Duties Page"
    And I click continue on "Entry_Select Duties Page"
    Then I am presented with the "Entry_Enter Claim Page" "A00 - Customs Duty"
    When I enter "2,1" on "Entry_Enter Claim Page"
    And I click continue on "Entry_Enter Claim Page"
    Then I am presented with the "Entry_Check Claim Page"
    And I select radio button "yes" on "Entry_Check Claim Page"
    When I click continue on "Entry_Check Claim Page"
    Then I am presented with the "Entry_Enter Bank Account Details Page"
    When I enter "" on "Entry_Enter Bank Account Details Page"
    And I select checkbox on "Entry_Enter Bank Account Details Page"
    And I click continue on "Entry_Enter Bank Account Details Page"
    Then I am presented with the "Entry_Supporting Evidence Upload Supporting Evidence Page"
    # upload file 1
    When I upload a "image.jpg" file on "Entry_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Entry_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Entry_Supporting Evidence Scan Progress Page"
    Then I am presented with the "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    When I select dropdown value "C88/E2" on "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Entry_Supporting Evidence Check Your Answers Page"
    And I click "Add another file" on "Entry_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Entry_Supporting Evidence Upload Supporting Evidence Page"
    # ---
    # upload file 2
    When I upload a "document.doc" file on "Entry_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Entry_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Entry_Supporting Evidence Scan Progress Page"
    Then I am presented with the "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    When I select dropdown value "Packing List" on "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Entry_Supporting Evidence Check Your Answers Page"
    And I click "Add another file" on "Entry_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Entry_Supporting Evidence Upload Supporting Evidence Page"
    # ---
    # upload file 3
    When I upload a "document.pdf" file on "Entry_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Entry_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Entry_Supporting Evidence Scan Progress Page"
    Then I am presented with the "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    When I select dropdown value "Commercial Invoice" on "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Entry_Supporting Evidence Check Your Answers Page"
    # ---
    When I click continue on "Entry_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Entry_Check Answers Accept Send Page"
    And I click continue on "Entry_Check Answers Accept Send Page"
    Then I am presented with the "Entry_Claim Submitted Page" and content "£1.00"

  @test
  Scenario: User is a CDS Trader - fails file upload steps
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Enter Movement Reference Number Page"
    When I enter "000000001A00000001" on "Enter Movement Reference Number Page"
    And I click continue on "Enter Movement Reference Number Page"
    Then I am presented with the "Entry_Enter Declaration Details Page" and content "000000001A00000001"
    When I enter "" on "Entry_Enter Declaration Details Page"
    And I click continue on "Entry_Enter Declaration Details Page"
    Then I am presented with the "Entry_Who Is The Declarant Page"
    When I select radio button "0" on "Entry_Who Is The Declarant Page"
    And I click continue on "Entry_Who Is The Declarant Page"
    Then I am presented with the "Entry_Enter Your Details As Registered With CDS"
    When I enter "" on "Entry_Enter Your Details As Registered With CDS"
    And I select radio button "yes" on "Entry_Enter Your Details As Registered With CDS"
    And I click continue on "Entry_Enter Your Details As Registered With CDS"
    Then I am presented with the "Entry_Enter Your Contact Details Page"
    When I enter "" on "Entry_Enter Your Contact Details Page"
    And I click continue on "Entry_Enter Your Contact Details Page"
    Then I am presented with the "Entry_Enter Reason For Claim And Basis Page"
    When I select dropdown value "RGR,Overpayment" on "Entry_Enter Reason For Claim And Basis Page"
    And I click continue on "Entry_Enter Reason For Claim And Basis Page"
    Then I am presented with the "Entry_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Entry_Enter Commodity Details Page"
    And I click continue on "Entry_Enter Commodity Details Page"
    Then I am presented with the "Entry_Select Duties Page"
    When I select "A00" on "Entry_Select Duties Page"
    And I click continue on "Entry_Select Duties Page"
    Then I am presented with the "Entry_Enter Claim Page" "A00 - Customs Duty"
    When I enter "2,1" on "Entry_Enter Claim Page"
    And I click continue on "Entry_Enter Claim Page"
    Then I am presented with the "Entry_Check Claim Page"
    And I select radio button "yes" on "Entry_Check Claim Page"
    When I click continue on "Entry_Check Claim Page"
    Then I am presented with the "Entry_Enter Bank Account Details Page"
    When I enter "" on "Entry_Enter Bank Account Details Page"
    And I select checkbox on "Entry_Enter Bank Account Details Page"
    And I click continue on "Entry_Enter Bank Account Details Page"
    Then I am presented with the "Entry_Supporting Evidence Upload Supporting Evidence Page"
    # I don't upload a file, but I click continue
    And I click continue on "Entry_Supporting Evidence Upload Supporting Evidence Page"
    Then I am presented with the "Entry_Supporting Evidence Upload Supporting Evidence Page" error page
    # ---
    # I upload a file that is too big
    When I upload a "image-big.jpg" file on "Entry_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Entry_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Entry_Supporting Evidence Scan Progress Page"
    Then I am presented with the "Entry_Supporting Evidence Document Did Not Upload Page"
    And I click continue on "Entry_Supporting Evidence Document Did Not Upload Page"
    Then I am presented with the "Entry_Supporting Evidence Upload Supporting Evidence Page"
    # ---
    # I upload a good file but don't select a description
    When I upload a "image.jpg" file on "Entry_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Entry_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Entry_Supporting Evidence Scan Progress Page"
    Then I am presented with the "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Entry_Supporting Evidence Select Supporting Evidence Type Page" error page
    # ---
    # I select a description
    When I select dropdown value "Air Waybill" on "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Entry_Supporting Evidence Check Your Answers Page"
    # ---
    # I remove all uploaded documents
    When I click "Remove" on "Entry_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Entry_Supporting Evidence Upload Supporting Evidence Page"
    # ---
    # I upload a file successfully
    When I upload a "image.jpg" file on "Entry_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Entry_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Entry_Supporting Evidence Scan Progress Page"
    Then I am presented with the "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    When I select dropdown value "Bill of Lading" on "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Entry_Supporting Evidence Check Your Answers Page"
    # ---
    When I click continue on "Entry_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Entry_Check Answers Accept Send Page"
    And I click continue on "Entry_Check Answers Accept Send Page"
    Then I am presented with the "Entry_Claim Submitted Page" and content "£1.00"
