Feature: C&E1179 Exploratory file

  @Exp
  Scenario: happy path - check importer/declarant eori pages
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    And I select radio button "Enter one MRN" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Single_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA2" on "CE1179_Single_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Single_Enter Movement Reference Number Page"
    Then I am presented with the "CE1179_Single_Enter Importer Eori Page"
    When I enter "GB000000000000002" on "CE1179_Single_Enter Importer Eori Page"
    And I click continue on "CE1179_Single_Enter Importer Eori Page"
    Then I am presented with the "CE1179_Single_Enter Declarant Eori Page"
    When I enter "GB000000000000002" on "CE1179_Single_Enter Declarant Eori Page"
    And I click continue on "CE1179_Single_Enter Declarant Eori Page"
    Then I am presented with the "CE1179_Single_Check Declaration Details Page"
    When I select radio button "yes" on "CE1179_Single_Check Declaration Details Page"
    And I click continue on "CE1179_Single_Check Declaration Details Page"
    Then I am presented with the "CE1179_Single_Claimant Details Change Claimant Details Page"
    And I enter "" on "CE1179_Single_Claimant Details Change Claimant Details Page"
    And I click continue on "CE1179_Single_Claimant Details Change Claimant Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "CE1179_Single_Claimant Details Page"
    And I click continue on "CE1179_Single_Claimant Details Page"
    Then I am presented with the "CE1179_Single_Choose Basis For Claim Page"
    When I select radio button "Not in accordance with contract" on "CE1179_Single_Choose Basis For Claim Page"
    And I click continue on "CE1179_Single_Choose Basis For Claim Page"
    Then I am presented with the "CE1179_Single_Choose Disposal Method Page"
    When I select radio button "Export" on "CE1179_Single_Choose Disposal Method Page"
    And I click continue on "CE1179_Single_Choose Disposal Method Page"
    Then I am presented with the "CE1179_Single_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "CE1179_Single_Enter Rejected Goods Details Page"
    And I click continue on "CE1179_Single_Enter Rejected Goods Details Page"
    Then I am presented with the "CE1179_Single_Select Duties Page"
    When I select "A80,A95,A90,A85" on "CE1179_Single_Select Duties Page"
    And I click continue on "CE1179_Single_Select Duties Page"
    Then I am presented with the "CE1179_Single_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "CE1179_Single_Enter Claim Page"
    And I click continue on "CE1179_Single_Enter Claim Page"
    Then I am presented with the "CE1179_Single_Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "CE1179_Single_Enter Claim Page"
    And I click continue on "CE1179_Single_Enter Claim Page"
    Then I am presented with the "CE1179_Single_Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "CE1179_Single_Enter Claim Page"
    And I click continue on "CE1179_Single_Enter Claim Page"
    Then I am presented with the "CE1179_Single_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "CE1179_Single_Enter Claim Page"
    And I click continue on "CE1179_Single_Enter Claim Page"
    Then I am presented with the "CE1179_Single_Check Claim Page"
    When I select radio button "yes" on "CE1179_Single_Check Claim Page"
    And I click continue on "CE1179_Single_Check Claim Page"
    Then I am presented with the "CE1179_Single_Enter Inspection Date Page"
    When I enter "10,10,2020" on "CE1179_Single_Enter Inspection Date Page"
    And I click continue on "CE1179_Single_Enter Inspection Date Page"
    Then I am presented with the "CE1179_Single_Inspection Address Choose Type Page"
    When I select radio button "11 Mount Road, London, E10 7PP" on "CE1179_Single_Inspection Address Choose Type Page"
    And I click continue on "CE1179_Single_Inspection Address Choose Type Page"
    Then I am presented with the "CE1179_Single_Check Bank Details Page"
    And I select radio button "yes" on "CE1179_Single_Check Bank Details Page"
    When I click continue on "CE1179_Single_Check Bank Details Page"
    Then I am presented with the "CE1179_Single_Choose File Type Page"
    When I select radio button "Commercial invoice" on "CE1179_Single_Choose File Type Page"
    And I click continue on "CE1179_Single_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    When I upload a "document.pdf" file on "UDF_Choose Files Page"
    And I click continue on "UDF_Choose File Page"
    And I click continue if I'm on "UDF_Progress Page"
    Then I am presented with the "UDF_Summary Page" "1"
    When I select radio button "Yes" on "UDF_Summary Page"
    And I click continue on "UDF_Summary Page"
    Then I am presented with the "CE1179_Single_Choose File Type Page"
    When I select radio button "Import or export declaration" on "CE1179_Single_Choose File Type Page"
    And I click continue on "CE1179_Single_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import or export declaration"
    When I upload a "image.jpg" file on "UDF_Choose Files Page"
    And I click continue on "UDF_Choose File Page"
    And I click continue if I'm on "UDF_Progress Page"
    Then I am presented with the "UDF_Summary Page" "2"
    When I select radio button "No" on "UDF_Summary Page"
    And I click continue on "UDF_Summary Page"
    Then I am presented with the "CE1179_Single_Check Your Answers Page"
    And I click continue on "CE1179_Single_Check Your Answers Page"
    Then I am presented with the "CE1179_Single_Claim Submitted Page"
