@C&E1179 @Multiple
Feature: C&E1179 Multiple Subsidy

  @test
  Scenario: Cannot submit a C&E1179 Multiple MRN claim when first MRN is subsidy
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    When the "block subsidies" feature is "enabled"
    When the "subsidies for rejected goods" feature is "disabled"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    When I select radio button "Enter multiple MRNs" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number Page"
    When I enter "10DDDDDDDDDDDDDDD1" on "CE1179_Multiple_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Multiple_Enter Movement Reference Number Page"
    Then The error summary title is "There is a problem" and the error message is "Subsidy MRNs cannot be added to online claims at this time"


  @test
  Scenario: Cannot submit a C&E1179 Multiple MRN claim when second MRN is subsidy
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    When the "block subsidies" feature is "enabled"
    When the "subsidies for rejected goods" feature is "disabled"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    And I select radio button "Enter multiple MRNs" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "CE1179_Multiple_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "CE1179_Multiple_Check Declaration Details Page"
    When I select radio button "yes" on "CE1179_Multiple_Check Declaration Details Page"
    And I click continue on "CE1179_Multiple_Check Declaration Details Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number 6 Page"
    When I enter "10DDDDDDDDDDDDDDD1" on "CE1179_Multiple_Enter Movement Reference Number 6 Page"
    And I click continue on "CE1179_Multiple_Enter Movement Reference Number 6 Page"
    Then The error summary title is "There is a problem" and the error message is "Subsidy MRNs cannot be added to online claims at this time"


  @test
  Scenario: C&E1179 multiple MRN claim for Subsidy repayment online
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    When the "block subsidies" feature is "enabled"
    When the "subsidies for rejected goods" feature is "enabled"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    And I am presented with the "CE1179_Choose How Many Mrns Page" "A Movement Reference Number (MRN) is a unique 18-digit number that is issued when an import is declared. An MRN can be associated with either a GB or an XI EORI number. You can find it in your initial import acceptance notification, commercial software or in documents from a shipping company, freight forwarder or agency."
    And I am presented with the "CE1179_Choose How Many Mrns Page" "Entering Multiple MRNs"
    And I am presented with the "CE1179_Choose How Many Mrns Page" "You can enter MRNs associated with both GB and XI EORI numbers. If your claim includes multiple MRNs, the goods must: all be from the same importer all have the same reason for overpayment have the same method of payment"
    And I select radio button "Enter multiple MRNs" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number Page"
    When I enter "00AA006AAAAAAAAA01" on "CE1179_Multiple_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "CE1179_Multiple_Check Declaration Details Page"
    When I am presented with the "CE1179_Multiple_Check Declaration Details Page" "This is a subsidy MRN. All additional MRNs you include in this claim must be subsidy only"
    And I select radio button "yes" on "CE1179_Multiple_Check Declaration Details Page"
    And I click continue on "CE1179_Multiple_Check Declaration Details Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    When I enter "01AA006AAAAAAAAA01" on "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    Then I click continue on "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    When I am presented with the "CE1179_Multiple_Check Movement Reference Numbers Page"
    And I am presented with the "CE1179_Multiple_Check Movement Reference Numbers Page" "First MRN 00AA006AAAAAAAAA01 Change"
    And I am presented with the "CE1179_Multiple_Check Movement Reference Numbers Page" "Second MRN 01AA006AAAAAAAAA01 Change"
    And I click "Change" on "CE1179_Multiple_Enter Movement Reference Number 1 Page"
    And I click continue on "CE1179_Multiple_Enter Movement Reference Number 1 Page"
    And I select radio button "yes" on "CE1179_Multiple_Check Declaration Details Page"
    And I click continue on "CE1179_Multiple_Check Declaration Details Page"
    And I select radio button "No" on "CE1179_Multiple_Check Movement Reference Numbers Page"
    And I click continue on "CE1179_Multiple_Check Movement Reference Numbers Page"
    Then I am presented with the "CE1179_Multiple_Claimant Details Page"
    When I click continue on "CE1179_Multiple_Claimant Details Page"
    And I select radio button "Goods are not in accordance with contract" on "CE1179_Multiple_Choose Basis For Claim Page"
    And I click continue on "CE1179_Multiple_Choose Basis For Claim Page"
    Then I am presented with the "CE1179_Multiple_Choose Disposal Method Page"
    When I select radio button "Return the goods by road, rail, air or ship" on "CE1179_Multiple_Choose Disposal Method Page"
    And I click continue on "CE1179_Multiple_Choose Disposal Method Page"
    Then I am presented with the "CE1179_Multiple_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "CE1179_Single_Enter Rejected Goods Details Page"
    And I click continue on "CE1179_Multiple_Enter Rejected Goods Details Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 1 Page"
    And I am presented with the "CE1179_Multiple_Select Duties 1 Page" "These are the duties that have been paid under MRN: 00AA006AAAAAAAAA01"
    When I select "A80,A95,A90,A85" on "CE1179_Multiple_Select Duties 1 Page"
    And I click continue on "CE1179_Multiple_Select Duties 1 Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 1 Duty Page" "A80 - Definitive Anti-Dumping Duty under first MRN"
    When I enter "20" on "CE1179_Multiple_Select Duties 1 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 1 Duty Page" "A95 - Provisional Countervailing Duty under first MRN"
    When I enter "10" on "CE1179_Multiple_Select Duties 1 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 1 Duty Page" "A90 - Definitive Countervailing Duty under first MRN"
    When I enter "20" on "CE1179_Multiple_Select Duties 1 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 1 Duty Page" "A85 - Provisional Anti-Dumping Duty under first MRN"
    When I enter "10" on "CE1179_Multiple_Select Duties 1 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 2 Page"
    When I select "A80,A95,A90,A85" on "CE1179_Multiple_Select Duties 2 Page"
    And I click continue on "CE1179_Multiple_Select Duties 2 Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 2 Duty Page" "A80 - Definitive Anti-Dumping Duty under second MRN"
    When I enter "20" on "CE1179_Multiple_Select Duties 2 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 2 Duty Page" "A95 - Provisional Countervailing Duty under second MRN"
    When I enter "30" on "CE1179_Multiple_Select Duties 2 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 2 Duty Page" "A90 - Definitive Countervailing Duty under second MRN"
    When I enter "50" on "CE1179_Multiple_Select Duties 2 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 2 Duty Page" "A85 - Provisional Anti-Dumping Duty under second MRN"
    When I enter "40" on "CE1179_Multiple_Select Duties 2 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "CE1179_Multiple_Check Claim Page"
    When I select radio button "yes" on "CE1179_Multiple_Check Claim Page"
    And I click continue on "CE1179_Multiple_Check Claim Page"
    Then I am presented with the "CE1179_Multiple_Enter Inspection Date Page"
    When I enter "10,10,2020" on "CE1179_Multiple_Enter Inspection Date Page"
    And I click continue on "CE1179_Multiple_Enter Inspection Date Page"
    Then I am presented with the "CE1179_Multiple_Inspection Address Choose Type Page"
    When I select radio button "11 Mount Road, London, E10 7PP" on "CE1179_Multiple_Inspection Address Choose Type Page"
    And I click continue on "CE1179_Multiple_Inspection Address Choose Type Page"
    Then I am presented with the "CE1179_Multiple_Choose File Type Page"
    When I select radio button "Commercial invoice" on "CE1179_Multiple_Choose File Type Page"
    And I click continue on "CE1179_Multiple_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue on "UDF_Choose Files Page"
    Then I am presented with the "UDF_Choose Files Page" error page
    When I upload a 1 "image.jpg" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "CE1179_Multiple_Check Your Answers Page"
    And I am presented with the "CE1179_Multiple_Check Your Answers Page" "Movement Reference Numbers (MRNs) - Subsidy"
    And I should see the following details
      | This is the basis behind the claim        | Second MRN         | Import date      | Contact details                                     | Importer email       | Uploaded                     | Contact address                                  | Importer telephone | Importer name    | Declarant name     | Method of payment | Importer address                                 | Declarant address                                 | Total   | Method             | First MRN          | Duties paid | 00AA006AAAAAAAAA01 | Inspection address type | Inspection date | 01AA006AAAAAAAAA01 | These are the details of the rejected goods | Inspection address                          | This is how the goods will be disposed of   |
      | Goods are not in accordance with contract | 01AA006AAAAAAAAA01 | 12 February 2021 | Online Sales LTD,automation@gmail.com,+4420723934397 | automation@gmail.com | image.jpg,Commercial invoice | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | +4420723934397     | IT Solutions LTD | Foxpro Central LTD | Subsidy           | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | £200.00 | Subsidy allocation | 00AA006AAAAAAAAA01 | £828.00     | £60.00             | Importer address        | 10 October 2020 | £140.00            | under 500 characters                        | 11 Mount Road,London,E10 7PP,United Kingdom | Return the goods by road, rail, air or ship |
    And I click continue on "CE1179_Multiple_Check Your Answers Page"
    #Then I am presented with the "CE1179_Multiple_Claim Submitted Page"
