@C&E1179 @Multiple
Feature: C&E1179 Multiple

  @test @a11y @ZAP
  Scenario: happy path - check importer/declarant eori pages
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    When I select radio button "Enter multiple MRNs" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA2" on "CE1179_Multiple_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "CE1179_Multiple_Enter Importer Eori Page"
    When I enter "GB000000000000002" on "CE1179_Multiple_Enter Importer Eori Page"
    And I click continue on "CE1179_Multiple_Enter Importer Eori Page"
    Then I am presented with the "CE1179_Multiple_Enter Declarant Eori Page"
    When I enter "GB000000000000002" on "CE1179_Multiple_Enter Declarant Eori Page"
    And I click continue on "CE1179_Multiple_Enter Declarant Eori Page"
    Then I am presented with the "CE1179_Multiple_Check Declaration Details Page"
    And I select radio button "yes" on "CE1179_Multiple_Check Declaration Details Page"
    And I click continue on "CE1179_Multiple_Check Declaration Details Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    When I enter "20AAAAAAAAAAAAAAA2" on "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "CE1179_Multiple_Check Movement Reference Numbers Page"
    When I select radio button "No" on "CE1179_Multiple_Check Movement Reference Numbers Page"
    And I click continue on "CE1179_Multiple_Check Movement Reference Numbers Page"
    Then I am presented with the "CE1179_Multiple_Claimant Details Page"
    And I click continue on "CE1179_Multiple_Claimant Details Page"
    Then I am presented with the "CE1179_Multiple_Choose Basis For Claim Page"
    When I select radio button "Defective" on "CE1179_Multiple_Choose Basis For Claim Page"
    And I click continue on "CE1179_Multiple_Choose Basis For Claim Page"
    Then I am presented with the "CE1179_Multiple_Choose Disposal Method Page"
    When I select radio button "Return the goods by road, rail, air or ship" on "CE1179_Multiple_Choose Disposal Method Page"
    And I click continue on "CE1179_Multiple_Choose Disposal Method Page"
    Then I am presented with the "CE1179_Multiple_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "CE1179_Multiple_Enter Rejected Goods Details Page"
    And I click continue on "CE1179_Multiple_Enter Rejected Goods Details Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 1 Page"
    When I select "A80,A95" on "CE1179_Multiple_Select Duties 1 Page"
    And I click continue on "CE1179_Multiple_Select Duties 1 Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 1 Duty Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "CE1179_Multiple_Select Duties 1 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 1 Duty Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "CE1179_Multiple_Select Duties 1 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 2 Page"
    When I select "A90,A85" on "CE1179_Multiple_Select Duties 2 Page"
    And I click continue on "CE1179_Multiple_Select Duties 2 Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 2 Duty Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "CE1179_Multiple_Select Duties 2 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 2 Duty Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "CE1179_Multiple_Select Duties 2 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "CE1179_Multiple_Check Claim Page"
    And I select radio button "yes" on "CE1179_Multiple_Check Claim Page"
    When I click continue on "CE1179_Multiple_Check Claim Page"
    Then I am presented with the "CE1179_Multiple_Enter Inspection Date Page"
    When I enter "10,10,2020" on "CE1179_Multiple_Enter Inspection Date Page"
    And I click continue on "CE1179_Multiple_Enter Inspection Date Page"
    Then I am presented with the "CE1179_Multiple_Inspection Address Choose Type Page"
    When I select radio button "11 Mount Road, London, E10 7PP" on "CE1179_Multiple_Inspection Address Choose Type Page"
    And I click continue on "CE1179_Multiple_Inspection Address Choose Type Page"
    Then I am presented with the "CE1179_Multiple_Check Bank Details Page"
    When I click continue on "CE1179_Multiple_Check Bank Details Page"
    Then I am presented with the "CE1179_Multiple_Choose File Type Page"
    When I select radio button "Commercial invoice" on "CE1179_Multiple_Choose File Type Page"
    And I click continue on "CE1179_Multiple_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "CE1179_Multiple_Check Your Answers Page"
    And I should see the following details
      | This is the basis behind the claim | VAT paid | Import date      | Contact details             | Importer email       | Uploaded                        | Contact address                                   | Name on the account | Importer telephone | Importer name    | Account number   | Declarant name     | Importer address                                 | Declarant address                                 | Total  | 20AAAAAAAAAAAAAAA2 | 10AAAAAAAAAAAAAAA2 | First MRN          | Second MRN         | Duties paid | Sort code      | Inspection address type | Inspection date | These are the details of the rejected goods | Inspection address                          | This is how the goods will be disposed of   |
      | Defective                          | £0.00    | 12 February 2021 | Info Tech LTD,user@test.com | automation@gmail.com | document.pdf,Commercial invoice | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | CDS E2E To E2E Bank | +4420723934397     | IT Solutions LTD | Ending with 5678 | Foxpro Central LTD | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | £40.00 | £20.00             | £20.00             | 10AAAAAAAAAAAAAAA2 | 20AAAAAAAAAAAAAAA2 | £828.00     | Ending with 44 | Importer address        | 10 October 2020 | under 500 characters                        | 11 Mount Road,London,E10 7PP,United Kingdom | Return the goods by road, rail, air or ship |
    And I click continue on "CE1179_Multiple_Check Your Answers Page"
    Then I am presented with the "CE1179_Multiple_Claim Submitted Page"

  @test @a11y @ZAP
  Scenario: happy path - Special circumstances, CMA eligible
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    And I select radio button "Enter multiple MRNs" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "CE1179_Multiple_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "CE1179_Multiple_Check Declaration Details Page"
    And I select radio button "yes" on "CE1179_Multiple_Check Declaration Details Page"
    And I click continue on "CE1179_Multiple_Check Declaration Details Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    When I enter "20AAAAAAAAAAAAAAA1" on "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "CE1179_Multiple_Check Movement Reference Numbers Page"
    When I select radio button "No" on "CE1179_Multiple_Check Movement Reference Numbers Page"
    And I click continue on "CE1179_Multiple_Check Movement Reference Numbers Page"
    Then I am presented with the "CE1179_Multiple_Claimant Details Page"
    And I click continue on "CE1179_Multiple_Claimant Details Page"
    Then I am presented with the "CE1179_Multiple_Choose Basis For Claim Page"
    When I select radio button "Special circumstances" on "CE1179_Multiple_Choose Basis For Claim Page"
    And I click continue on "CE1179_Multiple_Choose Basis For Claim Page"
    Then I am presented with the "CE1179_Multiple_Enter Special Circumstances Page"
    When I enter "under 500 characters" on "CE1179_Multiple_Enter Special Circumstances Page"
    And I click continue on "CE1179_Multiple_Enter Special Circumstances Page"
    Then I am presented with the "CE1179_Multiple_Choose Disposal Method Page"
    When I select radio button "Return the goods by road, rail, air or ship" on "CE1179_Multiple_Choose Disposal Method Page"
    And I click continue on "CE1179_Multiple_Choose Disposal Method Page"
    Then I am presented with the "CE1179_Multiple_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "CE1179_Multiple_Enter Rejected Goods Details Page"
    And I click continue on "CE1179_Multiple_Enter Rejected Goods Details Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 1 Page"
    When I select "A80,A95" on "CE1179_Multiple_Select Duties 1 Page"
    And I click continue on "CE1179_Multiple_Select Duties 1 Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 1 Duty Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "CE1179_Multiple_Select Duties 1 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 1 Duty Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "CE1179_Multiple_Select Duties 1 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 2 Page"
    When I select "A90,A85" on "CE1179_Multiple_Select Duties 2 Page"
    And I click continue on "CE1179_Multiple_Select Duties 2 Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 2 Duty Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "CE1179_Multiple_Select Duties 2 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 2 Duty Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "CE1179_Multiple_Select Duties 2 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "CE1179_Multiple_Check Claim Page"
    And I select radio button "yes" on "CE1179_Multiple_Check Claim Page"
    When I click continue on "CE1179_Multiple_Check Claim Page"
    Then I am presented with the "CE1179_Multiple_Enter Inspection Date Page"
    When I enter "10,10,2020" on "CE1179_Multiple_Enter Inspection Date Page"
    And I click continue on "CE1179_Multiple_Enter Inspection Date Page"
    Then I am presented with the "CE1179_Multiple_Inspection Address Choose Type Page"
    When I select radio button "11 Mount Road, London, E10 7PP" on "CE1179_Multiple_Inspection Address Choose Type Page"
    And I click continue on "CE1179_Multiple_Inspection Address Choose Type Page"
    Then I am presented with the "CE1179_Multiple_Check Bank Details Page"
    When I click continue on "CE1179_Multiple_Check Bank Details Page"
    Then I am presented with the "CE1179_Multiple_Choose File Type Page"
    When I select radio button "Commercial invoice" on "CE1179_Multiple_Choose File Type Page"
    And I click continue on "CE1179_Multiple_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "CE1179_Multiple_Check Your Answers Page"
    And I should see the following details
      | This is the basis behind the claim | VAT paid | Import date      | Contact details                                      | Importer email       | Uploaded                        | Contact address                                  | Name on the account | Importer telephone | Importer name    | Account number   | Declarant name     | Importer address                                 | Declarant address                                 | Total  | 20AAAAAAAAAAAAAAA1 | 10AAAAAAAAAAAAAAA1 | First MRN          | Second MRN         | Duties paid | Sort code      | Inspection address type | Inspection date | These are the details of the rejected goods | Inspection address                          | This is how the goods will be disposed of   | Any special circumstances relating to your claim |
      | Special circumstances              | £0.00    | 12 February 2021 | Online Sales LTD,automation@gmail.com,+4420723934397 | automation@gmail.com | document.pdf,Commercial invoice | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | CDS E2E To E2E Bank | +4420723934397     | IT Solutions LTD | Ending with 5678 | Foxpro Central LTD | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | £40.00 | £20.00             | £20.00             | 10AAAAAAAAAAAAAAA1 | 20AAAAAAAAAAAAAAA1 | £828.00     | Ending with 44 | Importer address        | 10 October 2020 | under 500 characters                        | 11 Mount Road,London,E10 7PP,United Kingdom | Return the goods by road, rail, air or ship | under 500 characters                             |
    And I click continue on "CE1179_Multiple_Check Your Answers Page"
    Then I am presented with the "CE1179_Multiple_Claim Submitted Page"

  @test
  Scenario: happy path - don't check importer/declarant eori pages
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    And I select radio button "Enter multiple MRNs" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "CE1179_Multiple_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "CE1179_Multiple_Check Declaration Details Page"
    And I select radio button "yes" on "CE1179_Multiple_Check Declaration Details Page"
    And I click continue on "CE1179_Multiple_Check Declaration Details Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    When I enter "20AAAAAAAAAAAAAAA1" on "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "CE1179_Multiple_Check Movement Reference Numbers Page"
    When I select radio button "No" on "CE1179_Multiple_Check Movement Reference Numbers Page"
    And I click continue on "CE1179_Multiple_Check Movement Reference Numbers Page"
    Then I am presented with the "CE1179_Multiple_Claimant Details Page"
    And I click continue on "CE1179_Multiple_Claimant Details Page"
    Then I am presented with the "CE1179_Multiple_Choose Basis For Claim Page"
    When I select radio button "Defective" on "CE1179_Multiple_Choose Basis For Claim Page"
    And I click continue on "CE1179_Multiple_Choose Basis For Claim Page"
    Then I am presented with the "CE1179_Multiple_Choose Disposal Method Page"
    When I select radio button "Return the goods by road, rail, air or ship" on "CE1179_Multiple_Choose Disposal Method Page"
    And I click continue on "CE1179_Multiple_Choose Disposal Method Page"
    Then I am presented with the "CE1179_Multiple_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "CE1179_Multiple_Enter Rejected Goods Details Page"
    And I click continue on "CE1179_Multiple_Enter Rejected Goods Details Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 1 Page"
    When I select "A80,A95" on "CE1179_Multiple_Select Duties 1 Page"
    And I click continue on "CE1179_Multiple_Select Duties 1 Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 1 Duty Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "CE1179_Multiple_Select Duties 1 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 1 Duty Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "CE1179_Multiple_Select Duties 1 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 2 Page"
    When I select "A90,A85" on "CE1179_Multiple_Select Duties 2 Page"
    And I click continue on "CE1179_Multiple_Select Duties 2 Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 2 Duty Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "CE1179_Multiple_Select Duties 2 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 2 Duty Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "CE1179_Multiple_Select Duties 2 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "CE1179_Multiple_Check Claim Page"
    And I select radio button "yes" on "CE1179_Multiple_Check Claim Page"
    When I click continue on "CE1179_Multiple_Check Claim Page"
    Then I am presented with the "CE1179_Multiple_Enter Inspection Date Page"
    When I enter "10,10,2020" on "CE1179_Multiple_Enter Inspection Date Page"
    And I click continue on "CE1179_Multiple_Enter Inspection Date Page"
    Then I am presented with the "CE1179_Multiple_Inspection Address Choose Type Page"
    When I select radio button "11 Mount Road, London, E10 7PP" on "CE1179_Multiple_Inspection Address Choose Type Page"
    And I click continue on "CE1179_Multiple_Inspection Address Choose Type Page"
    Then I am presented with the "CE1179_Multiple_Check Bank Details Page"
    When I click continue on "CE1179_Multiple_Check Bank Details Page"
    Then I am presented with the "CE1179_Multiple_Choose File Type Page"
    When I select radio button "Commercial invoice" on "CE1179_Multiple_Choose File Type Page"
    And I click continue on "CE1179_Multiple_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "CE1179_Multiple_Check Your Answers Page"
    And I should see the following details
      | This is the basis behind the claim | VAT paid | Import date      | Contact details                                      | Importer email       | Uploaded                        | Contact address                                  | Name on the account | Importer telephone | Importer name    | Account number   | Declarant name     | Importer address                                 | Declarant address                                 | Total  | 20AAAAAAAAAAAAAAA1 | 10AAAAAAAAAAAAAAA1 | First MRN          | Second MRN         | Duties paid | Sort code      | Inspection address type | Inspection date | These are the details of the rejected goods | Inspection address                          | This is how the goods will be disposed of   |
      | Defective                          | £0.00    | 12 February 2021 | Online Sales LTD,automation@gmail.com,+4420723934397 | automation@gmail.com | document.pdf,Commercial invoice | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | CDS E2E To E2E Bank | +4420723934397     | IT Solutions LTD | Ending with 5678 | Foxpro Central LTD | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | £40.00 | £20.00             | £20.00             | 10AAAAAAAAAAAAAAA1 | 20AAAAAAAAAAAAAAA1 | £828.00     | Ending with 44 | Importer address        | 10 October 2020 | under 500 characters                        | 11 Mount Road,London,E10 7PP,United Kingdom | Return the goods by road, rail, air or ship |
    And I click continue on "CE1179_Multiple_Check Your Answers Page"
    Then I am presented with the "CE1179_Multiple_Claim Submitted Page"

  @test @a11y @ZAP
  Scenario: Happy path with no document upload
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    When I select radio button "Enter multiple MRNs" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA2" on "CE1179_Multiple_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "CE1179_Multiple_Enter Importer Eori Page"
    When I enter "GB000000000000002" on "CE1179_Multiple_Enter Importer Eori Page"
    And I click continue on "CE1179_Multiple_Enter Importer Eori Page"
    Then I am presented with the "CE1179_Multiple_Enter Declarant Eori Page"
    When I enter "GB000000000000002" on "CE1179_Multiple_Enter Declarant Eori Page"
    And I click continue on "CE1179_Multiple_Enter Declarant Eori Page"
    Then I am presented with the "CE1179_Multiple_Check Declaration Details Page"
    And I select radio button "yes" on "CE1179_Multiple_Check Declaration Details Page"
    And I click continue on "CE1179_Multiple_Check Declaration Details Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    When I enter "20AAAAAAAAAAAAAAA2" on "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "CE1179_Multiple_Check Movement Reference Numbers Page"
    When I select radio button "No" on "CE1179_Multiple_Check Movement Reference Numbers Page"
    And I click continue on "CE1179_Multiple_Check Movement Reference Numbers Page"
    Then I am presented with the "CE1179_Multiple_Claimant Details Page"
    And I click continue on "CE1179_Multiple_Claimant Details Page"
    Then I am presented with the "CE1179_Multiple_Choose Basis For Claim Page"
    When I select radio button "Defective" on "CE1179_Multiple_Choose Basis For Claim Page"
    And I click continue on "CE1179_Multiple_Choose Basis For Claim Page"
    Then I am presented with the "CE1179_Multiple_Choose Disposal Method Page"
    When I select radio button "Return the goods by road, rail, air or ship" on "CE1179_Multiple_Choose Disposal Method Page"
    And I click continue on "CE1179_Multiple_Choose Disposal Method Page"
    Then I am presented with the "CE1179_Multiple_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "CE1179_Multiple_Enter Rejected Goods Details Page"
    And I click continue on "CE1179_Multiple_Enter Rejected Goods Details Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 1 Page"
    When I select "A80" on "CE1179_Multiple_Select Duties 1 Page"
    And I click continue on "CE1179_Multiple_Select Duties 1 Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 1 Duty Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "CE1179_Multiple_Select Duties 1 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 1 Duty Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 2 Page"
    When I select "A90" on "CE1179_Multiple_Select Duties 2 Page"
    And I click continue on "CE1179_Multiple_Select Duties 2 Page"
    Then I am presented with the "CE1179_Multiple_Select Duties 2 Duty Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "CE1179_Multiple_Select Duties 2 Duty Page"
    And I click continue on "CE1179_Multiple_Select Duties 2 Duty Page"
    Then I am presented with the "CE1179_Multiple_Check Claim Page"
    And I select radio button "yes" on "CE1179_Multiple_Check Claim Page"
    When I click continue on "CE1179_Multiple_Check Claim Page"
    Then I am presented with the "CE1179_Multiple_Enter Inspection Date Page"
    When I enter "10,10,2020" on "CE1179_Multiple_Enter Inspection Date Page"
    And I click continue on "CE1179_Multiple_Enter Inspection Date Page"
    Then I am presented with the "CE1179_Multiple_Inspection Address Choose Type Page"
    When I select radio button "11 Mount Road, London, E10 7PP" on "CE1179_Multiple_Inspection Address Choose Type Page"
    And I click continue on "CE1179_Multiple_Inspection Address Choose Type Page"
    Then I am presented with the "CE1179_Multiple_Check Bank Details Page"
    When I click continue on "CE1179_Multiple_Check Bank Details Page"
    Then I am presented with the "CE1179_Multiple_Choose File Type Page"
    When I select radio button "Commercial invoice" on "CE1179_Multiple_Choose File Type Page"
    And I click continue on "CE1179_Multiple_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue on "UDF_Choose Files Page"
    Then I am presented with the "CE1179_Multiple_Check Your Answers Page"
    And I click continue on "CE1179_Multiple_Check Your Answers Page"
    Then I am presented with the "CE1179_Multiple_Claim Submitted Page"

  @test
  Scenario: error scenario - second mrn not linked to eori
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    When I select radio button "Enter multiple MRNs" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "CE1179_Multiple_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "CE1179_Multiple_Check Declaration Details Page"
    And I select radio button "yes" on "CE1179_Multiple_Check Declaration Details Page"
    And I click continue on "CE1179_Multiple_Check Declaration Details Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    When I enter "10AAAAAAAAAAAAAAA2" on "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number 2 Page" error page

  @test
  Scenario: error scenario - second mrn not linked to importer/declarant eori
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    When I select radio button "Enter multiple MRNs" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA2" on "CE1179_Multiple_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Multiple_Enter Movement Reference Number Page"
    Then I am presented with the "CE1179_Multiple_Enter Importer Eori Page"
    When I enter "GB000000000000002" on "CE1179_Multiple_Enter Importer Eori Page"
    And I click continue on "CE1179_Multiple_Enter Importer Eori Page"
    Then I am presented with the "CE1179_Multiple_Enter Declarant Eori Page"
    When I enter "GB000000000000002" on "CE1179_Multiple_Enter Declarant Eori Page"
    And I click continue on "CE1179_Multiple_Enter Declarant Eori Page"
    Then I am presented with the "CE1179_Multiple_Check Declaration Details Page"
    And I select radio button "yes" on "CE1179_Multiple_Check Declaration Details Page"
    And I click continue on "CE1179_Multiple_Check Declaration Details Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    And I click continue on "CE1179_Multiple_Enter Movement Reference Number 2 Page"
    Then I am presented with the "CE1179_Multiple_Enter Movement Reference Number 2 Page" error page
