@C285 @Single
Feature: C285 Single - XIEORI V2

  Scenario: XIEORI- happy path - check importer/declarant eori pages, change contact details - v2 enabled
    Given I navigate to the "Auth Login Stub Page"
    And I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
#    When the "overpayments v2" feature is "enabled"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "individual" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Have Your Supporting Document Ready Page v2"
    When I clickContinue on "C285_Have Your Supporting Document Ready Page v2"
    Then I am presented with the "C285_Single_Enter Movement Reference Number Page v2"
    When I enter "10XICDAAAAAAAAAAA1" on "C285_Single_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Single_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Single_Enter Importer Eori Page v2"
    When I enter "XI000000000000001" on "C285_Single_Enter Importer Eori Page v2"
    And I click continue on "C285_Single_Enter Importer Eori Page v2"
    Then I am presented with the "C285_Single_Enter Declarant Eori Page v2"
    When I enter "XI000000000000001" on "C285_Single_Enter Declarant Eori Page v2"
    And I click continue on "C285_Single_Enter Declarant Eori Page v2"
    Then I am presented with the "C285_Single_Check Declaration Details Page v2"
#    And I should see the following details
#      | Import MRN         | Import date      | ''  | VAT paid | Importer name    | Importer email       | Importer telephone | Importer address                                 | Declarant name     | Declarant address                                |
#      | 10XICDAAAAAAAAAAA1 | 12 February 2021 | ''  | £0.00    | IT Solutions LTD | automation@gmail.com | +4420723934397     | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | Foxpro Central LTD | 2 Skybricks Road,Coventry,CV3 6EA,United Kingdom |

    When I select radio button "yes" on "C285_Single_Check Declaration Details Page v2"
    And I click continue on "C285_Single_Check Declaration Details Page v2"
    Then I am presented with the "C285_Single_Choose Basis For Claim Page v2"
    When I select radio button "Duplicate Movement Reference Number (MRN)" on "C285_Single_Choose Basis For Claim Page v2"
    And I click continue on "C285_Single_Choose Basis For Claim Page v2"
    Then I am presented with the "C285_Single_Enter Duplicate Movement Reference Number Page v2"
    When I enter "20AAAAAAAAAAAAAAA1" on "C285_Single_Enter Duplicate Movement Reference Number Page v2"
    And I click continue on "C285_Single_Enter Duplicate Movement Reference Number Page v2"
    Then I am presented with the "C285_Single_Check Duplicate Declaration Details Page v2"
    #And I select radio button "yes" on "C285_Single_Check Duplicate Declaration Details Page v2"
    And I click continue on "C285_Single_Check Duplicate Declaration Details Page v2"
    Then I am presented with the "C285_Single_Enter Additional Details Page v2"
    When I enter "under 500 characters" on "C285_Single_Enter Additional Details Page v2"
    And I click continue on "C285_Single_Enter Additional Details Page v2"
    Then I am presented with the "C285_Single_Select Duties Page v2"
    When I select "A80,A95,A90,A85" on "C285_Single_Select Duties Page v2"
    And I click continue on "C285_Single_Select Duties Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Check Claim Page v2"
    # And I select radio button "yes" on "C285_Single_Check Claim Page v2"
    When I clickContinue on "C285_Single_Check Claim Page v2"
    Then I am presented with the "C285_Single_Choose Payee Type v2"
    And I select radio button "Importer" on "C285_Single_Choose Payee Type v2"
    When I click continue on "C285_Single_Choose Payee Type v2"
    Then I am presented with the "C285_Single_Check These Bank Details Are Correct Page v2"
    And I select radio button "yes" on "C285_Single_Check These Bank Details Are Correct Page v2"
    When I click continue on "C285_Single_Check These Bank Details Are Correct Page v2"
    Then I am presented with the "C285_Single_Supporting Evidence Select Supporting Evidence Type Page v2"
    When I select radio button "Commercial invoice" on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page v2"
    And I click continue on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page v2"
    Then I am presented with the "UCDF_Choose File Other Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    Then I am presented with the "C285_Single_Claimant Details Change Claimant Details Page v2"
    And I enter "" on "C285_Single_Claimant Details Change Claimant Details Page v2"
    And I click continue on "C285_Single_Claimant Details Change Claimant Details Page v2"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "C285_Single_Claimant Details Page v2"
    Then I am presented with the "C285_Single_Claimant Details Page v2"
    And I click continue on "C285_Single_Claimant Details Page v2"
#    Then I am presented with the "UDF_Summary Page v2" "1"
#    When I select radio button "No" on "UDF_Summary Page v2"
#    And I click continue on "UDF_Summary Page v2"
    Then I am presented with the "C285_Single_Check Answers Accept Send Page v2"
    And I should see the following details
      | This is the basis behind the claim        | Import date      | Contact details                 | Uploaded                        | Contact address                                   | Name on the account   | Account number                               | This is the reason for the claim                          | EU Duty | Total   | Method                | Method of payment |MRN                | Duties paid | Sort code      |
      | Duplicate Movement Reference Number (MRN) | 12 February 2021 | Mr John Smith,someemail@mail.com,01234567890 | document.pdf,Commercial invoice | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | Mr John Smith    | 11001001 | under 500 characters           | £788.00 | £788.00 | Bank account transfer | Immediate payment |10XICDAAAAAAAAAAA1 | £828.00     | 123456 |
    When I click continue on "C285_Single_Check Answers Accept Send Page v2"
    Then I am presented with the "C285_Single_Claim Submitted Page v2"

  @test
  Scenario: happy path - user selects CMA
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
#    When the "overpayments v2" feature is "enabled"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "individual" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Have Your Supporting Document Ready Page v2"
    When I clickContinue on "C285_Have Your Supporting Document Ready Page v2"
    Then I am presented with the "C285_Single_Enter Movement Reference Number Page v2"
    When I enter "10XICAAAAAAAAAAAA1" on "C285_Single_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Single_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Single_Check Declaration Details Page v2"
    #And I select radio button "yes" on "C285_Single_Check Declaration Details Page v2"
    And I click continue on "C285_Single_Check Declaration Details Page v2"
    Then I am presented with the "C285_Single_Choose Basis For Claim Page v2"
    When I select radio button "Duplicate Movement Reference Number (MRN)" on "C285_Single_Choose Basis For Claim Page v2"
    And I click continue on "C285_Single_Choose Basis For Claim Page v2"
    Then I am presented with the "C285_Single_Enter Duplicate Movement Reference Number Page v2"
    When I enter "20AAAAAAAAAAAAAAA1" on "C285_Single_Enter Duplicate Movement Reference Number Page v2"
    And I click continue on "C285_Single_Enter Duplicate Movement Reference Number Page v2"
    Then I am presented with the "C285_Single_Check Duplicate Declaration Details Page v2"
    #And I select radio button "yes" on "C285_Single_Check Duplicate Declaration Details Page v2"
    And I click continue on "C285_Single_Check Duplicate Declaration Details Page v2"
    Then I am presented with the "C285_Single_Enter Additional Details Page v2"
    When I enter "under 500 characters" on "C285_Single_Enter Additional Details Page v2"
    And I click continue on "C285_Single_Enter Additional Details Page v2"
    Then I am presented with the "C285_Single_Select Duties Page v2"
    When I select "A95,A90,A85" on "C285_Single_Select Duties Page v2"
    And I click continue on "C285_Single_Select Duties Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Check Claim Page v2"
    # And I select radio button "yes" on "C285_Single_Check Claim Page v2"
    When I clickContinue on "C285_Single_Check Claim Page v2"
    Then I am presented with the "C285_Single_Choose Payee Type v2"
    And I select radio button "Importer" on "C285_Single_Choose Payee Type v2"
    When I click continue on "C285_Single_Choose Payee Type v2"
    Then I am presented with the "C285_Single_Select Reimbursement Method Page v2"
    When I select radio button "Current Month Adjustment (CMA)" on "C285_Single_Select Reimbursement Method Page v2"
    And I click continue on "C285_Single_Select Reimbursement Method Page v2"
#    Then I am presented with the "C285_Single_Check These Bank Details Are Correct Page v2"
#    And I select radio button "yes" on "C285_Single_Check These Bank Details Are Correct Page v2"
#    When I click continue on "C285_Single_Check These Bank Details Are Correct Page v2"
    Then I am presented with the "C285_Single_Enter Bank Account Details Page v2"
    And I enter "" on "C285_Single_Enter Bank Account Details Page v2"
    When I click continue on "C285_Single_Enter Bank Account Details Page v2"
    Then I am presented with the "C285_Single_Supporting Evidence Select Supporting Evidence Type Page v2"
    When I select radio button "Commercial invoice" on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page v2"
    And I click continue on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page v2"
    Then I am presented with the "UCDF_Choose File Other Page" "Commercial invoice"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    Then I am presented with the "C285_Single_Claimant Details Change Claimant Details Page v2"
    And I enter "" on "C285_Single_Claimant Details Change Claimant Details Page v2"
    And I click continue on "C285_Single_Claimant Details Change Claimant Details Page v2"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "C285_Single_Claimant Details Page v2"
    And I click continue on "C285_Single_Claimant Details Page v2"
#    Then I am presented with the "UDF_Summary Page" "1"
#    When I select radio button "No" on "UDF_Summary Page"
#    And I click continue on "UDF_Summary Page"
    Then I am presented with the "C285_Single_Check Answers Accept Send Page v2"
    And I should see the following details
      | Basis of claim        | Import date      | Contact details                      | Uploaded                        | Contact address                                     |Account number| Sort code| Name on the account   |Duplicate MRN|Payee                              | Additional claim details                                | A85 - Provisional Anti-Dumping Duty |A90 - Definitive Countervailing Duty| Total   | MRN                |A95 - Provisional Countervailing Duty| Duties paid | Method                         | Method of payment |
      | Duplicate Movement Reference Number (MRN) | 12 February 2021 | Mr John Smith,someemail@mail.com,01234567890  | document.pdf,Commercial invoice | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom |11001001|123456| Mr John Smith |20AAAAAAAAAAAAAAA1|Importer | under 500 characters             | £10.00 | £10.00                | £30.00 | 10XICAAAAAAAAAAAA1 | £10.00     | £828.00                             | Current Month Adjustment (CMA) | Immediate payment |
    When I click continue on "C285_Single_Check Answers Accept Send Page v2"
    Then I am presented with the "C285_Single_Claim Submitted Page v2"

