@C285 @Single
Feature: C285 Single Claim Basis V2

  @test
  Scenario: happy path - Duplicate Movement Reference Number (MRN)
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
#    When the "overpayments v2" feature is "enabled"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "individual" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Single_Enter Movement Reference Number Page v2"
    When I enter "10AAAAAAAAAAAAAAA1" on "C285_Single_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Single_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Single_Check Declaration Details Page v2"
    And I select radio button "yes" on "C285_Single_Check Declaration Details Page v2"
    And I click continue on "C285_Single_Check Declaration Details Page v2"
    Then I am presented with the "C285_Single_Claimant Details Change Claimant Details Page v2"
    And I enter "" on "C285_Single_Claimant Details Change Claimant Details Page v2"
    And I click continue on "C285_Single_Claimant Details Change Claimant Details Page v2"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "C285_Single_Claimant Details Page v2"
    And I click continue on "C285_Single_Claimant Details Page v2"
    Then I am presented with the "C285_Single_Choose Basis For Claim Page v2"
    When I select radio button "Duplicate Movement Reference Number (MRN)" on "C285_Single_Choose Basis For Claim Page v2"
    And I click continue on "C285_Single_Choose Basis For Claim Page v2"
    Then I am presented with the "C285_Single_Enter Duplicate Movement Reference Number Page v2"
    When I enter "20AAAAAAAAAAAAAAA1" on "C285_Single_Enter Duplicate Movement Reference Number Page v2"
    And I click continue on "C285_Single_Enter Duplicate Movement Reference Number Page v2"
    Then I am presented with the "C285_Single_Check Duplicate Declaration Details Page v2"
    And I select radio button "yes" on "C285_Single_Check Duplicate Declaration Details Page v2"
    And I click continue on "C285_Single_Check Duplicate Declaration Details Page v2"
    Then I am presented with the "C285_Single_Enter Additional Details Page v2"
    When I enter "under 500 characters" on "C285_Single_Enter Additional Details Page v2"
    And I click continue on "C285_Single_Enter Additional Details Page v2"
    Then I am presented with the "C285_Single_Select Duties Page v2"
    When I select "A80,A95,A90,A85" on "C285_Single_Select Duties Page v2"
    And I click continue on "C285_Single_Select Duties Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Check Claim Page v2"
    And I select radio button "yes" on "C285_Single_Check Claim Page v2"
    When I click continue on "C285_Single_Check Claim Page v2"
    Then I am presented with the "C285_Single_Choose Payee Type v2"
    And I select radio button "Importer" on "C285_Single_Choose Payee Type v2"
    When I click continue on "C285_Single_Choose Payee Type v2"
#    Then I am presented with the "C285_Single_Check These Bank Details Are Correct Page v2"
#    And I select radio button "yes" on "C285_Single_Check These Bank Details Are Correct Page v2"
#    When I click continue on "C285_Single_Check These Bank Details Are Correct Page v2"
    Then I am presented with the "C285_Single_Enter Bank Account Details Page v2"
    And I enter "" on "C285_Single_Enter Bank Account Details Page v2"
    When I click continue on "C285_Single_Enter Bank Account Details Page v2"
    Then I am presented with the "C285_Single_Supporting Evidence Select Supporting Evidence Type Page v2"
    When I select radio button "Commercial invoice" on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page v2"
    And I click continue on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page v2"
    Then I am presented with the "UCDF_Choose File Other Page" "Commercial invoice"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    Then I am presented with the "C285_Single_Check Answers Accept Send Page v2"
    And I should see the following details
      | Basis of claim        | Import date      | Contact details                                      | Importer email       | Uploaded                        | Contact address                                  | Name on the account | Importer telephone | Importer name    | Account number   | Declarant name     |Payee| Importer address                                 | Additional claim information | Declarant address                                 | A80 - Definitive Anti-Dumping Duty |A85 - Provisional Anti-Dumping Duty|A90 - Definitive Countervailing Duty|A95 - Provisional Countervailing Duty| Total   | Method                | Method of payment |MRN                | Duties paid | Sort code      |
      | Duplicate Movement Reference Number (MRN) | 12 February 2021 | Mr John Smith,someemail@mail.com,01234567890 | automation@gmail.com | document.pdf,Commercial invoice | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | CDS E2E To E2E Bank | +4420723934397     | IT Solutions LTD | Ending with 5678 | Foxpro Central LTD |Importer    | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | under 500 characters             | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | £208.00 | £161.00                                   | £218.00                             | £201.00                              | £788.00 | Bank account transfer | Immediate Payment |10AAAAAAAAAAAAAAA1 | £828.00     | Ending with 44 |
    When I click continue on "C285_Single_Check Answers Accept Send Page v2"
    Then I am presented with the "C285_Single_Claim Submitted Page v2"

  @test
  Scenario: happy path - excise duty selected
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000002" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
#    When the "overpayments v2" feature is "enabled"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "individual" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Single_Enter Movement Reference Number Page v2"
    When I enter "10AAAAAAAAAAAAAAA3" on "C285_Single_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Single_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Single_Check Declaration Details Page v2"
    And I select radio button "yes" on "C285_Single_Check Declaration Details Page v2"
    And I click continue on "C285_Single_Check Declaration Details Page v2"
    Then I am presented with the "C285_Single_Claimant Details Change Claimant Details Page v2"
    And I enter "" on "C285_Single_Claimant Details Change Claimant Details Page v2"
    And I click continue on "C285_Single_Claimant Details Change Claimant Details Page v2"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "C285_Single_Claimant Details Page v2"
    And I click continue on "C285_Single_Claimant Details Page v2"
    Then I am presented with the "C285_Single_Choose Basis For Claim Page v2"
    When I select radio button "Incorrect excise value" on "C285_Single_Choose Basis For Claim Page v2"
    And I click continue on "C285_Single_Choose Basis For Claim Page v2"
    Then I am presented with the "C285_Single_Enter Additional Details Page v2"
    When I enter "under 500 characters" on "C285_Single_Enter Additional Details Page v2"
    And I click continue on "C285_Single_Enter Additional Details Page v2"
    Then I am presented with the "C285_Single_Select Duties Page v2"
    When I select "421,623,99C" on "C285_Single_Select Duties Page v2"
    And I click continue on "C285_Single_Select Duties Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "Excise Duty - Made-wine 421"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "Excise Duty - Tobacco products 623"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "Excise Duty - Climate Change Levy 99C"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Check Claim Page v2"
    And I select radio button "yes" on "C285_Single_Check Claim Page v2"
    When I click continue on "C285_Single_Check Claim Page v2"
    Then I am presented with the "C285_Single_Choose Payee Type v2"
    And I select radio button "Importer" on "C285_Single_Choose Payee Type v2"
    When I click continue on "C285_Single_Choose Payee Type v2"
    Then I am presented with the "C285_Single_Select Reimbursement Method Page v2"
    When I select radio button "Bank account transfer" on "C285_Single_Select Reimbursement Method Page v2"
    When I click continue on "C285_Single_Select Reimbursement Method Page v2"
#    Then I am presented with the "C285_Single_Check These Bank Details Are Correct Page v2"
#    And I select radio button "yes" on "C285_Single_Check These Bank Details Are Correct Page v2"
#    When I click continue on "C285_Single_Check These Bank Details Are Correct Page v2"
    Then I am presented with the "C285_Single_Enter Bank Account Details Page v2"
    And I enter "" on "C285_Single_Enter Bank Account Details Page v2"
    When I click continue on "C285_Single_Enter Bank Account Details Page v2"
    Then I am presented with the "C285_Single_Supporting Evidence Select Supporting Evidence Type Page v2"
    When I select radio button "Commercial invoice" on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page v2"
    And I click continue on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page v2"
    Then I am presented with the "UCDF_Choose File Other Page" "Commercial invoice"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    Then I am presented with the "C285_Single_Check Answers Accept Send Page v2"
    And I should see the following details
      | Basis of claim | Import date      | Contact details                                      | Importer email       | Uploaded                        | Contact address                                  | Name on the account | Importer telephone | Importer name    | Account number   | Declarant name     |Payee|  Importer address                                 | Additional claim information | Declarant address                                 | 421 - Sparkling, 8.5% and above but not exceeding 15% |99C - Gas supplied by a gas utility or any gas supplied in a gaseous state that is of a kind supplied by a gas utility Great Britain|623 - Other smoking tobacco| Total   | MRN                | Duties paid | Sort code      | Method                | Method of payment |
      | Incorrect excise value             | 12 February 2021 | Mr John Smith,someemail@mail.com,01234567890 | automation@gmail.com | document.pdf,Commercial invoice | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | CDS E2E To E2E Bank | +4420723934397     | IT Solutions LTD | Ending with 5678 | Foxpro Central LTD |Importer    |  19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | under 500 characters             | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | £201.00     |£161.00                                                                                                                                                   |£218.00                     | £580.00 | 10AAAAAAAAAAAAAAA3 | £828.00     | Ending with 44 | Bank account transfer | Immediate Payment |
    When I click continue on "C285_Single_Check Answers Accept Send Page v2"
    Then I am presented with the "C285_Single_Claim Submitted Page v2"

  @smoke
  Scenario: happy path - excise journey but excise not selected
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000002" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When the "overpayments v2" feature is "enabled"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "individual" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Single_Enter Movement Reference Number Page v2"
    When I enter "10AAAAAAAAAAAAAAA3" on "C285_Single_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Single_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Single_Check Declaration Details Page v2"
    And I select radio button "yes" on "C285_Single_Check Declaration Details Page v2"
    And I click continue on "C285_Single_Check Declaration Details Page v2"
    Then I am presented with the "C285_Single_Claimant Details Change Claimant Details Page v2"
    And I enter "" on "C285_Single_Claimant Details Change Claimant Details Page v2"
    And I click continue on "C285_Single_Claimant Details Change Claimant Details Page v2"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "C285_Single_Claimant Details Page v2"
    And I click continue on "C285_Single_Claimant Details Page v2"
    Then I am presented with the "C285_Single_Choose Basis For Claim Page v2"
    When I select radio button "Returned goods relief (RGR)" on "C285_Single_Choose Basis For Claim Page v2"
    And I click continue on "C285_Single_Choose Basis For Claim Page v2"
    Then I am presented with the "C285_Single_Enter Additional Details Page v2"
    When I enter "under 500 characters" on "C285_Single_Enter Additional Details Page v2"
    And I click continue on "C285_Single_Enter Additional Details Page v2"
    Then I am presented with the "C285_Single_Select Duties Page v2"
    When I select "A80,421,623,99C" on "C285_Single_Select Duties Page v2"
    And I click continue on "C285_Single_Select Duties Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "Excise Duty - Made-wine 421"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "Excise Duty - Tobacco products 623"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Enter Claim Page v2" "Excise Duty - Climate Change Levy 99C"
    When I enter "10" on "C285_Single_Enter Claim Page v2"
    And I click continue on "C285_Single_Enter Claim Page v2"
    Then I am presented with the "C285_Single_Check Claim Page v2"
    And I select radio button "yes" on "C285_Single_Check Claim Page v2"
    When I click continue on "C285_Single_Check Claim Page v2"
    Then I am presented with the "C285_Single_Choose Payee Type v2"
    And I select radio button "Importer" on "C285_Single_Choose Payee Type v2"
    When I click continue on "C285_Single_Choose Payee Type v2"
    Then I am presented with the "C285_Single_Check These Bank Details Are Correct Page v2"
    When I click continue on "C285_Single_Check These Bank Details Are Correct Page v2"
    And I select radio button "yes" on "C285_Single_Check These Bank Details Are Correct Page v2"
    When I click continue on "C285_Single_Check These Bank Details Are Correct Page v2"
    Then I am presented with the "C285_Single_Supporting Evidence Select Supporting Evidence Type Page v2"
    When I select radio button "Commercial invoice" on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page v2"
    And I click continue on "C285_Single_Supporting Evidence Select Supporting Evidence Type Page v2"
    Then I am presented with the "UCDF_Choose File Other Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    Then I am presented with the "C285_Single_Check Answers Accept Send Page v2"
    And I should see the following details
      | Basis of claim | Import date      | Contact details                                      | Importer email       | Uploaded                        | Contact address                                  | Name on the account | Importer telephone | Importer name    | Account number   | Declarant name     |  Importer address                                 | Additional claim information | Declarant address                                 | EU Duty | Excise Duty | Total   | Method                | Method of payment |MRN                | Duties paid | Sort code      |
      | Returned goods relief (RGR)        | 12 February 2021 | Mr John Smith,someemail@mail.com,01234567890 | automation@gmail.com | document.pdf,Commercial invoice | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | CDS E2E To E2E Bank | +4420723934397     | IT Solutions LTD | Ending with 5678 | Foxpro Central LTD |  19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | under 500 characters             | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | £208.00 | £580.00     | £788.00 | Bank account transfer | Immediate Payment |10AAAAAAAAAAAAAAA3 | £828.00     | Ending with 44 |
    When I click continue on "C285_Single_Check Answers Accept Send Page v2"
    Then I am presented with the "C285_Single_Claim Submitted Page v2"