Feature: Exploratory file using Cucumber

  @Exp
  Scenario: User is a CDS Trader - happy path (entry number) - duplicate Entry Number
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Enter Movement Reference Number Page"
    When I enter "000000001A00000001" on "Enter Movement Reference Number Page"
    And I click continue on "Enter Movement Reference Number Page"
    Then I am presented with the "Entry_Enter Declaration Details Page" and content "000000001A00000001"
    When I enter "" on "Entry_Enter Declaration Details Page"
    And I click continue on "Entry_Enter Declaration Details Page"
    Then I am presented with the "Entry_Who Is The Declarant Page"
    When I select radio button "0" on "Entry_Who Is The Declarant Page"
    And I click continue on "Entry_Who Is The Declarant Page"
    Then I am presented with the "Entry_Enter Your Details As Registered With CDS"
    When I enter "" on "Entry_Enter Your Details As Registered With CDS"
    And I select radio button "yes" on "Entry_Enter Your Details As Registered With CDS"
    And I click continue on "Entry_Enter Your Details As Registered With CDS"
    Then I am presented with the "Entry_Enter Your Contact Details Page"
    When I enter "" on "Entry_Enter Your Contact Details Page"
    And I click continue on "Entry_Enter Your Contact Details Page"
    Then I am presented with the "Entry_Enter Reason For Claim And Basis Page"
    When I select dropdown value "Duplicate Entry,Mail Order Goods – duties not due" on "Entry_Enter Reason For Claim And Basis Page"
    And I click continue on "Entry_Enter Reason For Claim And Basis Page"
    Then I am presented with the "Entry_Enter Duplicate Movement Reference Number Page"
    When I enter "000000002B00000002" on "Entry_Enter Duplicate Movement Reference Number Page"
    And I click continue on "Entry_Enter Duplicate Movement Reference Number Page"
    Then I am presented with the "Entry_Enter Duplicate Declaration Details Page"
    When I enter "" on "Entry_Enter Duplicate Declaration Details Page"
    And I click continue on "Entry_Enter Duplicate Declaration Details Page"
    Then I am presented with the "Entry_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Entry_Enter Commodity Details Page"
    And I click continue on "Entry_Enter Commodity Details Page"
    Then I am presented with the "Entry_Select Duties Page"
    When I select "A00,A20,A30,A35,A40,A45,B00,A50,A70,A80,A85,A90,A95,B05" on "Entry_Select Duties Page"
    And I click continue on "Entry_Select Duties Page"
    Then I am presented with the "Entry_Enter Claim Page" "A00 - Customs Duty"
    When I enter "2,1" on "Entry_Enter Claim Page"
    And I click continue on "Entry_Enter Claim Page"
    Then I am presented with the "Entry_Enter Claim Page" "A20 - Additional Duty"
    When I enter "3,2" on "Entry_Enter Claim Page"
    And I click continue on "Entry_Enter Claim Page"
    Then I am presented with the "Entry_Enter Claim Page" "A30 - Definitive Anti-Dumping Duty"
    When I enter "4,3" on "Entry_Enter Claim Page"
    And I click continue on "Entry_Enter Claim Page"
    Then I am presented with the "Entry_Enter Claim Page" "A35 - Provisional Anti-Dumping Duty"
    When I enter "5,4" on "Entry_Enter Claim Page"
    And I click continue on "Entry_Enter Claim Page"
    Then I am presented with the "Entry_Enter Claim Page" "A40 - Definitive Countervailing Duty"
    When I enter "6,5" on "Entry_Enter Claim Page"
    And I click continue on "Entry_Enter Claim Page"
    Then I am presented with the "Entry_Enter Claim Page" "A45 - Provisional Countervailing Duty"
    When I enter "7,6" on "Entry_Enter Claim Page"
    And I click continue on "Entry_Enter Claim Page"
    Then I am presented with the "Entry_Enter Claim Page" "B00 - Value Added Tax"
    When I enter "8,7" on "Entry_Enter Claim Page"
    And I click continue on "Entry_Enter Claim Page"
    Then I am presented with the "Entry_Enter Claim Page" "A50 - Customs Duty"
    When I enter "9,8" on "Entry_Enter Claim Page"
    And I click continue on "Entry_Enter Claim Page"
    Then I am presented with the "Entry_Enter Claim Page" "A70 - Additional Duty"
    When I enter "10,9" on "Entry_Enter Claim Page"
    And I click continue on "Entry_Enter Claim Page"
    Then I am presented with the "Entry_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "11,10" on "Entry_Enter Claim Page"
    And I click continue on "Entry_Enter Claim Page"
    Then I am presented with the "Entry_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "12,11" on "Entry_Enter Claim Page"
    And I click continue on "Entry_Enter Claim Page"
    Then I am presented with the "Entry_Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "13,12" on "Entry_Enter Claim Page"
    And I click continue on "Entry_Enter Claim Page"
    Then I am presented with the "Entry_Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "14,13" on "Entry_Enter Claim Page"
    And I click continue on "Entry_Enter Claim Page"
    Then I am presented with the "Entry_Enter Claim Page" "B05 - Value Added Tax"
    When I enter "15,14" on "Entry_Enter Claim Page"
    And I click continue on "Entry_Enter Claim Page"
    Then I am presented with the "Entry_Check Claim Page"
    And I select radio button "yes" on "Entry_Check Claim Page"
    When I click continue on "Entry_Check Claim Page"
    Then I am presented with the "Entry_Enter Bank Account Details Page"
    When I enter "" on "Entry_Enter Bank Account Details Page"
    And I select checkbox on "Entry_Enter Bank Account Details Page"
    And I click continue on "Entry_Enter Bank Account Details Page"
    Then I am presented with the "Entry_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Entry_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Entry_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Entry_Supporting Evidence Scan Progress Page"
    When I select dropdown value "Commercial Invoice" on "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Entry_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Entry_Supporting Evidence Check Your Answers Page"
    When I click continue on "Entry_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Entry_Check Answers Accept Send Page"
    And I click continue on "Entry_Check Answers Accept Send Page"
    Then I am presented with the "Entry_Claim Submitted Page"

  @Exp1
  Scenario: User is a CDS Trader - happy path (mrn) - duplicate mrn
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000001,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA1" on "Enter Movement Reference Number Page"
    And I click continue on "Enter Movement Reference Number Page"
    Then I am presented with the "Mrn_Check Declaration Details Page"
    And I click continue on "Mrn_Check Declaration Details Page"
    Then I am presented with the "Mrn_Who Is The Declarant Page"
    When I select radio button "0" on "Mrn_Who Is The Declarant Page"
    And I click continue on "Mrn_Who Is The Declarant Page"
    Then I am presented with the "Mrn_Enter Your Details As Registered With CDS Page"
    And I select radio button "no" on "Mrn_Enter Your Details As Registered With CDS Page"
    And I click continue on "Mrn_Enter Your Details As Registered With CDS Page"
    Then I am presented with the "Mrn_Choose Basis For Claim Page"
    When I select radio button "Duplicate Entry" on "Mrn_Choose Basis For Claim Page"
    And I click continue on "Mrn_Choose Basis For Claim Page"
    Then I am presented with the "Mrn_Enter Duplicate Movement Reference Number Page"
    When I enter "20AAAAAAAAAAAAAAA1" on "Mrn_Enter Duplicate Movement Reference Number Page"
    And I click continue on "Mrn_Enter Duplicate Movement Reference Number Page"
    Then I am presented with the "Mrn_Check Duplicate Declaration Details Page"
    And I click continue on "Mrn_Check Duplicate Declaration Details Page"
    Then I am presented with the "Mrn_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Mrn_Enter Commodity Details Page"
    And I click continue on "Mrn_Enter Commodity Details Page"
    Then I am presented with the "Mrn_Select Duties Page"
    When I select "A80,A95,A90,A85" on "Mrn_Select Duties Page"
    And I click continue on "Mrn_Select Duties Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Check Claim Page"
    And I select radio button "yes" on "Mrn_Check Claim Page"
    When I click continue on "Mrn_Check Claim Page"
    Then I am presented with the "Mrn_Check These Bank Details Are Correct Page"
    When I click continue on "Mrn_Check These Bank Details Are Correct Page"
    Then I am presented with the "Mrn_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Mrn_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Mrn_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Mrn_Supporting Evidence Scan Progress Page"
    When I select dropdown value "Commercial Invoice" on "Mrn_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Mrn_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Mrn_Supporting Evidence Check Your Answers Page"
    When I click continue on "Mrn_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Mrn_Check Answers Accept Send Page"
    And I click continue on "Mrn_Check Answers Accept Send Page"
    Then I am presented with the "Mrn_Claim Submitted Page"
