@Regression @Scheduled @new

Feature: Bulk scheduled

  Background:
    Given the "Bulk Claim" feature is "enabled"
    Given the "Entry Number" feature is "enabled"
    Given the "Northern Ireland" feature is "enabled"

  @test
  Scenario: test temp Ni pages - NI enabled
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000005" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page" and content "GB000000000000005,TestUser"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Number Of Claims Page"
    When I select radio button "schedule" on "Select Number Of Claims Page"
    And I click continue on "Select Number Of Claims Page"
    Then I am presented with the "Scheduled_Enter Movement Reference Number Page"
    When I enter "50AAAAAAAAAAAAAAA1" on "Scheduled_Enter Movement Reference Number Page"
    And I click continue on "Scheduled_Enter Movement Reference Number Page"
    Then I am presented with the "Scheduled_Check Declaration Details Page" and content "50AAAAAAAAAAAAAAA1"
    And I select radio button "yes" on "Scheduled_Check Declaration Details Page"
    And I click continue on "Scheduled_Check Declaration Details Page"
    Then I am presented with the "Scheduled_Who Is The Declarant Page"
    When I select radio button "0" on "Scheduled_Who Is The Declarant Page"
    And I click continue on "Scheduled_Who Is The Declarant Page"
    Then I am presented with the "Mrn_Enter Your Details As Registered With CDS Page"
    And I select radio button "yes" on "Mrn_Enter Your Details As Registered With CDS Page"
    And I click continue on "Mrn_Enter Your Details As Registered With CDS Page"
    Then I am presented with the "Mrn_Enter Your Contact Details Page"
    And I click continue on "Mrn_Enter Your Contact Details Page"
    Then I am presented with the "Scheduled_Claim Northern Ireland Page"
    When I select radio button "Yes" on "Scheduled_Claim Northern Ireland Page"
    And I click continue on "Scheduled_Claim Northern Ireland Page"
    Then I am presented with the "Scheduled_Choose Basis For Claim Page"
    When I select radio button "Incorrect Additional Information code (excluding NIAID) - Northern Ireland claims only" on "Scheduled_Choose Basis For Claim Page"
    And I click continue on "Scheduled_Choose Basis For Claim Page"
    Then I am presented with the "Scheduled_Enter Commodity Details Page"
    When I enter "under 500 characters" on "Scheduled_Enter Commodity Details Page"
    And I click continue on "Scheduled_Enter Commodity Details Page"
    Then I am presented with the "Mrn_Select Duties Page" and content "50AAAAAAAAAAAAAAA1"
    When I select "A20,A35,A90,A85,A95,421,623" on "Mrn_Select Duties Page"
    And I click continue on "Mrn_Select Duties Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A20 - Additional Duty" and content "£218.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A35 - Provisional Anti-Dumping Duty" and content "£211.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A90 - Definitive Countervailing Duty" and content "£228.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty" and content "£171.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "A95 - Provisional Countervailing Duty" and content "£171.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "421 - Made-wine (sparkling), exceeding 8.5% vol. but not exceeding 15% vol." and content "£171.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Enter Claim Page" "623 - Smoking tobacco – other" and content "£171.00"
    When I enter "10" on "Mrn_Enter Claim Page"
    And I click continue on "Mrn_Enter Claim Page"
    Then I am presented with the "Mrn_Check Claim Page"
    And I select radio button "yes" on "Mrn_Check Claim Page"
    When I click continue on "Mrn_Check Claim Page"
    Then I am presented with the "Mrn_Check These Bank Details Are Correct Page"
    When I click continue on "Mrn_Check These Bank Details Are Correct Page"
    Then I am presented with the "Mrn_Supporting Evidence Upload Supporting Evidence Page"
    When I upload a "document.pdf" file on "Mrn_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue on "Mrn_Supporting Evidence Upload Supporting Evidence Page"
    And I click continue if I'm on "Mrn_Supporting Evidence Scan Progress Page"
    When I select dropdown value "Commercial Invoice" on "Mrn_Supporting Evidence Select Supporting Evidence Type Page"
    And I click continue on "Mrn_Supporting Evidence Select Supporting Evidence Type Page"
    Then I am presented with the "Mrn_Supporting Evidence Check Your Answers Page"
    When I click continue on "Mrn_Supporting Evidence Check Your Answers Page"
    Then I am presented with the "Mrn_Check Answers Accept Send Page"
    And I click continue on "Mrn_Check Answers Accept Send Page"
    Then I am presented with the "Mrn_Claim Submitted Page" and content "£70.00"
