@C285 @Scheduled
Feature: C285 Scheduled - XIEORI V2

  @test @wip
  Scenario: happy path - check importer/declarant eori pages
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
#    When the "overpayments v2" feature is "enabled"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "c285" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "C285_Choose How Many Mrns Page v2"
    When I select radio button "schedule" on "C285_Choose How Many Mrns Page v2"
    And I click continue on "C285_Choose How Many Mrns Page v2"
    Then I am presented with the "C285_Scheduled_Have Your Supporting Document Ready Page v2"
    When I clickContinue on "C285_Scheduled_Have Your Supporting Document Ready Page v2"
    Then I am presented with the "C285_Scheduled_Enter Movement Reference Number Page v2"
    When I enter "10XICDAAAAAAAAAAA1" on "C285_Scheduled_Enter Movement Reference Number Page v2"
    And I click continue on "C285_Scheduled_Enter Movement Reference Number Page v2"
    Then I am presented with the "C285_Scheduled_Enter Importer Eori Page v2"
    When I enter "XI000000000000001" on "C285_Scheduled_Enter Importer Eori Page v2"
    And I click continue on "C285_Scheduled_Enter Importer Eori Page v2"
    Then I am presented with the "C285_Scheduled_Enter Declarant Eori Page v2"
    When I enter "XI000000000000001" on "C285_Scheduled_Enter Declarant Eori Page v2"
    And I click continue on "C285_Scheduled_Enter Declarant Eori Page v2"
    Then I am presented with the "C285_Scheduled_Check Declaration Details Page v2"
    #And I select radio button "yes" on "C285_Scheduled_Check Declaration Details Page v2"
    And I click continue on "C285_Scheduled_Check Declaration Details Page v2"
    #New Changes to the flow
    Then I am presented with the "UDF_Choose File Page"
    When I upload a 1 "image.jpg" file on "UDF_Choose File Page"
    And I click continue if I'm on "UDF_Choose File Page"
#    Then I am presented with the "UDF_Summary Page"
#    And I click continue on "UDF_Summary Page"
    Then I am presented with the "C285_Scheduled_Choose Basis For Claim Page v2"
    When I select radio button "Outward processing relief" on "C285_Scheduled_Choose Basis For Claim Page v2"
    And I click continue on "C285_Scheduled_Choose Basis For Claim Page v2"
    Then I am presented with the "C285_Scheduled_Enter Additional Details Page v2"
    When I enter "under 500 characters" on "C285_Scheduled_Enter Additional Details Page v2"
    And I click continue on "C285_Scheduled_Enter Additional Details Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties Select Duty Types Page v2"

    When I select "uk-duty,eu-duty,excise-duty" on "C285_Scheduled_Select Duties Select Duty Types Page v2"
    And I click continue on "C285_Scheduled_Select Duties Select Duty Types Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties Uk Duty Page v2"
    When I select "A00,B00" on "C285_Scheduled_Select Duties Uk Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties Uk Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "A00-Customs Duty"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "B00-Value Added Tax (VAT)"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties Eu Duty Page v2"
    When I select "A50,B05" on "C285_Scheduled_Select Duties Eu Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties Eu Duty Page v2"

    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "A50 - Customs Duty"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "B05 - Value Added Tax (VAT)"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties Excise Duty Page v2"

    When I select "beer,wine,made-wine,low-alcohol-beverages,spirits,cider-perry,other-fermented-products,hydrocarbon-oils,biofuels,miscellaneous-road-fuels,tobacco,climate-change-levy" on "C285_Scheduled_Select Duties Excise Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties Excise Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties Beer Page v2"
    When I select "407,447" on "C285_Scheduled_Select Duties Beer Page v2"
    And I click continue on "C285_Scheduled_Select Duties Beer Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty -407 Beer"
  #"Excise Duty-407 Beer"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-447 Beer"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties Wine Page v2"
    When I select "411,415" on "C285_Scheduled_Select Duties Wine Page v2"
    And I click continue on "C285_Scheduled_Select Duties Wine Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-411 Wine"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-415 Wine"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties Made Wine Page v2"
    When I select "421,429" on "C285_Scheduled_Select Duties Made Wine Page v2"
    And I click continue on "C285_Scheduled_Select Duties Made Wine Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-421 Made-wine"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-429 Made-wine"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"

    Then I am presented with the "C285_Scheduled_Select Duties Low Alcohol Beverages Page v2"
    When I select "301,431" on "C285_Scheduled_Select Duties Low Alcohol Beverages Page v2"
    And I click continue on "C285_Scheduled_Select Duties Low Alcohol Beverages Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-301 Low alcohol beverages"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-431 Low alcohol beverages"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"

    Then I am presented with the "C285_Scheduled_Select Duties Spirits Page v2"
    When I select "315,325" on "C285_Scheduled_Select Duties Spirits Page v2"
    And I click continue on "C285_Scheduled_Select Duties Spirits Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-315 Spirits"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-325 Spirits"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"

    Then I am presented with the "C285_Scheduled_Select Duties Cider Perry Page v2"
    When I select "312,322" on "C285_Scheduled_Select Duties Cider Perry Page v2"
    And I click continue on "C285_Scheduled_Select Duties Cider Perry Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-312 Cider and perry"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-322 Cider and perry"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"

    Then I am presented with the "C285_Scheduled_Select Duties Other Fermented Products Page v2"
    When I select "314,324" on "C285_Scheduled_Select Duties Other Fermented Products Page v2"
    And I click continue on "C285_Scheduled_Select Duties Other Fermented Products Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-314 Other fermented products"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-324 Other fermented products"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"

    Then I am presented with the "C285_Scheduled_Select Duties Hydrocarbon Oils Page v2"
    When I select "511,520" on "C285_Scheduled_Select Duties Hydrocarbon Oils Page v2"
    And I click continue on "C285_Scheduled_Select Duties Hydrocarbon Oils Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-511 Hydrocarbon oil"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-520 Hydrocarbon oil"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"

    Then I am presented with the "C285_Scheduled_Select Duties Biofuels Page v2"
    When I select "589" on "C285_Scheduled_Select Duties Hydrocarbon Oils Page v2"
    And I click continue on "C285_Scheduled_Select Duties Hydrocarbon Oils Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-589 Biofuels"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"

    Then I am presented with the "C285_Scheduled_Select Duties Miscellaneous Road Fuels Page v2"
    When I select "591,592" on "C285_Scheduled_Select Duties Miscellaneous Road Fuels Page v2"
    And I click continue on "C285_Scheduled_Select Duties Miscellaneous Road Fuels Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-591 Miscellaneous road fuels"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-592 Miscellaneous road fuels"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"

    Then I am presented with the "C285_Scheduled_Select Duties Tobacco Page v2"
    When I select "611,633" on "C285_Scheduled_Select Duties Tobacco Page v2"
    And I click continue on "C285_Scheduled_Select Duties Tobacco Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-611 Tobacco products"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-633 Tobacco products"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"

    Then I am presented with the "C285_Scheduled_Select Duties Climate Change Levy Page v2"
    When I select "99A,99D" on "C285_Scheduled_Select Duties Climate Change Levy Page v2"
    And I click continue on "C285_Scheduled_Select Duties Climate Change Levy Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-99A Climate Change Levy"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    Then I am presented with the "C285_Scheduled_Select Duties DutyType Duty Page v2" "Excise Duty-99D Climate Change Levy"
    When I enter "10,5" on "C285_Scheduled_Select Duties DutyType Duty Page v2"
    And I click continue on "C285_Scheduled_Select Duties DutyType Duty Page v2"

    Then I am presented with the "C285_Scheduled_Check Claim Page v2"
    #When I select radio button "Yes" on "C285_Scheduled_Check Claim Page v2"
    And I click continue on "C285_Scheduled_Check Claim Page v2"
    Then I am presented with the "C285_Scheduled_Choose Payee Type v2"
    And I select radio button "Importer" on "C285_Multiple_Choose Payee Type v2"
    When I click continue on "C285_Scheduled_Choose Payee Type v2"
    Then I am presented with the "C285_Scheduled_Enter Bank Account Details Page v2"
    And I enter "" on "C285_Scheduled_Enter Bank Account Details Page v2"
    When I click continue on "C285_Scheduled_Enter Bank Account Details Page v2"
#    Then I am presented with the "C285_Scheduled_Check These Bank Details Are Correct Page v2"
#    When I select radio button "yes" on "C285_Scheduled_Check These Bank Details Are Correct Page v2"
#    And I click continue on "C285_Scheduled_Check These Bank Details Are Correct Page v2"
    Then I am presented with the "C285_Scheduled_Supporting Evidence Select Supporting Evidence Type Page v2"
    When I select radio button "Commercial invoice" on "C285_Scheduled_Supporting Evidence Select Supporting Evidence Type Page v2"
    And I click continue on "C285_Scheduled_Supporting Evidence Select Supporting Evidence Type Page v2"
    Then I am presented with the "UCDF_Choose File Other Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "UCDF_Choose File Other Page"
    And I select radio button "No" on "UCDF_Choose File Other Page"
    And I click continue if I'm on "UCDF_Choose File Other Page"
    #New changes to the flow
    Then I am presented with the "C285_Scheduled_Claimant Details Change Claimant Details Page v2"
    And I enter "" on "C285_Scheduled_Claimant Details Change Claimant Details Page v2"
    And I click continue on "C285_Scheduled_Claimant Details Change Claimant Details Page v2"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "C285_Scheduled_Claimant Details Page v2"
    And I click continue on "C285_Scheduled_Claimant Details Page v2"
    Then I am presented with the "C285_Scheduled_Check Answers Accept Send Page v2"
    And I should see the following details
      | Reason for claim      | Personal details                | Uploaded files                        | Address                                   | Bank details   | Payee                                | Additional claim information                               | EU Duty | UK Duty | Excise Duty | Total        | First Movement Reference Number (MRN)          | Claim summary document |
      | Outward processing relief         | Mr John Smith,someemail@mail.com,01234567890 | Commercial invoice:,document.pdf| 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | Mr John Smith,123456,11001001  | Importer | under 500 characters              | £10.00  | £10.00  | £115.00      | £135.00  | 10XICDAAAAAAAAAAA1 | image.jpg          |
    And I click continue on "C285_Scheduled_Check Answers Accept Send Page v2"
    Then I am presented with the "C285_Scheduled_Claim Submitted Page v2"

