@C&E1179 @Single
Feature: C&E1179 Single

  @test @a11y @ZAP
  Scenario: happy path - check importer/declarant eori pages, change contact details, change bank details
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    And I select radio button "Enter one MRN" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Single_Enter Movement Reference Number Page"
    When I enter "10AAAAAAAAAAAAAAA2" on "CE1179_Single_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Single_Enter Movement Reference Number Page"
    Then I am presented with the "CE1179_Single_Enter Importer Eori Page"
    When I enter "GB000000000000002" on "CE1179_Single_Enter Importer Eori Page"
    And I click continue on "CE1179_Single_Enter Importer Eori Page"
    Then I am presented with the "CE1179_Single_Enter Declarant Eori Page"
    When I enter "GB000000000000002" on "CE1179_Single_Enter Declarant Eori Page"
    And I click continue on "CE1179_Single_Enter Declarant Eori Page"
    Then I am presented with the "CE1179_Single_Check Declaration Details Page"
    When I select radio button "yes" on "CE1179_Single_Check Declaration Details Page"
    And I click continue on "CE1179_Single_Check Declaration Details Page"
    Then I am presented with the "CE1179_Single_Claimant Details Change Claimant Details Page"
    And I enter "" on "CE1179_Single_Claimant Details Change Claimant Details Page"
    And I click continue on "CE1179_Single_Claimant Details Change Claimant Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "CE1179_Single_Claimant Details Page"
    When I click "Change Contact details" on "CE1179_Single_Claimant Details Page"
    Then I am presented with the "CE1179_Single_Claimant Details Change Claimant Details Page"
    And I enter "" on "CE1179_Single_Claimant Details Change Claimant Details Page"
    And I click continue on "CE1179_Single_Claimant Details Change Claimant Details Page"
    Then I am presented with the "CE1179_Single_Claimant Details Page"
    And I click continue on "CE1179_Single_Claimant Details Page"
    Then I am presented with the "CE1179_Single_Choose Basis For Claim Page"
    When I select radio button "Goods are not in accordance with contract" on "CE1179_Single_Choose Basis For Claim Page"
    And I click continue on "CE1179_Single_Choose Basis For Claim Page"
    Then I am presented with the "CE1179_Single_Choose Disposal Method Page"
    When I select radio button "Return the goods by road, rail, air or ship" on "CE1179_Single_Choose Disposal Method Page"
    And I click continue on "CE1179_Single_Choose Disposal Method Page"
    Then I am presented with the "CE1179_Single_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "CE1179_Single_Enter Rejected Goods Details Page"
    And I click continue on "CE1179_Single_Enter Rejected Goods Details Page"
    Then I am presented with the "CE1179_Single_Select Duties Page"
    When I select "A80,A95,A90,A85" on "CE1179_Single_Select Duties Page"
    And I click continue on "CE1179_Single_Select Duties Page"
    Then I am presented with the "CE1179_Single_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "CE1179_Single_Enter Claim Page"
    And I click continue on "CE1179_Single_Enter Claim Page"
    Then I am presented with the "CE1179_Single_Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "CE1179_Single_Enter Claim Page"
    And I click continue on "CE1179_Single_Enter Claim Page"
    Then I am presented with the "CE1179_Single_Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "CE1179_Single_Enter Claim Page"
    And I click continue on "CE1179_Single_Enter Claim Page"
    Then I am presented with the "CE1179_Single_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "CE1179_Single_Enter Claim Page"
    And I click continue on "CE1179_Single_Enter Claim Page"
    Then I am presented with the "CE1179_Single_Check Claim Page"
    When I select radio button "yes" on "CE1179_Single_Check Claim Page"
    And I click continue on "CE1179_Single_Check Claim Page"
    Then I am presented with the "CE1179_Single_Enter Inspection Date Page"
    When I enter "10,10,2020" on "CE1179_Single_Enter Inspection Date Page"
    And I click continue on "CE1179_Single_Enter Inspection Date Page"
    Then I am presented with the "CE1179_Single_Inspection Address Choose Type Page"
    When I select radio button "11 Mount Road, London, E10 7PP" on "CE1179_Single_Inspection Address Choose Type Page"
    And I click continue on "CE1179_Single_Inspection Address Choose Type Page"
    Then I am presented with the "CE1179_Single_Choose Payee Type Page"
    And I select radio button "Importer" on "CE1179_Single_Choose Payee Type Page"
    When I click continue on "CE1179_Single_Choose Payee Type Page"
    Then I am presented with the "CE1179_Single_Check Bank Details Page"
    When I click "Change" on "CE1179_Single_Check Bank Details Page"
    Then I am presented with the "CE1179_Single_Enter Bank Account Details Page"
    When I enter "" on "CE1179_Single_Enter Bank Account Details Page"
    And I click continue on "CE1179_Single_Enter Bank Account Details Page"
    Then I am presented with the "CE1179_Single_Check Bank Details Page"
    And I select radio button "yes" on "CE1179_Single_Check Bank Details Page"
    When I click continue on "CE1179_Single_Check Bank Details Page"
    Then I am presented with the "CE1179_Single_Choose File Type Page"
    When I select radio button "Commercial invoice" on "CE1179_Single_Choose File Type Page"
    And I click continue on "CE1179_Single_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "Yes" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "CE1179_Single_Choose File Type Page"
    When I select radio button "Import or export declaration" on "CE1179_Single_Choose File Type Page"
    And I click continue on "CE1179_Single_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import or export declaration"
    When I upload a 2 "image.jpg" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "CE1179_Single_Check Your Answers Page"
    And I should see the following details
      | This is the basis behind the claim        | Import date      | Contact details                              | Importer email       | Uploaded                                                                | Contact address                                   | Name on the account | Importer telephone | Importer name    | Account number   | Declarant name     | Importer address                                 | Payee |Declarant address                                 | Total   | Method                | Method of payment |MRN                | Duties paid | Sort code      | A85 - Provisional Anti-Dumping Duty | Inspection address type | Inspection date | A90 - Definitive Countervailing Duty | These are the details of the rejected goods | A80 - Definitive Anti-Dumping Duty | Inspection address                          | A95 - Provisional Countervailing Duty | This is how the goods will be disposed of   |
      | Goods are not in accordance with contract | 12 February 2021 | Mr John Smith,someemail@mail.com,01234567890 | automation@gmail.com | document.pdf,Commercial invoice,image.jpg,Import or export declaration | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | Mr John Smith       | +4420723934397     | IT Solutions LTD | Ending with 1001 | Foxpro Central LTD | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | Importer |12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | £788.00 | Bank account transfer | Immediate Payment |10AAAAAAAAAAAAAAA2 | £828.00     | Ending with 56 | £161.00                             | Importer address        | 10 October 2020 | £218.00                              | under 500 characters                        | £208.00                            | 11 Mount Road,London,E10 7PP,United Kingdom | £201.00                               | Return the goods by road, rail, air or ship |
    And I click continue on "CE1179_Single_Check Your Answers Page"
    Then I am presented with the "CE1179_Single_Claim Submitted Page"

  @smoke
  Scenario: happy path - check importer/declarant eori pages, Special circumstances, CMA eligible
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    And I select radio button "Enter one MRN" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Single_Enter Movement Reference Number Page"
      When I enter "10AAAAAAAAAAAAAAA2" on "CE1179_Single_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Single_Enter Movement Reference Number Page"
    Then I am presented with the "CE1179_Single_Enter Importer Eori Page"
    When I enter "GB000000000000002" on "CE1179_Single_Enter Importer Eori Page"
    And I click continue on "CE1179_Single_Enter Importer Eori Page"
    Then I am presented with the "CE1179_Single_Enter Declarant Eori Page"
    When I enter "GB000000000000002" on "CE1179_Single_Enter Declarant Eori Page"
    And I click continue on "CE1179_Single_Enter Declarant Eori Page"
    Then I am presented with the "CE1179_Single_Check Declaration Details Page"
    When I select radio button "yes" on "CE1179_Single_Check Declaration Details Page"
    And I click continue on "CE1179_Single_Check Declaration Details Page"
    Then I am presented with the "CE1179_Single_Claimant Details Change Claimant Details Page"
    And I enter "" on "CE1179_Single_Claimant Details Change Claimant Details Page"
    And I click continue on "CE1179_Single_Claimant Details Change Claimant Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "CE1179_Single_Claimant Details Page"
    And I click continue on "CE1179_Single_Claimant Details Page"
    Then I am presented with the "CE1179_Single_Choose Basis For Claim Page"
    When I select radio button "Special circumstances" on "CE1179_Single_Choose Basis For Claim Page"
    And I click continue on "CE1179_Single_Choose Basis For Claim Page"
    Then I am presented with the "CE1179_Single_Enter Special Circumstances Page"
    When I enter "under 500 characters" on "CE1179_Single_Enter Special Circumstances Page"
    And I click continue on "CE1179_Single_Enter Special Circumstances Page"
    Then I am presented with the "CE1179_Single_Choose Disposal Method Page"
    When I select radio button "Return the goods by road, rail, air or ship" on "CE1179_Single_Choose Disposal Method Page"
    And I click continue on "CE1179_Single_Choose Disposal Method Page"
    Then I am presented with the "CE1179_Single_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "CE1179_Single_Enter Rejected Goods Details Page"
    And I click continue on "CE1179_Single_Enter Rejected Goods Details Page"
    Then I am presented with the "CE1179_Single_Select Duties Page"
    When I select "A95,A90,A85" on "CE1179_Single_Select Duties Page"
    And I click continue on "CE1179_Single_Select Duties Page"
    Then I am presented with the "CE1179_Single_Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "CE1179_Single_Enter Claim Page"
    And I click continue on "CE1179_Single_Enter Claim Page"
    Then I am presented with the "CE1179_Single_Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "CE1179_Single_Enter Claim Page"
    And I click continue on "CE1179_Single_Enter Claim Page"
    Then I am presented with the "CE1179_Single_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "CE1179_Single_Enter Claim Page"
    And I click continue on "CE1179_Single_Enter Claim Page"
    Then I am presented with the "CE1179_Single_Check Claim Page"
    And I select radio button "yes" on "CE1179_Single_Check Claim Page"
    When I click continue on "CE1179_Single_Check Claim Page"
    Then I am presented with the "CE1179_Single_Enter Inspection Date Page"
    When I enter "10,10,2020" on "CE1179_Single_Enter Inspection Date Page"
    And I click continue on "CE1179_Single_Enter Inspection Date Page"
    Then I am presented with the "CE1179_Single_Inspection Address Choose Type Page"
    When I select radio button "11 Mount Road, London, E10 7PP" on "CE1179_Single_Inspection Address Choose Type Page"
    And I click continue on "CE1179_Single_Inspection Address Choose Type Page"
    Then I am presented with the "CE1179_Single_Choose Payee Type Page"
    And I select radio button "Importer" on "CE1179_Single_Choose Payee Type Page"
    When I click continue on "CE1179_Single_Choose Payee Type Page"
    Then I am presented with the "CE1179_Single_Choose Repayment Method Page"
    When I select radio button "cma" on "CE1179_Single_Choose Repayment Method Page"
    And I click continue on "CE1179_Single_Choose Repayment Method Page"
    Then I am presented with the "CE1179_Single_Choose File Type Page"
    When I select radio button "Commercial invoice" on "CE1179_Single_Choose File Type Page"
    And I click continue on "CE1179_Single_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "Yes" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "CE1179_Single_Choose File Type Page"
    When I select radio button "Import or export declaration" on "CE1179_Single_Choose File Type Page"
    And I click continue on "CE1179_Single_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import or export declaration"
    When I upload a 2 "image.jpg" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "CE1179_Single_Check Your Answers Page"
    And I should see the following details
      | This is the basis behind the claim | Import date      | Contact details             | Importer email       | Uploaded                                                                | Contact address                                   | Importer telephone | Importer name    | Declarant name     | Importer address                                 | Declarant address                                 | Total  | MRN                | Duties paid | A85 - Provisional Anti-Dumping Duty | Inspection address type | Inspection date | A90 - Definitive Countervailing Duty | These are the details of the rejected goods | Inspection address                          | A95 - Provisional Countervailing Duty | This is how the goods will be disposed of   | Any special circumstances relating to your claim | Method                         | Method of payment |
      | Special circumstances              | 12 February 2021 | Mr John Smith,someemail@mail.com,01234567890 | automation@gmail.com | document.pdf,Commercial invoice,image.jpg,Import or export declaration | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | +4420723934397     | IT Solutions LTD | Foxpro Central LTD | 19 Bricks Road,Newcastle,NE12 5BT,United Kingdom | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | £580.00 | 10AAAAAAAAAAAAAAA2 | £828.00     | £161.00                              | Importer address        | 10 October 2020 | £218.00                               | under 500 characters                        | 11 Mount Road,London,E10 7PP,United Kingdom | £10.00                                | Return the goods by road, rail, air or ship | under 500 characters                             | Current Month Adjustment (CMA) | Immediate Payment |
    And I click continue on "CE1179_Single_Check Your Answers Page"
    Then I am presented with the "CE1179_Single_Claim Submitted Page"
