@C&E1179 @Single
Feature: C&E1179 Single - XIEORI

  @test
  Scenario: happy path - check importer/declarant eori pages, change contact details, change bank details
    Given I navigate to the "Auth Login Stub Page"
    When I enter redirectURL on "Auth Login Stub Page"
    And I enter Enrollment Key "HMRC-CUS-ORG", ID Name "EORINumber" and ID Value "GB000000000000001" on "Auth Login Stub Page"
    And I click continue on "Auth Login Stub Page"
    Then I am presented with the "Check Eori Details Page"
    When I select radio button "yes" on "Check Eori Details Page"
    And I click continue on "Check Eori Details Page"
    Then I am presented with the "Select Claim Type Page"
    When I select radio button "ce1179" on "Select Claim Type Page"
    And I click continue on "Select Claim Type Page"
    Then I am presented with the "CE1179_Choose How Many Mrns Page"
    And I select radio button "One MRN" on "CE1179_Choose How Many Mrns Page"
    And I click continue on "CE1179_Choose How Many Mrns Page"
    Then I am presented with the "CE1179_Single_Have Your Supporting Document Ready Page v2"
    When I clickContinue on "CE1179_Single_Have Your Supporting Document Ready Page v2"
    Then I am presented with the "CE1179_Single_Enter Movement Reference Number Page"
    When I enter "10XICDAAAAAAAAAAA1" on "CE1179_Single_Enter Movement Reference Number Page"
    And I click continue on "CE1179_Single_Enter Movement Reference Number Page"
    Then I am presented with the "CE1179_Single_Enter Importer Eori Page"
    When I enter "XI000000000000001" on "CE1179_Single_Enter Importer Eori Page"
    And I click continue on "CE1179_Single_Enter Importer Eori Page"
    Then I am presented with the "CE1179_Single_Enter Declarant Eori Page"
    When I enter "XI000000000000001" on "CE1179_Single_Enter Declarant Eori Page"
    And I click continue on "CE1179_Single_Enter Declarant Eori Page"
    Then I am presented with the "CE1179_Single_Check Declaration Details Page"
    And I click continue on "CE1179_Single_Check Declaration Details Page"
     # NEW CHANGE CDSR-3827
    Then I am presented with the "CE1179_Single_Choose Basis For Claim Page"
    When I select radio button "Goods are not in accordance with contract" on "CE1179_Single_Choose Basis For Claim Page"
    And I click continue on "CE1179_Single_Choose Basis For Claim Page"
    Then I am presented with the "CE1179_Single_Choose Disposal Method Page"
    When I select radio button "Return the goods by road, rail, air or ship" on "CE1179_Single_Choose Disposal Method Page"
    And I click continue on "CE1179_Single_Choose Disposal Method Page"
    Then I am presented with the "CE1179_Single_Enter Rejected Goods Details Page"
    When I enter "under 500 characters" on "CE1179_Single_Enter Rejected Goods Details Page"
    And I click continue on "CE1179_Single_Enter Rejected Goods Details Page"
    Then I am presented with the "CE1179_Single_Select Duties Page"
    When I select "A80,A95,A90,A85" on "CE1179_Single_Select Duties Page"
    And I click continue on "CE1179_Single_Select Duties Page"
    Then I am presented with the "CE1179_Single_Enter Claim Page" "A80 - Definitive Anti-Dumping Duty"
    When I enter "10" on "CE1179_Single_Enter Claim Page"
    And I click continue on "CE1179_Single_Enter Claim Page"
    Then I am presented with the "CE1179_Single_Enter Claim Page" "A95 - Provisional Countervailing Duty"
    When I enter "10" on "CE1179_Single_Enter Claim Page"
    And I click continue on "CE1179_Single_Enter Claim Page"
    Then I am presented with the "CE1179_Single_Enter Claim Page" "A90 - Definitive Countervailing Duty"
    When I enter "10" on "CE1179_Single_Enter Claim Page"
    And I click continue on "CE1179_Single_Enter Claim Page"
    Then I am presented with the "CE1179_Single_Enter Claim Page" "A85 - Provisional Anti-Dumping Duty"
    When I enter "10" on "CE1179_Single_Enter Claim Page"
    And I click continue on "CE1179_Single_Enter Claim Page"
    Then I am presented with the "CE1179_Single_Check Claim Page"
    And I clickContinue on "CE1179_Single_Check Claim Page"
    Then I am presented with the "CE1179_Single_Enter Inspection Date Page"
    When I enter "10,10,2020" on "CE1179_Single_Enter Inspection Date Page"
    And I click continue on "CE1179_Single_Enter Inspection Date Page"
    Then I am presented with the "CE1179_Single_Inspection Address Choose Type Page"
    When I select radio button "11 Mount Road, London, E10 7PP" on "CE1179_Single_Inspection Address Choose Type Page"
    And I click continue on "CE1179_Single_Inspection Address Choose Type Page"
    Then I am presented with the "CE1179_Single_Choose Payee Type Page"
    And I select radio button "Importer" on "CE1179_Single_Choose Payee Type Page"
    When I click continue on "CE1179_Single_Choose Payee Type Page"
    Then I am presented with the "CE1179_Single_Enter Bank Account Details Page"
    When I enter "" on "CE1179_Single_Enter Bank Account Details Page"
    And I click continue on "CE1179_Single_Enter Bank Account Details Page"
    Then I am presented with the "CE1179_Single_Choose File Type Page"
    When I select radio button "Commercial invoice" on "CE1179_Single_Choose File Type Page"
    And I click continue on "CE1179_Single_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "commercial invoice"
    When I upload a 1 "document.pdf" file on "UDF_Choose Files Page"
    And I select radio button "Yes" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
    Then I am presented with the "CE1179_Single_Choose File Type Page"
    When I select radio button "Import or export declaration" on "CE1179_Single_Choose File Type Page"
    And I click continue on "CE1179_Single_Choose File Type Page"
    Then I am presented with the "UDF_Choose Files Page" "import or export declaration"
    When I upload a 2 "image.jpg" file on "UDF_Choose Files Page"
    And I select radio button "No" on "UDF_Choose Files Page"
    And I click continue if I'm on "UDF_Choose Files Page"
     # NEW CHANGE CDSR-3827
    Then I am presented with the "CE1179_Single_Claimant Details Change Claimant Details Page"
    And I enter "" on "CE1179_Single_Claimant Details Change Claimant Details Page"
    And I click continue on "CE1179_Single_Claimant Details Change Claimant Details Page"
    And I click "Enter the address manually" on "ALF_Lookup Address Lookup Page"
    And I enter "" on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Edit Page"
    And I click continue on "ALF_Lookup Address Confirm Page"
    Then I am presented with the "CE1179_Single_Check Your Answers Page"
    And I should see the following details
      | Reason for claim                          | Personal details                             | Uploaded files                                                           | Address                                           | Bank details                   |Payee   | Total   | Method                |What do you want to claim?|Movement Reference Number (MRN)  | A85 - Provisional Anti-Dumping Duty  | Inspection date | A90 - Definitive Countervailing Duty | Additional claim information | A80 - Definitive Anti-Dumping Duty | Inspection address                          | A95 - Provisional Countervailing Duty | Disposal method   |
      | Goods are not in accordance with contract | Mr John Smith,someemail@mail.com,01234567890 | Commercial invoice:,document.pdf,Import or export declaration:,image.jpg | 12 Skybricks Road,Coventry,CV3 6EA,United Kingdom | Mr John Smith,123456,11001001  |Importer| £40.00 | Bank account transfer  |A80 - Definitive Anti-Dumping Duty,A95 - Provisional Countervailing Duty,A90 - Definitive Countervailing Duty,A85 - Provisional Anti-Dumping Duty|10XICDAAAAAAAAAAA1 | £10.00               | 10 October 2020 | £10.00                              | under 500 characters                        | £10.00                            | Importer address:,11 Mount Road,London,E10 7PP,United Kingdom | £10.00                               | Return the goods by road, rail, air or ship |
    And I click continue on "CE1179_Single_Check Your Answers Page"
    Then I am presented with the "CE1179_Single_Claim Submitted Page"


